### ISSUE TITLE
how to add a menu ?

### ISSUE THREAD

**Issue by vesper8** [mpociot/botman#103]
I'm not sure if this is in the scope of this project. But I've noticed that a lot of Facebook Messenger bots are integrating a little menu that can be used to navigate to different options or conversations.

These are two bots that make use of the menu

Coding Memes: https://www.messenger.com/t/272687346480612
Alexa Dating: https://www.messenger.com/t/alexadating

I'm wondering how those menus are created, and whether Botman can help or plans to add this feature in the future.

Thanks!

**Comment by mpociot** [comment]
Hi,

Do you mean this menu?

https://developers.facebook.com/docs/messenger-platform/thread-settings/persistent-menu

If that's what you want, it looks like you can just send a request with your menu entries to Facebook. 
Botman would then need a way to listen for those button click events : payloads. 

I already plan to add support to the "Get started" Facebook button, which will be the same kind of payload driver. 

But the menu creation would be out of the scope of BotMan (at least right now).

**Comment by vesper8** [comment]
Yes I meant that one, although it looks different on the messenger.com website or inside the osx messenger client. But it's the same persistent menu.

Would be really cool if you added it to Botman although I don't mind doing things manually of course.

Looking forward to your support of the "Get started" button. Do you think it'll be available soon'ish?

Cheers! Keep up the great work!

**Comment by mpociot** [comment]
You can now listen to "Get started" or Menu postback payloads using this code:

```php
$botman->hears('USER_DEFINED_PAYLOAD', function (BotMan $bot) {
    $bot->reply('Let\'s get started!');
})->driver(FacebookPostbackDriver::DRIVER_NAME);
```

This way, BotMan will only listen for the postback payloads, and will not trigger the method if a user types "USER_DEFINED_PAYLOAD" in the chat!

It's currently only on dev-master.

**Comment by vesper8** [comment]
Hey @mpociot I was wondering if I can use one of botman's FacebookDriver to send the menu to the graph api? I know I could build my own request using guzzle and what not but since the chatbot menu kind of is tied to the chatbot I feel like it would be useful if it was called through Botman.

I tried with this code. But then realized that $botman->getDriver()->getName(); returns an empty string when I try to access the controller route manually.. which got me to thinking of where you actually tell botman to use a specific driver.. and I realized this gets set in the incoming request from the facebook messenger call. So maybe the below code should work and I'm just missing a little something. Or maybe it won't work that way.. I figured instead of losing an hour or two trying to get it to work I'd show it to you first so maybe you can tell me right away if there's something wrong.

```
        $botman = app('botman');
        $botman->verifyServices('2Awl0ot93jJAjfja92BoaFYiFjs44nmAUtQTf5SEezDL6VCLo4Uz');

        $menu = [
            [
                "type" => "postback",
                "title" => "Help",
                "payload" => "DEVELOPER_DEFINED_PAYLOAD_FOR_HELP",
            ],
            [
                "type" => "postback",
                "title" => "Start a New Order",
                "payload" => "DEVELOPER_DEFINED_PAYLOAD_FOR_START_ORDER",
            ],
            [
                "type" => "web_url",
                "title" => "Checkout",
                "url" => "http=>//petersapparel.parseapp.com/checkout",
                "webview_height_ratio" => "full",
                "messenger_extensions" => true,
            ],
            [
                "type" => "web_url",
                "title" => "View Website",
                "url" => "http=>//petersapparel.parseapp.com/",
            ],
        ];

        $parameters = [
            "setting_type" => "call_to_actions",
            "thread_state" => "existing_thread",
            "call_to_actions" => $menu,
        ];

        $botman->getDriver()->post('https://graph.facebook.com/v2.6/me/messages', [], $parameters);
```

**Comment by mpociot** [comment]
Yes, BotMan is focused around hearing commands and therefore it specifies the driver by parsing the incoming requests.

I am not sure if such a command would really be useful inside of BotMan, because it is a one-time only setup process - once you've set up the menu, you won't need it again.

You could as well just copy-paste the example code from the Facebook messenger API website, modify it and edit your page access token.

Maybe I'm going to change my mind, but right now I don't think it fits into BotMan.
