### ISSUE TITLE
Can not get BotMan to work with Slack Event API

### ISSUE THREAD

**Issue by marktopper** [mpociot/botman#108]
I'm using the [Laravel starter kit](https://github.com/mpociot/botman-laravel-starter).

I have gathered a bot token using this url: https://my.slack.com/services/new/bot

However, it doesn't seems to work unless I run `php artisan botman:listen`, but then it still does not support the interactive message buttons.

<img width="1049" alt="skaermbillede 2017-01-07 kl 20 37 35" src="https://cloud.githubusercontent.com/assets/2232539/21744591/28d26898-d519-11e6-8136-5db3a133cdbf.png">

> **Note:** The error from this image is from when I press a button (ex `Tell a joke`)

Sounds like I have to generate an application. However that leaves me with a `Client ID` and a `Client Secret` instead of a token.

**Comment by mpociot** [comment]
Yes, slack is currently quite hard to set up and the readme lacks this process. You will have to create a slack app and get an access token using the slack button Oauth flow. 

I will cover it once I have time to work on the docs.

**Comment by marktopper** [comment]
@mpociot: I can help with documentation.

I managed to get a token by creating a application and logging in to that application.

However, what should I set event request url to in order to have it working.

**Comment by marktopper** [comment]
What Slack events are required for it to work properly?

**Comment by mpociot** [comment]
You can take a look at the blog post I wrote to introduce the package that later became botman: http://marcelpociot.de/blog/2016-10-19-write-your-own-slack-bot-using-laravel
