### ISSUE TITLE
User extended info

### ISSUE THREAD

**Issue by a-komarev** [mpociot/botman#114]
Is there any way to get user info from driver? For example from slack. Because right now message has only internal slack id. I need extended info about channel, and all it's participants (names, avatars) on each hear.

**Comment by mpociot** [comment]
No, that's not possible right now. You would have to gather that information yourself using the `$bot->getMessage()->getUser()` or `$bot->getMessage()->getChannel()` methods and make requests to the driver(s) of your choice to receive the data you need.

**Comment by butteff** [comment]
Hello, I had the same problem and I've started to use [wrapi slack](https://github.com/wrapi/slack) like an additional code to botman for some features.

for example, this methid in botman.php can give info about user:

 ```
   public function getUserInfo($username) {
        $client = new slack($config['slack_token']); //wrapi slack class
        $user = $client->users->info(array("user" => $username));
        return $user['user'];
    }
```

**Comment by mpociot** [comment]
That's nice. I will add it to the documentation. Don't think it makes sense in the core.
