### ISSUE TITLE
[question] What is the best way tho protect botman Laravel route?

### ISSUE THREAD

**Issue by willsilvano** [mpociot/botman#1149]
- BotMan Version: 2.0
- PHP Version: 7.2
- Messaging Service(s):
- Cache Driver: Laravel Cache (Redis)

### Description:
I have a route like that: http://localhost/chatbot

But it is public and anyone who knows that can try massive attack with POST/GET or try to pass fake params.

There are any way the prevent this?

I thought to create middleware, but what i should to check?

My chatbot response to webdriver and TelegramDriver.

**Comment by sergiy-petrov** [comment]
@willsilvano I guess you can change your route to something like /chatbot/{token} and then check if {token} from route params equals to your actual bot token

**Comment by feralheart** [comment]
I agree with @sergiy-petrov 
But you have to update the webhook accordingly

**Comment by sergiy-petrov** [comment]
@feralheart yeah sure!

**Comment by willsilvano** [comment]
@sergiy-petrov Thank you for suggestion. I think is a good idea!
