### ISSUE TITLE
Cannot install Botman Studio in existing Laravel v7.14.1 project

### ISSUE THREAD

**Issue by charlieheslington** [mpociot/botman#1156]
- BotMan Version: #.#.#
- PHP Version: 7.3.16

### Description:
I am unsure how to install Botman Studio into an existing project. The Botman documentation only describes how to do this in Botman v1.5 and I wish to use v2.0. The Botman installer package only seems to create new projects. Is there any way to add Botman into an existing project? 1.5 seemed to have an easy way of installing alongside an existing project and I can't find any way of doing this with Botman 2.0. This looks like an awesome project and I really want to implement it in an application I am making! 

### Steps To Reproduce:
I have tried installing via:
**composer require Botman/Botman** 

- This does not seem to be a full Botman Studio install and the documentation mentions that this is to "use BotMan without the use of BotMan Studio/Laravel" where I am using Laravel and want to use the tools included in Botman Studio.

**composer require botman/studio-addons**

- When attempting to install this package, Composer will not install it as I am using Laravel v7.14.1 "Conclusion: remove laravel/framework v7.14.1"

- I am not sure if this package is a full install of Botman Studio as the repo describes it as "Addons used in combination with BotMan Studio." and as of yet I cannot find a way to install Botman Studio.

**composer require botman/studio**
- I get the following from composer:
    - Installation request for laravel/tinker (locked at v2.4.0, required as ^2.4) -> satisfiable by laravel/tinker[v2.4.0].
    - botman/studio 1.3.0 requires laravel/tinker ~1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - botman/studio 1.3.1 requires laravel/tinker ^1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - Conclusion: don't install laravel/tinker 1.x-dev
    - Installation request for botman/studio ^1.3 -> satisfiable by botman/studio[1.3.0, 1.3.1].
- I have Laravel Tinker v2.4.0 installed within my project

**Comment by feralheart** [comment]
Botman studio is a Laravel 5.8-Botman boilerplate. If you want to install Botman to an existing project I recommend to only install `botman/botman`, then follow the [basic usage without studio](https://botman.io/2.0/installation#basic-usage-without-botman-studio) section.

**Comment by charlieheslington** [comment]
Thanks @feralheart - I was going off information from the Botman website. I am guessing this is no longer a feature, thanks for clearing this up.
