### ISSUE TITLE
Botman throws 502 error when calling $answer->getText()

### ISSUE THREAD

**Issue by GauravG8** [mpociot/botman#1159]
- BotMan Version: 2.6
- PHP Version: 7.2
- Messaging Service(s): DialogFlow
- Cache Driver: default Botman driver - array()

### Description:
Botman is throwing 502 error when calling $answer->getText() in ask function.
From error log: *27 recv() failed (104: Connection reset by peer) while reading response header from upstream,

### Steps To Reproduce:
Added the following in my conversation and it threw the error.
```
          $question = Question::create('Would you like to know more?')
                ->callbackId('agree')
                ->addButtons([
                    Button::create('Yes')->value('yes'),
                    Button::create('No')->value('no'),
                ]);

            $bot->ask($question, function (Answer $answer) {
                $this->reply($answer->getText());
            });
        }
```
When removing the reply, it seems to work correctly. Normal conversation flow is seamless. Only question based flow throws the error.

**Comment by c51x** [comment]
same error for me , how to solve it? is this error only in tinker?

**Comment by GauravG8** [comment]
Nope I faced this in my laravel project where I tried to include the botman library. This seems to be related to the cache config I think. Still not been able to figure it out.

**Comment by filippotoso** [comment]
In a Conversation class:

```
$question = Question::create('Would you like to know more?')
    ->callbackId('agree')
    ->addButtons([
        Button::create('Yes')->value('yes'),
        Button::create('No')->value('no'),
    ]);

$this->ask($question, function (Answer $answer) {
    $this->say($answer->getText());
});
```
