### ISSUE TITLE
Get bot user id

### ISSUE THREAD

**Issue by a-komarev** [mpociot/botman#116]
Is there is a way to get bot User ID?

I found only check if this is a bot.

```php
public function isBot()
{
    return $this->event->has('bot_id');
}
```

What do you think about extending interface with `getBotId()` method? I need this to understand that message is written to the bot and choose right controller to instantiate.

**Comment by mpociot** [comment]
Since bot IDs are slack specific (some messaging drivers don't send back the bot responses at all) it would be better if you would extract that information from the message payload in your own. 

Use:`$bot->getMessage()->getPayload()` for this.

**Comment by a-komarev** [comment]
But there is no info about bot. Only id of user who sent this message.

```
Illuminate\Support\Collection {#654
  #items: array:6 [
    "type" => "message"
    "channel" => "C01HT4B7J"
    "user" => "U03HT4B76"
    "text" => "<@U3NG0FHNW>"
    "ts" => "1483865098.000291"
    "team" => "T03HT4B81"
  ]
}
```
