### ISSUE TITLE
Various questions: how to add locale translation, message tag, OTN, personas, buy button, webview, etc

### ISSUE THREAD

**Issue by jay2success** [mpociot/botman#1160]
Hello,

Thanks for the great package, have some questions:
1. How to setup for bot to handle multiple fb pages with their own conversation logic? (similar to manych*t, etc)
2. How to add locale translation for hear, reply and conversation?
3. How to send message with tag? (https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags)
4. How to setup personas? (https://developers.facebook.com/docs/messenger-platform/send-messages/personas)
5. How to send OTN? (https://developers.facebook.com/docs/messenger-platform/send-messages/one-time-notification)
6. How to use webview? (https://developers.facebook.com/docs/messenger-platform/webview)
7. How to send buy button like manych*t and others?
8. How to test the bot internally, so user can test the bots running like it should be?

Thanks and hoping for your help. Have a nice day.

**Comment by feralheart** [comment]
Hi,
1. Are you using BotMan Studio?

2. You can check the user's locale from checking `getUser()` and you can make different logic based the result.

3-6. I'm not sure if they're implemented yet. You can check the supported features in the [documentation](https://botman.io/2.0/driver-facebook-messenger#supported-features).

7. You can add buttons to any templates via the `addButton('text')->url('your_url)` method

**Comment by jay2success** [comment]
Hi,

Thanks for reply. 
1. No, I am not using botman studio.
2. Ok, thanks for solution.
3-6. Ok, it's fine. I maybe able to fork and add it.
7. The button is not url redirect button, its normal buy button with stripe/paypal integration. I think its using webview, not using standard fb message template.

Any idea how to test the bot locally before making it live on fb messenger? is it using the web widget?

Thanks

> Hi,
> 
> 1. Are you using BotMan Studio?
> 2. You can check the user's locale from checking `getUser()` and you can make different logic based the result.
> 
> 3-6. I'm not sure if they're implemented yet. You can check the supported features in the [documentation](https://botman.io/2.0/driver-facebook-messenger#supported-features).
> 
> 1. You can add buttons to any templates via the `addButton('text')->url('your_url)` method
