### ISSUE TITLE
Botman Integration

### ISSUE THREAD

**Issue by Tidada** [mpociot/botman#1161]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

Hello, 
thank you for the package its awesome, i just wanna know if we can integrate the application to Whatsapp? 

Thank you
### Steps To Reproduce:

**Comment by feralheart** [comment]
Hi,
There is a [3rd party Whatsapp Driver](https://github.com/dextervip/botman-driver-waboxapp) made by @dextervip

**Comment by Tidada** [comment]
hi 
@feralheart  is there any documentation about it?

**Comment by Tidada** [comment]
@feralheart  and can i use conversation in the whatsapp  api? 

Thank you

**Comment by feralheart** [comment]
As I see @dextervip didn't make driver related documentation yet, but for the main part you can use the documentation at [botman.io](https://botman.io/2.0/welcome).
Yes, you can use conversations in any drivers.

**Comment by sherpaxit** [comment]
Hi!! @feralheart   How are you ?! In 360dialog you can use the whatsapp direct API ..  

Is there any chance to make a driver for Whatsapp Direct API ?? 
https://360dialog-waba.api-docs.io/v1/guide/sandbox#2-how-to-use-whatsapp-direct-api-sandbox
Thanks!!!!

**Comment by legreco** [comment]
any updates?

**Comment by filippotoso** [comment]
At this time the focus is on maintaining Botman and subset of the existing drivers.
If you need to support a new platform you should try to write the driver yourself or find someone who can.
A couple of year ago I wrote a Rocket Chat driver because I needed it. It's not too difficult if you use an existing driver (ie. Telegram) as a starting point.

**Comment by legreco** [comment]
Thank you for your answer. I wrote the WhatsApp driver myself.
As you said , it's not too difficult.
Thank you.
