### ISSUE TITLE
Serve botman as an API

### ISSUE THREAD

**Issue by therealkirko** [mpociot/botman#1162]
I've recently been engaged in a task to build a bot for a client so am quite new to botman which is so far great and can do crazy stuff on the fly, however.. Is there a way i can serve botman as an API with laravel? If no, is there a way that it can be implimented? If yes, i would love to see how to go about implementing it.

**Comment by lukrudus** [comment]
Check this documentation it might help you with laravel implementation. 

https://botman.io/2.0/installation

**Comment by therealkirko** [comment]
> Check this documentation it might help you with laravel implementation.
> 
> https://botman.io/2.0/installation

I've gone through the documentation and what is there is implementing it on web, and the various integrations. What am looking for is implementing it through some sort of an API end point.

**Comment by roelofr** [comment]
Looks like you'll have to make [a custom driver][1] for that. 

For example, you could pass a `is-api` parameter to your JSON and match that:

```php
public function matchesRequest()
{
    return $this->event->get('is-api') === true && $this->event->get('message') !== null;
}
```

And then send

```json
{
    "is-api": true,
    "message": "Hello World"
}
```

I'd suggest to make it open source, and to write a spec. If you need help I might be able to help over the weekends :partying_face: 

[1]: https://botman.io/2.0/drivers

**Comment by therealkirko** [comment]
I think this the direction i need to take. @roelofr i would appreciate your help.
