### ISSUE TITLE
Unbinding $this of closure is deprecated

### ISSUE THREAD

**Issue by oleghalin** [mpociot/botman#1166]
- BotMan Version: 2.6.0
- PHP Version: 7.4
- Messaging Service(s): Telegram
- Cache Driver: Laravel (Redis)

### Description:
Im Using botman conversation and askForImages(), i validate images count and if it more then 1 - send repeat(). If I send new image after `repeat()` PHP throws an error `Unbinding $this of closure is deprecated`

**Comment by aliwesome** [comment]
I have same issue, I think it's because of php version.
I'm on 7.4.8

**Comment by oleghalin** [comment]
Hey, any updates on it? Does anyone know whats wrong here?

**Comment by oleghalin** [comment]
I found the issue, it's related to the way Botman works with `opis/closure`. I have a solution for this, I will do more tests and share it.

**Comment by ghost** [comment]
@oleghalin it will be great! - you can share part of solution for collective solve - because this causes for us to. we can help

**Comment by oleghalin** [comment]
@aios issue related to how the closure was serialized after `repeat` called. Basically, we just need to delete `getClosure()` in Conversation.php (lines 185 and 189), it solved the issue with Telegram Driver.

**Comment by oleghalin** [comment]
So, instead of PHP Closure we will send SerializedClosure to `ask()` as argument

**Comment by ghost** [comment]
> So, instead of PHP Closure we will send SerializedClosure to `ask()` as argument

@oleghalin
i think this is "Костыль ибаный" (not reliable solution) because need to overload/edit vendor files - i try to find a way for get overloaded Closures context with return state **( !is_null(closure_context) )**. 

callback not need to return and need to repeat before be validated as `return null` so keep it mind on the $conversation->ask()
and modify when $conversation->askPhotos($question, \Closure $getFirstPhoto, \Closure $getOtherPhoto)

so when we touch first photo by media_group_id inside `$getFirstPhoto` then `$getOtherPhoto` (that will store to __repeat additional params and this will repeat before be validated by return null) will get other photos before `return null`

something like example 

```php
     .....
    private function fillPhotos(array $images): void {
        $this->productData->setImages([
            ...$this->productData->getImages() ?? [],
            ...collect($images)
                ->map(fn(Image $image): ImageObject => new ImageObject($image->getUrl()))
                ->toArray(),
        ]);
    }

    private function askPhotos(): void
    {
        $text = count($this->productData->getImages() ?? []) > 0
            ? 'Прикрепите еще фото. До 5 штук максимум.*'
            : 'Прикрепите фото по одному. До 5 штук максимум.*';

        $question = Question::create($text)
            ->addButtons(ConversationHelpers::createButtons())
            ->callbackId('conversation_get_photo_');




        //Get First Callback
        $getAlbum = function (array $images) {

            $this->fillPhotos($images);
         
        };



        //Get Second Callback
        $getRepeat = function (Answer $answer) {

            //TODO: Get IDENTIFIER
            //$answer->getMessage()->getConversationIdentifier();
            $this->fillPhotos($answer->getMessage()->getImages());

            if (collect($this->productData->getImages())->count() >= 5) {
                $this->say('Максимум можно прикрепить 5 фото.');

                return; /**TODO: something return for null; and on that place i am stoped - because i dont know how detect a last query of media group.**/
            }


            if ($answer->isInteractiveMessageReply()) {
                if ($answer->getValue() === 'photo_continue') {
                    $this->askVideo();

                    return;
                }
            }

            if (ConversationHelpers::isCancel($answer)) {
                $this->say(self::CANCEL_MESSAGE);

                return;
            }


            $this->askVideo();
        };

        $this->askForImages(
            $question,
            $getAlbum,
            $getRepeat
        );
    }
```
#1168 #1109 #1096 #1044 #859 #1054

**Comment by oleghalin** [comment]
@aios it doesn't relate to askForImages(). It relates to the whole logic about Conversation history. I did fork for now and use this repo from my Laravel App. As soon as I sure that it works absolutely I will send PR with commit to 2.0 branch.

**Comment by aliwesome** [comment]
@oleghalin please share your forked repo.

**Comment by oleghalin** [comment]
@aliwesome I still not figure out the source of the issue. But I think its under the hood of opis closure. Basically, i did hard fix for this and this is not a solution at all.

**Comment by aliwesome** [comment]
@oleghalin yeah it's because of `opis/closure` package.
I also saw this [issue](https://github.com/opis/closure/issues/84) but it's not clear to me that how we could solve this and what exactly causes the error.

**Comment by drunkrabbit1** [comment]
Hello, I have found a solution to this error. 

```
protected function registerOpisSecurityKey()
{
    if (Str::startsWith($key = $this->app['config']->get('app.key'), 'base64:')) {
        $key = base64_decode(substr($key, 7));
    }

    SerializableClosure::setSecretKey($key);
}
```

```
use Illuminate\Queue\SerializableClosure;
use Illuminate\Support\Str;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        ...
        $this->registerOpisSecurityKey();
    }
```

**Comment by drunkrabbit1** [comment]
> 
> 
> @oleghalin yeah it's because of `opis/closure` package. I also saw this [issue](https://github.com/opis/closure/issues/84) but it's not clear to me that how we could solve this and what exactly causes the error.

As I understand it, the problem is Laravel conflict between serialization authorization. Hence you need to re-authorize serialization

Hope I can help someone with this answer)
