### ISSUE TITLE
Bot for Broker MQTT

### ISSUE THREAD

**Issue by sergioxdev** [mpociot/botman#1167]
Hi guys, 

congratulations for the work you have done, 
I would like to make a bot for an MQTT broker, there is a way to interface botman on an MQTT broker, so that I can respond to customer requests:
- raw
- xml
- json

Any advice is accepted

**Comment by feralheart** [comment]
Hi @sergioxdev,
Am I right that you are want to create a new driver for an MQTT broker?

**Comment by sergioxdev** [comment]
Hi @feralheart 
yes, i want create a new driver for MQTT
