### ISSUE TITLE
asksForImages (receivesFiles)  not receive files

### ISSUE THREAD

**Issue by nepstor** [mpociot/botman#1168]
- BotMan Version: 2.6.0
- PHP Version: 7.2.26
- Messaging Service(s): Telegram
- Cache Driver: RedisCache

### Description:
When a file is sent, it asksForImages does not receive it

### Steps To Reproduce:
We use Yii2 Framework.

Сode example:
```php
DriverManager::loadDriver(TelegramDriver::class);
$botman = BotManFactory::create($config, new RedisCache('127.0.0.1', 6379));

$botman->hears(KeyboardList::COMMAND_CREATE_ORDER,
    function (BotMan $bot) {
      $bot->startConversation(new CreateOrderConversation());
    }
)->stopsConversation();
```

In conversation
```php
$question = Question::create('Сфотографируйте документ подтверждающий Вашу личность');
$this->askForImages($question, function ($images) {
    // does not enter here
});
```
Another example:
```php
        $botman->receivesFiles(function(BotMan $bot, $images) {
            foreach ($images as $image) {
                $url = $image->getUrl();
                $bot->reply($url);
            }
        });
```
Not work too

**Comment by feralheart** [comment]
I have the same issue in #1096 
Maybe there's a change in the Telegram BotAPI what hasn't added yet in the Telegram driver?

**Comment by php-ninja** [comment]
I have a similar problem, please help me fix it, I have to give up my job today. (

**BotMan Version:** latest
**PHP Version:** 7.4
**Messaging Service(s)**: Telegram
**Cash**: symfony/cache FileSystemAdapter


`  
  public function askDocPhoto() {
        $this->askForImages('Please upload an image.', function ($images) {
            $this->say('thx ');
            // $images contains an array with all images.
        });
    }
`

Nothing is going on.

**Comment by oleghalin** [comment]
Botman has issue with PHP 7.4. Here is no support for Closure serialization, it causes issues in conversation. But I'm using it with Laravel 6.0 and PHP 7.3, everything looks okay. I believe that @mpociot and contributors team will be able to make an upgrade for this package and maybe botman 3.0 will be released :)

**Comment by php-ninja** [comment]
Я не использую Laravel, да и проблема не связана с 7.4 потому что  другие кто столкнулся с той же проблемой, используют PHP 7.2, тут либо с драйвером что-то, либо с самим ботманом.
_______
I do not use Laravel, and the problem is not related to 7.4 because others who have faced the same problem use PHP 7.2.

**Comment by oleghalin** [comment]
@php-ninja I'm using latest Botman and it works perfectly with askImages on telegram driver.

```
            "name": "botman/botman",
            "version": "2.6.0",
```

```
            "name": "botman/driver-telegram",
            "version": "1.6",
```

**Comment by php-ninja** [comment]
Then I don't know what the problem is.
I use the latest version, too.

```php
$botman->hears('img_test', function($bot) {

    $bot->reply('img_test'); // work

    $bot->receivesImages(function($bot, $images) {
        $bot->reply('asdasd'); // not work
        foreach ($images as $image) {
            $url = $image->getUrl();
            $title = $image->getTitle();
            $payload = $image->getPayload();


            $bot->reply('test'); // not work
            $bot->reply($url); // not work
            $bot->reply($title); // not work
            $bot->reply($payload); // not work
        }
    });
});
```


```php

$botman->hears('img_test', function($bot) {

    $bot->reply('img_test'); // work

    $bot->receivesFiles(function($bot, $files) {
        $bot->reply('work!'); // not work
        foreach ($files as $file) {
            $bot->reply('222'); // not work
            $url = $file->getUrl();
            $payload = $file->getPayload();

            $bot->reply($payload); // not work
            $bot->reply($url); //not work

        }
    });
});
```

error_log empty...


**UPDATE**
On the advice of [ this message,](https://github.com/botman/botman/issues/712) I hooked it up:
```php
use BotMan\Drivers\Telegram\TelegramPhotoDrive;
use BotMan\Drivers\Telegram\TelegramFileDrive;
```

but the problem isn't fixed.

```php
    public function askDocPhoto() {

        $this->askForImages('Please upload an image.', function ($images) {
            $this->say('Спасибо '); // not work
            error_log(var_export($images)); // empty error log
        });

    }
```

If I upload the image, nothing happens. If I send a text instead of an image, the phrase "Please upload an image." is repeated.

**Comment by php-ninja** [comment]
Tested for 7.3, no results. It's not working.

**Comment by php-ninja** [comment]
I tried to connect the driver this way:

```php
// Load the driver(s) you want to use
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
```

And I got the next mistake:
```php
Backend fatal error: PHP Fatal error: Uncaught Error: Class 'BotMan\\Drivers\\Telegram\\TelegramFileDrive' not found in /var/www/vendor/botman/botman/src/Drivers/DriverManager.php:173
Stack trace:

#0 /var/www/vendor/botman/botman/src/BotManFactory.php(68): BotMan\\BotMan\\Drivers\\DriverManager->getMatchingDriver(Object(Symfony\\Component\\HttpFoundation\\Request))

#1 /var/www/tbot/tbot.php(58): BotMan\\BotMan\\BotManFactory::create(Array, Object(BotMan\\BotMan\\Cache\\SymfonyCache))

#2 {main}\n thrown in /var/www/vendor/botman/botman/src/Drivers/DriverManager.php on line 173
```

Tested on PHP versions 7.3 and 7.4.

**What am I doing wrong?**

**Comment by php-ninja** [comment]
[The problem has been solved.](https://github.com/botman/botman/issues/712#issuecomment-659557072)

**Comment by ladokutu** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location

**Comment by dj0nr1kk0** [comment]
Add this code
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
// Load the driver(s) foto
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
// Load the driver(s) file
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramLocationDrive::class);
// Load the driver(s) Location
