### ISSUE TITLE
Failing test: it_picks_up_conversations_using_this under PHP7.4

### ISSUE THREAD

**Issue by feralheart** [mpociot/botman#1169]
- BotMan Version: 2.6
- PHP Version: 7.4
- Messaging Service(s): - 
- Cache Driver: -

### Description:
Travis CI output:

```
1) BotMan\BotMan\tests\BotManTest::it_picks_up_conversations_using_this

Failed asserting that exception message 'Serialization of 'ReflectionClass' is not allowed' contains 'called conversation'.
```

It only fails under PHP7.4, on the other versions it pass

**Comment by crynobone** [comment]
Fixed via https://github.com/botman/botman/commit/7e1c6fee9f52e2cbba800d126d65a5907fb78d53
