### ISSUE TITLE
Bot should ignore his own messages

### ISSUE THREAD

**Issue by a-komarev** [mpociot/botman#117]
I found funny thing that bot listening it's own messages, and if another pattern is found - it falls into recursion. It could be solved by checking in each controller if this message was written by bot id and stop script execution, but it's hardcode.

It would be great to have an ability to configurate bot globally to stop to hear it's own messages (completely ignore them).

Example:

```php
$botman->hears('Hello', 'App\Http\Controllers\HelloController');
```
If within this controller bot will send `Hello` in chat - it will go into recursion.

**Comment by mpociot** [comment]
Which driver are you using? This is already fixed in various drivers. That's why the "isBot" message exists on each driver.

**Comment by a-komarev** [comment]
SlackRTM

**Comment by a-komarev** [comment]
`isBot` always returns null :(

**Comment by mpociot** [comment]
Okay. Then I'll take a look at it :)

**Comment by philcross** [comment]
Just experienced the same issue, I've created a PR, but I'm not sure of the implications of this code as this is the first day using this package :)

https://github.com/mpociot/botman/pull/119

**Comment by mpociot** [comment]
Thanks for the PR - merged it.
