### ISSUE TITLE
TODO: Improve documentation

### ISSUE THREAD

**Issue by feralheart** [mpociot/botman#1170]
In this issue I will collect everything what should be included into the documentation.

If you have suggestions send a comment to this issue.

**Comment by sherpaxit** [comment]
Please, How to set up a new driver! 🙏🙏🙏🙏🙏

**Comment by MmKargar** [comment]
telegram buttons documentation.

**Comment by goppi0** [comment]
Integration into existing Laravel apps. This existed in V1.5 and somehow dropped out in v2.

**Comment by cykonetic** [comment]
I've done some pretty deep dives into botman/botman, specifically integrating into Laravel 5.8. My org is preparing to migrate towards Laravel 7.x and possibly 8.0. At the very least I wouldn't mind contributing to the knowledge-base.
As far as what needs documentation, the differences between 
Botman::fallback and Question::fallback
Botman::says and Conversation::says
I get lost among the trees while looking for the forest

**Comment by jlmasson** [comment]
> Please, How to set up a new driver! 🙏🙏🙏🙏🙏

This is so useful. I think it's not clearly explained

**Comment by stsmuniz** [comment]
Using webdriver out of the widget

PLEASE!!!

**Comment by AvneetSingh27** [comment]
> Please, How to set up a new driver! 🙏🙏🙏🙏🙏

Did you managed to write your own custom driver?? @sherpaxit 
My goal is to transfer the chatbot conversation to real agent(live conversation). So I thought of writing my own driver but I am unable to. Please help @mpociot @christophrumpel

**Comment by carrigan223** [comment]
@stsmuniz if you structure the axios post as such `{
    "driver": "web",
    "userId": "lxbpp0",
    "message": "this is the message to send",
    "attachment": null,
    "interactive": "0"
}`

i have been able to get the response from insomnia/postman i am looking for, I haven't spent the time to build and try yet. I imagine though if your post request is structured that way you should be able get a response to build out a custom interface. Hope it helps some.
