### ISSUE TITLE
Is it possible to create multiple chatbots into one application?

### ISSUE THREAD

**Issue by myselfronin** [mpociot/botman#1172]
### Description:
I wanted to create an application from which i can create multiple chatbots from UI itself. I wanted to save the commands and its reply onto a database and query for the commands to reply. So its user based multiple chatbots

**Comment by feralheart** [comment]
Yes it's possible but you have to check and change the tokens on every request in order to work.

**Comment by myselfronin** [comment]
Thank you @feralheart . Also I wanted to generate the hear/listen code from database instead of coding myself. How would you suggest me? I am quite new with these bots so I could help your advice

**Comment by nikitabuida** [comment]
> Thank you @feralheart . Also I wanted to generate the hear/listen code from database instead of coding myself. How would you suggest me? I am quite new with these bots so I could help your advice

You just init two (or any number you want) instances of botman with different configs/drivers and use them separately. Works perfectly.

**Comment by vdomah** [comment]
Just using several instances with same driver will not work because of cache problem. Fixing it in PR https://github.com/botman/botman/pull/1207
