### ISSUE TITLE
Driver for Whatsapp  (360 dialog is a partner that use Whatsapp Api direct)

### ISSUE THREAD

**Issue by sherpaxit** [mpociot/botman#1174]
- BotMan Version: 2.0.0
- PHP Version: 7.2.18
- Messaging Service(s): Whatsapp API Direct
- Cache Driver: 

### Description:
It would be great to have a driver to Whatsapp API direct 
360dialog is a partner of whatsapp that use whatapps api direct

Here is a sandbox  https://docs.360dialog.com/api/whatsapp-api/sandbox
https://developers.facebook.com/docs/whatsapp/api/messages

### Steps To Reproduce:

**Comment by echr** [comment]
Hi, I just create simple gist about how I create Botman Driver for Whatsapp API on my project with other WA Partner. It's very bare minimum (text message only). Hope it will help.

https://gist.github.com/echr/d5141b0a3210462d32ed1fc3a621c371

**Comment by sherpaxit** [comment]
@echr Thanks!! i will try to make the same.. 
Which WA Partner do you use ?
Could you please explain a bit more where to put the files from the gist ?

@feralheart  i try to follow the steps from this docs but are a bit confusing.. https://botman.io/2.0/drivers#introduction. Could you please explain a bit more? 
I paid the video course from @mpociot  and with bad luck he doesn't explain how to make a driver.. :(

**Comment by sherpaxit** [comment]
> Hi, I just create simple gist about how I create Botman Driver for Whatsapp API on my project with other WA Partner. It's very bare minimum (text message only). Hope it will help.
> 
> https://gist.github.com/echr/d5141b0a3210462d32ed1fc3a621c371

@echr Do you know what i am doing wrong ??  Thanks!!!
![image](https://user-images.githubusercontent.com/47509192/88471037-5277d980-ceda-11ea-95b0-88e8edec4bec.png)

**Comment by echr** [comment]
> > Hi, I just create simple gist about how I create Botman Driver for Whatsapp API on my project with other WA Partner. It's very bare minimum (text message only). Hope it will help.
> > 
> > https://gist.github.com/echr/d5141b0a3210462d32ed1fc3a621c371
> 
> @echr Do you know what i am doing wrong ??  Thanks!!!
> ![image](https://user-images.githubusercontent.com/47509192/88471037-5277d980-ceda-11ea-95b0-88e8edec4bec.png)
> 

I think you should import the WhatsappDriver::class (without quote) and make sure the DriverServiceProvider loaded on config app.php

**Comment by sherpaxit** [comment]
> > > Hi, I just create simple gist about how I create Botman Driver for Whatsapp API on my project with other WA Partner. It's very bare minimum (text message only). Hope it will help.
> > > https://gist.github.com/echr/d5141b0a3210462d32ed1fc3a621c371
> > 
> > 
> > @echr Do you know what i am doing wrong ??  Thanks!!!
> > ![image](https://user-images.githubusercontent.com/47509192/88471037-5277d980-ceda-11ea-95b0-88e8edec4bec.png)
> 
> I think you should import the WhatsappDriver::class (without quote) and make sure the DriverServiceProvider loaded on config app.php

Thanks for your answer.  I put without quote , but when i did that and test, when the DriverServiceProvider Load  out this error .
![image](https://user-images.githubusercontent.com/47509192/88478830-a823a480-cf21-11ea-8f04-9d2dc4c6c13a.png)

**Comment by sherpaxit** [comment]
@feralheart  Hi!! , I follow all the steps in docs to make a new Driver and something its wrong but I dont know why .. 😢 
Please Help !
