### ISSUE TITLE
How to save chat logs?

### ISSUE THREAD

**Issue by craiem** [mpociot/botman#1177]
is there a method to save a chat log? 
It would be essential to see the behavior of users with the bot.

Regards

**Comment by benjamintemitope** [comment]
Set Dyanamic Path from the Controller
```php
config(['logging.channels.single.path' => storage_path('logs/chatslog.log')]);
```
`chatslog.log` is the Log File

Generate your Log
```php
\Log::channel('single')->info(print_r($bot->getMessage()->getPayload(),true));
```

**Comment by craiem** [comment]
Thanks!

**Comment by benjamintemitope** [comment]
To prevent storing both Laravel logs and Chat logs to same file

Add this to `config\logging.php`
```php
'channels' => [
       .........

        'chat' => [
          'driver' => 'single',
          'path' => storage_path('logs/chatslog.log'),
       ],
    ],
```
`logs/chatslog.log` is the Log file directory

Generate your Log
```php
\Log::channel('chat')->info(print_r($bot->getMessage()->getPayload(),true));
```
