### ISSUE TITLE
Driver returns null

### ISSUE THREAD

**Issue by marktopper** [mpociot/botman#118]
Inside a conversation I have this in order to try to get the driver name:

```
$driver = $this->bot->getDriver();
```

However it always returns `null` when being triggered from Slack using Slack Events API.

**Comment by mpociot** [comment]
When are you trying to retrieve the driver?

**Comment by marktopper** [comment]
Ohh, I was doing it in the constructor of the conversation.
Should of cause not be there, makes sense.
