### ISSUE TITLE
Unable to connect Botman with microsoft Teams BotFramework

### ISSUE THREAD

**Issue by Paras-Gupta790** [mpociot/botman#1181]
- BotMan Version: 2.x
- PHP Version: 7.2

Hello 

I 'm working on the integration of Microsoft Teams and the PHP client framework in CakePHP (which can save data in the database). This app can't send any messages to endpoint from Bot.

Do I have to register the Bot somewhere? Is there a specific way it has to respond? How can I create a connection?

Regards,
Paras

**Comment by filippotoso** [comment]
I think you have to write a custom driver, setup an application in the Active Directory portal and use it's credentials:

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-send-and-receive-messages?view=azure-bot-service-4.0
