### ISSUE TITLE
Botman 3.0

### ISSUE THREAD

**Issue by xepozz** [mpociot/botman#1182]
Hey.
I started working on version 3.0, which will differ from version 2.0 as follows:
- Rejection of the symfony in favor of psr
- Rejection of laravel collections in favor of arrays
- Rejection of the cache interface in favor of psr 16
- Updating the minimum version of php to 7.4
- Updating all tools and dependencies to the latest versions
- Typing properties, arguments and returned results

If you like this, then I suggest the following plan:
1. Create a 3.x branch for the main package and all dependent ones (drivers, etc.)
2. I will merge some unfinished results into it
3. Once in N time we will update plans, decompose tasks and do this together with other community members.

Thanks.

**Comment by ghost** [comment]
@xepozz Maybe first we try to ask @mpociot for give us feat-way todo's. 
Updates can wait on a mass functionality, cause we need think about all platforms/chats/messengers, not only right now required or supports. 
We need to think about a Botman like an a Platform and way that needs to go.
