### ISSUE TITLE
how to add "say" method ton send a message to the specific driver

### ISSUE THREAD

**Issue by joelkubanza** [mpociot/botman#1183]
- BotMan Version: 2.0
- PHP Version: 7.+
- Messaging Service(s):
- Cache Driver:

Hello everyone
I would like to add a "say" method which will send specific messages to users who use a given driver. I saw some docs to specify the driver with the "hear" method but I would like to specify it with the "say" method. Is it possible?
Thanks for your feedback

this is my simple example code

```php
        $botman->hears("Hello", function ($bot) {

            $bot->reply('hello web user')->driver(WebDriver::DRIVER_NAME);
            $bot->reply('Hello facebook user')->driver(FacebookDriver::DRIVER_NAME);
        });
```

**Comment by filippotoso** [comment]
Just use an IF to change the message depending on the driver in use (using $bot->getDriver()).
