### ISSUE TITLE
Custom message matcher

### ISSUE THREAD

**Issue by butschster** [mpociot/botman#1184]
### Hello guys!

I'm using telegram botman driver and I want to have better compatibility with telegram commands. For example I have pattern `/mycommand {?arg}`, where `arg` - an optional argument, and if somebody send command without args, bot doesn't understand it. Another example `/mycommand1`, if somebody send command with args, `/mycommand1 testarg`, matcher will skip it. 

I suggest to add ability to change Matcher through confing, something like this:
```php
class BotMan
{
    public function __construct(CacheInterface $cache, DriverInterface $driver, $config, StorageInterface $storage)
    {
        ...
        $this->matcher = isset($config['matcher']) ? new $config['matcher'] : new Matcher();
        ...
    }
}
```

or maybe

 ```php
class BotMan
{
    public function __construct(CacheInterface $cache, DriverInterface $driver, $config, StorageInterface $storage, ?Matcher $matcher = null)
    {
        ...
        $this->matcher = $matcher ?: new Matcher();
        ...
    }
}
```

It will allow me to have more control over my commands.

**Comment by butschster** [comment]
This param https://github.com/botman/botman/blob/2.0/src/BotMan.php#L137 is not used.

My new suggestion is

```php
class BotMan
{
   public function __construct(CacheInterface $cache, DriverInterface $driver, $config, StorageInterface $storage, ?Matcher $matcher = null)
   {
       ...
       $this->conversationManager = new ConversationManager($matcher ?: new Matcher());
       ...
   }
}
```

**Comment by agoalofalife** [comment]
@butschster I think is it good idea!👍

**Comment by filippotoso** [comment]
This will be included in the next release.
