### ISSUE TITLE
askForLocation error message

### ISSUE THREAD

**Issue by Antuan01** [mpociot/botman#1185]
- BotMan Version: #.#.#
- PHP Version: 7.2
- Messaging Service(s): Telegram
- Cache Driver: Laravel cache

### Description:

in a conversation, where i ask for a location  $this->askForLocation() , when via telegram the user send his location the bot crashes, the only clue i have is in the logs that says  preg_match expects parameter 2 to be a string, array given in botman/src/Matcher.php: 57.

the bot ask for location, but when the user send the location bot crashes, im stuck pls help 

$this->askForLocation(' send location' , function (Location $location) {
// here it crash
});

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Just tested with the latest version and works correctly.
