### ISSUE TITLE
Integrate botman with Wit.ai

### ISSUE THREAD

**Issue by lekeufackalida** [mpociot/botman#1186]
- BotMan Version: 2.6
- PHP Version:7.2
- Messaging Service(s): laravel 5.8
- Cache Driver:LaravelCache

### Description:
hi, please help me. I'am trying to integrate wit.ai in botman but wit is not sending me any message
i am using controller and a route. I created an account in wit website with one intent named Temp_rature

### Steps To Reproduce:
my controller code : 
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use BotMan\BotMan\BotMan;
use BotMan\BotMan\Middleware\Wit;
$botman=app('botman');
  
    $wit = Wit::create('APIkey');
$botman->middleware->received($wit);
$botman->hears('Temp_rature', function (BotMan $bot) {
    $extras = $bot->getMessage()->getExtras();
    $bot->reply('salut');
   
})->middleware($wit);
   $botman->listen();

**Comment by Tanariel** [comment]
Having somehow the same problem here. Following the same implementation than recommended for dialogflow i can't manage to get anything out of wit.ai with botman.

       `DriverManager::loadDriver(WebDriver::class);

        // Configuration for the BotMan WebDriver
        $config = [];

        // Create BotMan instance
        $botman = BotManFactory::create($config, new RedisCache());

        $witToken = '****';
        $witMw = Wit::create($witToken);

        $botman->middleware->received($witMw);

        $botman->hears('how_to_pay', function (BotMan $bot) {
            $bot->reply('Nous acceptons la CB, paypal et les bitcoins.');
        })->middleware($witMw);

        // Set a fallback
        $botman->fallback(function (BotMan $bot) {
            $extras = $bot->getMessage()->getExtras();
            $entities = $extras['entities'] ?? null;
            $bot->reply("this is what you told me : " . print_r($bot->getMessage(), true) . ", " . print_r($entities, true));
        });

        // Start listening
        $botman->listen();`

the wit.ai receive correctly all the request, matches it with the intent 'how_to_pay' but the chatbot always replies the fallback answer. Somehow the middleware seems to only match entities ? not intent ? 
Does anyone have a working example please ?

Thanks much.

**Comment by Tanariel** [comment]
from what I have investigated, wit.ai seems to have changed response formats from :

`{
"_text": "let us test something",
"entities": {
    "intent": [
        {
            "confidence": 0.98564616435397,
            "value": "test"
        }
    ]
},
"msg_id": "0CEKZSrnsdfunDHM8b9R"
}
`

to 

`{
"text":"Comment puis-je payer ?",
"intents":[{"id":"805519943625412","name":"how_to_pay","confidence":0.9992}],
"entities":{},
"traits":{"wit$on_off":[{"id":"53679cd0-fa41-420b-a759-44c4faec406e","value":"on","confidence":0.974}]}}`

The intents now have their own key instead of being parts of the entities.

**Comment by Tanariel** [comment]
created merge request #1195 
I'll be glad to update the tests if someone (preferably a maintainer) confirms the diagnostic.

Putin this as reference for quick check : 
https://wit.ai/docs/http/20200513/#get__message_link

**Comment by Tanariel** [comment]
![Capture d’écran 2020-09-09 à 16 13 57](https://user-images.githubusercontent.com/1983686/92603145-a4709500-f2b7-11ea-850e-e87e45c41f93.png)

![Capture d’écran 2020-09-09 à 16 14 05](https://user-images.githubusercontent.com/1983686/92603141-a33f6800-f2b7-11ea-9267-e6dc306bdf5e.png)

![Capture d’écran 2020-09-09 à 16 14 12](https://user-images.githubusercontent.com/1983686/92603136-a20e3b00-f2b7-11ea-8ab5-aff238ff90d8.png)

**Comment by lekeufackalida** [comment]
Bonjour Tanariel finalement as tu obtenu les resultats attentus?

**Comment by Tanariel** [comment]
@lekeufackalida Yes it's working perfectly with the patch.

**Comment by lekeufackalida** [comment]
Please can you share tour code and explain it to me

**Comment by Tanariel** [comment]
Just pull the last version and your code should work with it. Or look at the merge request #1195

**Comment by lekeufackalida** [comment]
Ok thank you i will it and tell you

**Comment by lekeufackalida** [comment]
Hello Tanariel i have tried the code and i don't have response and i can
refresh the page too i don't know what is the problem please can you help
me?

Le mar. 29 sept. 2020 à 20:31, alida bertille <lekeufackalida@gmail.com> a
écrit :

**Comment by Tanariel** [comment]
did you check if the question are correctly received by wit ? in your interface you should see them.

**Comment by lekeufackalida** [comment]
Wit receive the message but do notre return a response

**Comment by andreper** [comment]
Hello.
I have the same issue. I receive the message from Wit but Botman doesn't return any response. Could somebody help me, please?

This is my code:

$adapter = new FilesystemAdapter();
$botman = BotManFactory::create($config, new SymfonyCache($adapter));
$witMw = Wit::create(_WIT_TOKEN_);
$botman->middleware->received($witMw);

$botman->hears('booking', function (Botman $bot) {
    $extras = $bot->getMessage()->getExtras();
    $bot->reply("Welcome to this chatbot ");
})->middleware($witMw);

$botman->listen();

**Comment by scramatte** [comment]
Hello, any news about this integration?
