### ISSUE TITLE
send Message Replies with Attachments file 

### ISSUE THREAD

**Issue by Yepez** [mpociot/botman#1196]
- BotMan Version: 2.6
- PHP Version: 7.1
- Messaging Service(s): Microsoft 
- Cache Driver:

### Description:
hi good morning, i have question
how do botman send  files, I have tried it but there is no response ? and
what files are allowed to send ?

```php
$botman->hears('i', function ($bot) {

$attachment = new File('http://africau.edu/images/default/sample.pdf', [
'custom_payload' => true,
]);

// Build message object
$message = OutgoingMessage::create('This is my text')
            ->withAttachment($attachment);

// Reply message object
$bot->reply($message);
});
```

### Steps To Reproduce:

**Comment by MuriloCarvalhoo** [comment]
I'm having the same problem, I've tried Tinker and Web Widget and it doesn't send as much from online file as it sends from my app.

**Comment by filippotoso** [comment]
As far as I understand, the web widget supports only image, audio and video attachments:

https://github.com/botman/web-widget/blob/master/src/chat/messages/text.tsx
