### ISSUE TITLE
Botman with Existing Lumen App Facebook Integration not able to do(Error:The call back URL or verify token could not be validated)

### ISSUE THREAD

**Issue by riyazpt** [mpociot/botman#1200]
- BotMan Version: "^2.6",
   botman/driver-facebook: "^1.10",
- PHP Version:PHP 7.2.27
- Messaging Service(s):Facebook
Lumen (6.3.3) 
### Description:

I was trying to integrate Botman  with existing lumen App .I followed the steps but not able to set call back URL of Facebook.

**Error:The call back URL or verify token could not be validated.**.

_

> But with same token and app_secret I am able to set up chatbot with botman studio without any problem.

_
Is there any additional setting I need to do with lumen.

### Code

`<?php
namespace App\Http\Controllers\botman;
use App\Http\Controllers\Controller;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
class BotmanController extends Controller
{
public function getFacebookchat()
{
  $config=[
  'facebook' => [
  	'token' => 'xx',
   	'app_secret' => 'xxx',
    'verification'=>'xxx',
   
    
  ]
  ];

  // Load the driver(s) you want to use
  DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);
 
  // Create an instance
  $botman = BotManFactory::create($config);

  // Give the bot something to listen for.
  $botman->hears('hello', function (BotMan $bot) {
      $bot->reply('Hello yourself.');
  });
  $botman->fallback(function($bot) {
    $bot->reply('You said: '.$bot->getMessage()->getText());
});
  
  // Start listening
  $botman->listen();
}}`

and route is

`$router->get('/botman', 'botman\BotmanController@getFacebookchat')`.

**Comment by filippotoso** [comment]
Add also support for the POST request.
