### ISSUE TITLE
How Connecting Botman to multiple Facebook pages

### ISSUE THREAD

**Issue by s4rrow** [mpociot/botman#1210]
- BotMan Version: 2.0
- PHP Version: 7.2
- Messaging Service(s):Messenger

Description:
how could I connect a Messenger chatbot to multiple Facebook pages.
i find this topic: https://github.com/botman/botman/issues/865
But i can not use. 
Can someone provide a ready code.

**Comment by feralheart** [comment]
You should check the Facebook page id what's in the payload and change'n'reload the bot tokens in a Middleware.

**Comment by s4rrow** [comment]
> You should check the Facebook page id what's in the payload and change'n'reload the bot tokens in a Middleware.

Thanks for information, but still i cant do this. 
do you have a ready solution?
