### ISSUE TITLE
[ASK] Cannot continue conversation

### ISSUE THREAD

**Issue by sulfanoaf** [mpociot/botman#1212]
- BotMan Version: ~2.0
- PHP Version: 7.3
- Messaging Service(s): Telegram
- Cache Driver:

### Description:
I've a conversation. in this conversation i start to run other conversation. the code is below

```
     private function showCalendar()
    {
        $this->bot->startConversation(new BotmanCalendarConversation(new SerializableClosure(function ($date) {
            \Log::debug($date); // HAS OUTPUT
            $this->showDate($date);
        })));
    }

    private function showDate($date)
    {
        \Log::debug($date); // HAS OUTPUT
        $this->say($date); // THIS IS NOT WORK
    }
```

BotmanCalendarConversation
```
public function runCallBack()
    {
        if (!is_null($this->callback)) {
            $callback = $this->callback;
            // $callback($date);
            serialize($callback($this->selected_date));
        }
    }
```

its cannot continue conversation anymore.
`$this->say()` returning `Call to a member function reply() on null`

How to solve this ?

thankyou

**Comment by filippotoso** [comment]
This is an edge case not handled by Botman (SerializableClosure with $this used inside).

I suggest you to refactor your code to avoid using SerializableClosure.
