### ISSUE TITLE
Cannot install botman

### ISSUE THREAD

**Issue by Ahmard** [mpociot/botman#1213]
- BotMan Version: #.#.#
- PHP Version: 7.4.11
- Messaging Service(s):
- Cache Driver:

### Description: 
our requirements could not be resolved to an installable set of packages.

  Problem 1
    - botman/studio-addons[1.3.0, ..., 1.6.1] require thecodingmachine/discovery ^1.2 -> satisfiable by thecodingmachine/discovery[v1.2.0, v1.2.1].
    - thecodingmachine/discovery[v1.2.0, ..., v1.2.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires botman/studio-addons ~1.3 -> satisfiable by botman/studio-addons[1.3.0, ..., 1.6.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

### Steps To Reproduce: Try to install botman by running "composer create-project --prefer-dist botman/studio chatbot"

**Comment by komarove** [comment]
Same problem

**Comment by roelofr** [comment]
The discovery package seems incompatible with Composer 2.0, so try these steps:

1. Run `composer upgrade` to update to the most recent version, if that fails
2. Run `composer upgrade` but remove `vendor` and `composer.lock` first, if that fails too
3. downgrade Composer to 1.0 (`composer self-update --1`) to resolve it for now (it doesn't solve the problem, though).

**Comment by Ahmard** [comment]
> The discovery package is incompatible with Composer 2.0, downgrade Composer to 1.0 (`composer self-update --1`) to resolve it for now (it doesn't solve the problem, though).
> 
> As the discovery package hasn't been updated in 4 years, I'm afraid we'll have to look for a different solution (maybe something like how Laravel discovers packages?)

After downgrading to composer v1, it works.
Thank you.

**Comment by HVSoftware** [comment]
Looks like this is not a composer issue. I also encounted some issue. Can you try these steps after you have run `composer create-project`?

- Run `composer upgrade`

This worked for me, also with Composer 2.0

**Comment by Ahmard** [comment]
> Looks like this is not a composer issue. I also encounted some issue. Can you try these steps after you have run `composer create-project`?
> 
>     * Run `composer upgrade`
> 
> 
> This worked for me, also with Composer 2.0

Yeah, it works.
Thank you.

**Comment by askaaqib** [comment]
Same Problem
