### ISSUE TITLE
Need more Curl methods

### ISSUE THREAD

**Issue by moiz2050** [mpociot/botman#1215]
- BotMan Version: 2.6.1
- PHP Version:7.3
- Messaging Service(s): Facebook

### Description:
Right now `Http\Curl` only support GET and POST,  I think we should have more methods in it like `DELETE` or `PUT` because right now I am using facebook driver and I need to remove a persistent menu (it needs to have a DELETE request), I suggest that Botman library should be provided that Http methods by default.

**Comment by filippotoso** [comment]
It's available in tag 2.7.2
