### ISSUE TITLE
how to implement multiple bots in one application?

### ISSUE THREAD

**Issue by senobarii** [mpociot/botman#1216]
Hi, I need to implement multiple bots to handle them in one application based on domain, how is it possible? appreciate that you may share me any example or tutorial. thanks.

**Comment by vdomah** [comment]
Hi, the last commit of mine in botman allows exactly that. bit_id parameter was added to have ability to instantiate the exact bot you need from one application. 

For example you got endpoint for webhook Route::post('/botman/{bot_id?}'

Then you're able to inject bot's token or other config for particular bot_id:
````
//here you got $config for default bot

if ($bot_id) {
            //use $bot_id to grab your config info from db or elsewhere
           // you now got your bot $token somehow and set to config array:
            $config['telegram']['token'] = $token;
        }
// instantiate the botman 
        $botman = BotManFactory::create($config, new LaravelCache);
````

Would be glad to see your feedback on the subject and if you have any issues.

**Comment by poplach** [comment]
@vdomah Works well, but I also had to change `loadMessages()` method in **TelegramDriver** for it to work. I just added fifth parameter the same way `$this->config->get('bot_id')`
