### ISSUE TITLE
types should allow a timeout like typesAndWaits, but without a sleep in the backend

### ISSUE THREAD

**Issue by vesper8** [mpociot/botman#1219]
Frankly I do not at all understand the reasoning behind the `sleep()` inside of typesAndWaits. Since the typing indicator is shown on the front-end, it makes no sense to sleep in the backend.. unless the front-end is programmed to immediately and always activate a typing indicator until a response is received which might make sense.

In my case I want to be able to control how long the typing indicator appears on the front-end but using `types` sets a default timeout of 1 (no sleep on the back-end, but this is an instruction that can be interpreted by the front-end). I would like to change this timeout so that I can occasionally use a typing indicator that is of a length determined by the back-end conversation logic, but not ALWAYS show one

**Comment by poplach** [comment]
What I do in Telegram - I use `types`, then I do some back-end logic and then I send a message.
Telegram automatically cancels the writing when a new message is received - that's logic of Telegram.

**Comment by poplach** [comment]
What driver you're using?
Telegram automatically cancels the writing when a new message is received - that's logic of Telegram.
What I do in Telegram - I use `types`, then I do some back-end logic and then I send a message. If I want continue with `types`, I have to call it again.

**Comment by vesper8** [comment]
> What driver you're using?

I'm using the web driver, my chat bots are web based

**Comment by poplach** [comment]
I never worked with web driver, but what you can do is to check its methods:
```
    /**
     * @param IncomingMessage $matchingMessage
     * @return void
     */
    public function types(IncomingMessage $matchingMessage)
    {
        $this->replies[] = [
            'message' => TypingIndicator::create(),
            'additionalParameters' => [],
        ];
    }

    /**
     * Send a typing indicator and wait for the given amount of seconds.
     * @param IncomingMessage $matchingMessage
     * @param float $seconds
     * @return mixed
     */
    public function typesAndWaits(IncomingMessage $matchingMessage, float $seconds)
    {
        $this->replies[] = [
            'message' => TypingIndicator::create($seconds),
            'additionalParameters' => [],
        ];
    }
```

And see that the only difference is that it creates `TypingIndicator` with seconds.
If you take a look at `TypingIndicator` class you will see that in construct method 1 second is the default value:
```
    /**
     * @param float $timeout
     * @return TypingIndicator
     */
    public static function create(float $timeout = 1)
    {
        return new static($timeout);
    }
```
 that's why you get 1 second typing when you use `$botman->types()`.

Now take a look at another driver method `sendPayload`:
```
    /**
     * @param mixed $payload
     * @return Response
     */
    public function sendPayload($payload)
    {
        $this->replies[] = $payload;
    }
```
So in the end something like this should work just fine:
```
$seconds = 3;
$botman->sendPayload([
    'message' => TypingIndicator::create($seconds),
    'additionalParameters' => [],
]);
```
