### ISSUE TITLE
Hear doesn't work with wit middleware

### ISSUE THREAD

**Issue by khaledelmahdi** [mpociot/botman#122]
Hello,

I have this code:
```
        $config = [
            'microsoft_app_id'     => $this->dbbot->microsoft_app_id,
            'microsoft_app_key'    => $this->dbbot->microsoft_app_key,
            'microsoft_bot_handle' => $this->dbbot->name
        ];

        $millow = BotFactory::create($config, new LaravelCache(), $request, new FileStorage(storage_path('bot')));

        $millow->hears('test', function (myBot $bot) use ($id) {
            $bot->reply('This is a test!');
        });

        $millow->middleware(Wit::create('*********'));
        $millow->fallback(function (myBot $bot) use ($id) {
            $bot->userStorage()->save(['id' => $id], 'bot');
            $this->getContact($bot, $id);
            $extras   = $bot->getMessage()->getExtras();
            $entities = $extras['entities'];
            try {
                $intent = $entities['intent'][0]['value'];
                switch ($intent) {
                    case "greetings":
                        return $bot->randomReply(trans('bot.random.greetings'));
                        break;
                    case "info":
                        return $bot->reply(trans('bot.random.info', [
                            'name'    => $this->dbbot->name,
                            'company' => $this->dbbot->company
                        ]));
                        break;
                    default:
                        return $bot->reply('The intent is: ' . $intent);
                        break;
                }
            } catch (\Exception $e) {
                $bot->reply('Sorry, I did not understand you.');
            }
        });

        $millow->listen();
```

If I type 'test' on the bot, I get the message 'Sorry, I did not understand you.'

If I remove the line `$millow->middleware(Wit::create('*********'));` and type test, I get the correct reply 'This is a test!'.

I am using Laravel.

Is this a bug or I am doing something wrong?

Thank you.

**Comment by mpociot** [comment]
Hi!

It depends on how you set up wit.ai
The middleware is currently listening for a wit.ai entity called `intent`.
See: https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Middleware/Wit.php#L73

So the text you put in `hears` is matched against the entity called `intent` that you need to set up in wit.ai.

I'm still working on the documentation (there's already a docs repo at https://github.com/mpociot/botman-docs)

**Comment by khaledelmahdi** [comment]
Hi,

Sorry, I didn't explain my situation. What I am trying to do is the following:

Have a bunch of 'secret' command like setup, clear, ....
These commands will be in the form of: `$bot->hears('setup', ...`

Then I'll have anything else being parsed by wit

Hope this made it clear.

**Comment by mpociot** [comment]
Ahh okay - so you don't want everything to run through your middleware, but only some of your commands.

Hmm..maybe it would be best to have something like the chainable `->driver(...` method for this?

Like:

```php
$middleware = WitAi::create('xxx');

$bot->hears('setup', function($bot){});
$bot->hears('test', function($bot){})->middleware($middleware);
$bot->hears('foo', function($bot){})->middleware($middleware);
```

**Comment by khaledelmahdi** [comment]
Getting an error `Call to undefined method Command::middleware()`!

**Comment by mpociot** [comment]
Yeah, it's not implemented yet. His was more meant as an idea how the implementation for this might look like.

**Comment by mpociot** [comment]
Implemented in `dev-master`
https://github.com/mpociot/botman/commit/66d8da5b2192ad2ac145da2fc7ea6caadc93e2ff
