### ISSUE TITLE
$bot->getBotMessages() not working

### ISSUE THREAD

**Issue by jabysa** [mpociot/botman#1221]
- BotMan Version: 2
- PHP Version: 7.4
- Messaging Service(s):
- Cache Driver: file

### Description:
Hi i need the last message id that send with bot
and i want to get last message bot in conversation
   $this->bot->getBotMessages(); 
when i print that on serialize
    $this->bot->reply($this->bot->getBotMessages());
to then get id with this way
   getPayload()['message_id']
return this 
    a:0:{}

i want this for reply to the last bot message

this is my code

    $this->say('hello');

        $text = "Hello world";

        $parameters = [
            'chat_id' => $this->bot->getBotMessages()[0]->getPayload()['chat']['id'],
            'reply_to_message_id' => $this->bot->getBotMessages()[0]->getPayload()['message_id'],
            'text' => $text
        ];
        $this->bot->sendRequest('sendMessage',$parameters);

### Steps To Reproduce:

**Comment by filippotoso** [comment]
`getBotMessages()` does not what you think it does (see https://github.com/botman/botman/blob/2.0/src/BotMan.php#L202).

To do what you want, you can use a sending middleware to save somewhere (cache, DB, filesystem, etc.) the latest message sent associated with the bot id and the user id. Than you can use those information to send you message.

https://botman.io/2.0/middleware#sending-middleware
