### ISSUE TITLE
title is required for this quick reply

### ISSUE THREAD

**Issue by drgnv** [mpociot/botman#1224]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
Hi guys! This is the code:

`

//botman
require '../vendor/autoload.php';
//include './model/Basic.php';
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Question;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Messages\Attachments\Image;
use BotMan\BotMan\Messages\Outgoing\OutgoingMessage;

$config = [
    'facebook' => [
  	'token' => 'EAAIclVPE1t8BAF9FEMLkVBgbf6DMAZCCjjVylCjXhcKZACLWiG7DRE1cHfCZAMbZBYp7oyuThg09m3wZBjOr1Fs9ZAbdYSArZClRZC1kGyKbxZAViM35d5hwUlmydqAQRxTbjupIZBP69v6H4jZCD29EyrxA2OkGSN93ufiRBBwpZAVzaovd2cUVQZD',
	'app_secret' => '048bfa53653b6fd90',
    'verification'=>'d',
]
];

// Load the driver(s) you want to use
DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

// Create an instance
$botman = BotManFactory::create($config);
$botman->say(Question::create('🚖Съобщение от шофьор '.$order[0]['driver_names'].': '.$data['note'].'⏱️ ПРИ СЛЕДВАЩАТА СИ ПОРЪЧКА МОЖЕТЕ ДА ИЗПОЛЗВАТЕ НЯКОЙ ОТ БЪРЗИТЕ НИ БУТОНИ ПОД ТОВА СЪОБЩЕНИЕ ↓')->addButtons([
         Button::create("$a1")->value("$a1"),
         Button::create("$a2")->value("$a2"),
Button::create("$a3")->value("$a3"),
Button::create("$a4")->value("$a4"),
Button::create("$a5")->value("$a5"),

         ]), $order[0]['facebookid'], \BotMan\Drivers\Facebook\FacebookDriver::class);
         
              `

this is the error:

    https://ibb.co/mt5GSZ8

It hapens some times. When the msg is send from iphone for example. 
### Steps To Reproduce:

**Comment by cykonetic** [comment]
Try $botman->ask(...) instead of $botman->say(...)
semantically one asks questions and says or replys statements
