### ISSUE TITLE
BotMan on clicking 1st Button does not ask questions and runs whole code.

### ISSUE THREAD

**Issue by UmerDaraz163** [mpociot/botman#1227]
- BotMan Version: 2.6
- PHP Version: 7.4.1
- Messaging Service(s): Web-Driver
- Cache Driver: Symfony Cache

### Description:
I'm using question buttons and then asking questions using ask method.
I have some nested if conditions based on answer and then some ask methos in if conditions.
**Problem** is when I click the **very first button**, it does not ask other questions/ ask methods and run all ask methods with 1st if condition.
I include the symfony cache driver and created a config array in this file along with config/botman/ .
The code is given below along with code file

### Steps

`    <?php
    namespace App\Http\Controllers;

    use App\Http\Controllers\Controller;
    use BotMan\BotMan\BotMan;
    use BotMan\BotMan\BotManFactory;
    use BotMan\BotMan\Cache\SymfonyCache;
    use BotMan\BotMan\Messages\Incoming\Answer;
    use BotMan\BotMan\Messages\Outgoing\Actions\Button;
    use BotMan\BotMan\Messages\Outgoing\Question;
    use Symfony\Component\Cache\Adapter\FilesystemAdapter;

    class ChatbotController extends Controller
    {

        public function handle()
        {
            $config = [
                'conversation_cache_time' => 40,

                'user_cache_time' => 30,
                'matchingData' => [
                    'driver' => 'web',
                ],
            ];

            $botman = app("botman");

            $adapter = new FilesystemAdapter();
            $botman = BotManFactory::create($config, new SymfonyCache($adapter));
            $botman->hears("{message}", function (BotMan $bot, $message) {
                $question = Question::create("Tell me, which type of product you are looking for?")
                    ->fallback("Unable to help at this time, please try again later")
                    ->callbackId("choose_query")
                    ->addButtons([
                        Button::create("Something electronic like a phone or TV")->value("Electronic"),
                        Button::create("A trip to my favorite destination")->value("trip"),
                        Button::create('Something else')->value('Something'),
                    ]);
                $bot->ask($question, function (Answer $answer, $botman) {
                    // Detect if button was clicked:
                    if ($answer->isInteractiveMessageReply()) {
                        if ($answer->getValue() == 'Electronic') {
                            $question = Question::create("Choose 1 from electronic?")
                                ->fallback("Unable to ask question")
                                ->callbackId("I can not understand this")
                                ->addButtons([
                                    Button::create('Phone')->value('Phone'),
                                    Button::create('TV')->value('TV'),
                                    Button::create('Something else')->value('something'),
                                ]);
                            $botman->ask($question, function (Answer $answer, $botman) {
                                if ($answer->isInteractiveMessageReply()) {
                                    $type = $answer->getText();
                                    $botman->reply('Ok, we are very good in finding the best deal for a' . $type . 'What brand is it that you are looking for');
                                    $botman->ask('{brand}', function (Answer $answer, $brand, $botman) {
                                        $brand = $answer->getText();
                                    });
                                }

                            });

                        } else if ($answer->getValue() == 'trip') {
                            $botman->say('Coming Soon');
                        } else if ($answer->getValue() == 'Something') {
                            $botman->say('Coming Soon');
                        }
                    } else {
                        $botman->say('No category was selected');

                    }
                });

            });

            $botman->listen();
        }

    }
`
[ChatbotController.txt](https://github.com/botman/botman/files/5566409/ChatbotController.txt)

**Comment by filippotoso** [comment]
Use conversation placing each each `ask()` in its own method. Then call the next question withing the callback of the previous `ask()`.

This is how it should be done.
