### ISSUE TITLE
How can I send attachment in webwidget provided by botman?

### ISSUE THREAD

**Issue by diosdado93** [mpociot/botman#1229]
- BotMan Version: 2.#.#
- PHP Version:7
- Messaging Service(s):
- Cache Driver:

### Description:
How can I send attachment in webwidget provided by botman? I'm very blocked , does anyone has a ready to use code? I can pay for that, cause it's for an important personal project.
thank you vey much

### Steps To Reproduce:

Use botman studio, create a bot and use webwidget

**Comment by Edd-G** [comment]
Hi!
This described in the Botman doc's
```
use BotMan\BotMan\Messages\Attachments\File;
use BotMan\BotMan\Messages\Outgoing\OutgoingMessage;

// Create attachment
$attachment = new File('http://file-url-here.pdf', [
    'custom_payload' => true,
]);

// Build message object
$message = OutgoingMessage::create('This is my text')
            ->withAttachment($attachment);

// Reply message object
$bot->reply($message);
```
