### ISSUE TITLE
Unable to install botman

### ISSUE THREAD

**Issue by venkataadithan** [mpociot/botman#1231]
- BotMan Version: #.#.#
- PHP Version: 7.3
- Messaging Service(s):
- Cache Driver:

### Description:

Problem 1
    - thecodingmachine/discovery is locked to version v1.2.1 and an update of this package was not requested.
    - thecodingmachine/discovery v1.2.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - thecodingmachine/discovery v1.2.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - botman/studio-addons 1.3.0 requires thecodingmachine/discovery ^1.2 -> satisfiable by thecodingmachine/discovery[v1.2.1].
    - botman/studio-addons is locked to version 1.3.0 and an update of this package was not requested.

### Steps To Reproduce:
 botman new weather-bot

**Comment by hendra1** [comment]
Try some alternative composer command

`composer create-project --prefer-dist botman/studio projectname`

it will clone and install all the dependency

**Comment by venkataadithan** [comment]
**Getting this error when trying with composer create-project command**

composer create-project --prefer-dist botman/studio myfirstbot
Creating a "botman/studio" project at "./myfirstbot"
Installing botman/studio (1.3.1)
  - Downloading botman/studio (1.3.1)
  - Downloading botman/studio (1.3.1)
  - Downloading botman/studio (1.3.1)
  - Installing botman/studio (1.3.1): Extracting archive
Created project in /home/admin1/Document/myfirstbot
> php -r "file_exists('.env') || copy('.env.example', '.env');"
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - thecodingmachine/discovery is locked to version v1.2.1 and an update of this package was not requested.
    - thecodingmachine/discovery v1.2.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - thecodingmachine/discovery v1.2.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - botman/studio-addons 1.3.0 requires thecodingmachine/discovery ^1.2 -> satisfiable by thecodingmachine/discovery[v1.2.1].
    - botman/studio-addons is locked to version 1.3.0 and an update of this package was not requested.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by GDAndres98** [comment]
Worked for me after I downgrade Composer 2 to Composer 11.0 #1213 

`composer self-update --1`

**Comment by venkataadithan** [comment]
@GDAndres98 this works, Thanks!!!

**Comment by sebaxakerhtc** [comment]
After many errors and attempts i wrote a simple step-by-step install guide
https://github.com/sebaxakerhtc/My-Ubuntu-Server/blob/master/botman_install.md
