### ISSUE TITLE
Request URL 404 error

### ISSUE THREAD

**Issue by rohit82drj** [mpociot/botman#1234]
- PHP Version: 7.4

- On click of widget 404 error get in network how to resolved it?
Request Method: GET
Status Code: 404 Not Found
Remote Address: [2a02:4780:8:243:0:2975:e8c4:1]:80
Referrer Policy: strict-origin-when-cross-origin

**Comment by sahilkashyap64** [comment]
Things i did to debug:
`composer dump-autoload`
`php artisan route:clear`
`php artisan route:list`

Look for botman url and http method.  

You can also try these

`php artisan cache:clear`
`php artisan config:clear`
`php artisan view:clear`
