### ISSUE TITLE
When manipulating DateTime (Carbon/Chronos) "Invalid serialization data for DateTime object"

### ISSUE THREAD

**Issue by haikajymada** [mpociot/botman#1240]
- BotMan Version: 2.0
- PHP Version: 7.4
- Messaging Service(s): Web
- Cache Driver: Web

### Description:
I got a 505 error after calling few ask() method when manipulating a complex date format. I used **Carbon** first and I tried **Chronos** of Cakephp after. With the 2 libraries, I have this error:

C:\laragon\www\botman-facebook\vendor\botman\botman\src\Traits\HandlesConversations.php
**"Invalid serialization data for DateTime object"**

Laravel Version : 6.0

### Steps To Reproduce:

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Invalid serialization data for DateTime object"

Stacktrace:
#45 Symfony\Component\Debug\Exception\FatalThrowableError in C:\laragon\www\botman-facebook\vendor\botman\botman\src\Traits\HandlesConversations.php:136
#44 unserialize in C:\laragon\www\botman-facebook\vendor\botman\botman\src\Traits\HandlesConversations.php:136
#43 BotMan\BotMan\BotMan:unserializeClosure in C:\laragon\www\botman-facebook\vendor\botman\botman\src\Traits\HandlesConversations.php:234
#42 BotMan\BotMan\BotMan:BotMan\BotMan\Traits\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Support\Traits\EnumeratesValues.php:176
#41 Illuminate\Support\Collection:each in C:\laragon\www\botman-facebook\vendor\botman\botman\src\Traits\HandlesConversations.php:248
#40 BotMan\BotMan\BotMan:loadActiveConversation in C:\laragon\www\botman-facebook\vendor\botman\botman\src\BotMan.php:422
#39 BotMan\BotMan\BotMan:listen in C:\laragon\www\botman-facebook\app\Http\Controllers\BotManController.php:21
#38 App\Http\Controllers\BotManController:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#37 Illuminate\Routing\Controller:callAction in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#36 Illuminate\Routing\ControllerDispatcher:dispatch in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Route.php:219
#35 Illuminate\Routing\Route:runController in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Route.php:176
#34 Illuminate\Routing\Route:run in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Router.php:681
#33 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:130
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#31 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:78
#29 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#28 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#27 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:56
#25 Illuminate\Session\Middleware\StartSession:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#24 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#23 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:67
#21 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#20 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:105
#19 Illuminate\Pipeline\Pipeline:then in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Router.php:683
#18 Illuminate\Routing\Router:runRouteWithinStack in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Router.php:658
#17 Illuminate\Routing\Router:runRoute in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Router.php:624
#16 Illuminate\Routing\Router:dispatchToRoute in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Routing\Router.php:613
#15 Illuminate\Routing\Router:dispatch in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:170
#14 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:130
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\fideloper\proxy\src\TrustProxies.php:57
#12 Fideloper\Proxy\TrustProxies:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:21
#10 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#9 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:21
#8 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#6 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:63
#4 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
#3 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:105
#2 Illuminate\Pipeline\Pipeline:then in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:145
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\laragon\www\botman-facebook\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:110
#0 Illuminate\Foundation\Http\Kernel:handle in C:\laragon\www\botman-facebook\public\index.php:55

**Comment by Asedol** [comment]
Same thing for me. Please help

**Comment by filippotoso** [comment]
Without the code is very difficult to help. If you still have this problem, reopen the issue including a minimal sample code that reproduces the error with the latest version of Botman.
