### ISSUE TITLE
Botman Studio Integration with FB Messenger Driver - Internal 500 Server Error

### ISSUE THREAD

**Issue by arch2603** [mpociot/botman#1241]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

I am using the Botman studio to connect to the Facebook Messenger, the webhook is connecting fine, status 200, however after while it produce an Internal Server 500 error. I am using the Laravel web server and ngrok to provide a VPN tunnel publicly.
[InternalServer500Error_GitHub_platform.pdf](https://github.com/botman/botman/files/5823392/InternalServer500Error_GitHub_platform.pdf)

### Steps To Reproduce:

**Comment by haikajymada** [comment]
Any details in the log laravel.log ?
