### ISSUE TITLE
AskForLocation cannot manage the Pinned Location response on Messenger

### ISSUE THREAD

**Issue by haikajymada** [mpociot/botman#1242]
- BotMan Version: 2.x
- PHP Version: 7.2
- Messaging Service(s): Facebook Messenger
- Cache Driver:

### Description:
I want to use AskForLocation on Messenger but I have an error caught in the log laravel.log

> Argument 1 passed to App\Conversations\DataConversation::{closure}() must be an instance of App\Conversations\Location, instance of BotMan\BotMan\Messages\Attachments\Location given {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Conversations\\DataConversation::{closure}() must be an instance of App\\Conversations\\Location, instance of BotMan\\BotMan\\Messages\\Attachments\\Location given at closure://function (\\App\\Conversations\\Location $location)

```
        DriverManager::loadDriver(FacebookLocationDriver::class);

        $this->askForLocation('Please tell me your location.', function (Location $location) {
            // $location is a Location object with the latitude / longitude.
            // Log::info($location);
            $this->askNextStep();
        }, function(Answer $answer) {
            // This method is called when no valid image was provided.
            $this->say('Localisation non valide');
            $this->askNextStep();
        });
```

It seems Botman 2.x does not support actual location response of Messenger version 2020 ? Because this following json is correctly received but the treatment failed after :
{
    "object": "page",
    "entry": [
        {
            "id": "141483359286937",
            "time": 1610946393837,
            "messaging": [
                {
                    "sender": {
                        "id": "1401780929904705"
                    },
                    "recipient": {
                        "id": "141483359286937"
                    },
                    "timestamp": 1610946272455,
                    "message": {
                        "mid": "m_mDtJL37pYuKfCH72tbpfs_VNgKbGS5fAbyY1ZX_ZhUkQzkXLP_Oea5vSMFcPzjmoxFhUU-8HAadvefP4RY4Drg",
                        "attachments": [
                            {
                                "type": "location",
                                "payload": {
                                    "coordinates": {
                                        "lat": -18.951177,
                                        "long": 47.55619
                                    },
                                    "url": "https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.bing.com%2Fmaps%2Fdefault.aspx%3Fv%3D2%26pc%3DFACEBK%26mid%3D8100%26where1%3D-18.951177%252C%2B47.55619%26FORM%3DFBKPL1%26mkt%3Dfr-FR&h=AT3CLGNu9IM0achRe0nzprGgfWD-uC0kmG1ZbigU1KdSeeltXs9FLfJ3zQV1YYEqx-Z50unEFcs62R39sZSVAf3wOQO612Z9JOs_RFkk6YpKossS2eP3Epd5Ox5RDjw9CarseG1McoZeBmw&s=1",
                                    "title": "Pinned Location"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

**Comment by filippotoso** [comment]
You forgot to import the Location class at the beginning of the file that contains the DataConversation class.

```php
use BotMan\BotMan\Messages\Attachments\Location;
```
