### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ahmedatef00** [mpociot/botman#1244]
- BotMan Version: 2.6
- PHP Version:7.3|8
- Messaging Service(s):facebook
- Cache Driver:

### Description:
 How can I send the [generic template] that represents some news  to all users using commands in Laravel 
 where can I add the user facebook id I have the users information in my database but I don't know how can I send it to the users using Command
 
 the Generic template itself working but the image is not displayed when I put the data static but as I said i just want to make it generic and how can I sent to the users 

### Steps To Reproduce:
![Screenshot from 2021-01-19 20-23-19](https://user-images.githubusercontent.com/25952030/105076802-3bcecb80-5a94-11eb-890e-1b7d297f4672.png)

![Screenshot from 2021-01-19 20-24-52](https://user-images.githubusercontent.com/25952030/105076946-70db1e00-5a94-11eb-8393-1376b3b7e3d5.png)

**Comment by ahmedatef00** [comment]
@christophrumpel  
@mpociot 
If you can help I will appreciate That

**Comment by nunomazer** [comment]
Hi @ahmedatef00 did you found a solution? Could you please post ir here?
