### ISSUE TITLE
Question: How Do I send cards to Cisco Webex Team Space?

### ISSUE THREAD

**Issue by venkytt** [mpociot/botman#1245]
Hello

Thanks for BotMan! It rrrocks! Wish you all several fantastic years ahead

Is it possible to send cards on a 1:1 chat on Webex Teams? What I would like to do is send a card, user clicks on a button, and the action is sent to the web hook and the bot then replies accordingly.

Is this possible?

Thanks

**Comment by filippotoso** [comment]
Check if there's an API you can use to interact with Webex Teams. Then write write a custom driver for it.
