### ISSUE TITLE
Class 'Twilio\TwiML' not found {"exception":"[object] (Error(code: 0): Class 'Twilio\\TwiML' not found

### ISSUE THREAD

**Issue by enterlight** [mpociot/botman#1247]
- BotMan Version: 2.6.1
- PHP Version: 7.4
- Messaging Service(s): Twilio
- Cache Driver: 

### Description:
crashes on $bot->reply() with the following error:

[2021-01-22 20:30:46] local.ERROR: Class 'Twilio\TwiML' not found {"exception":"[object] (Error(code: 0): Class 'Twilio\\TwiML' not found at /var/www/headmin/vendor/botman/driver-twilio/src/TwilioMessageDriver.php:130)
[stacktrace]
#0 /var/www/headmin/vendor/botman/botman/src/BotMan.php(655): BotMan\\Drivers\\Twilio\\TwilioMessageDriver->sendPayload(Array)
#1 [internal function]: BotMan\\BotMan\\BotMan->BotMan\\BotMan\\{closure}(Array)
#2 /var/www/headmin/vendor/mpociot/pipeline/src/Pipeline.php(114): call_user_func_array(Object(Closure), Array)
#3 [internal function]: Mpociot\\Pipeline\\Pipeline->Mpociot\\Pipeline\\{closure}(Array)
#4 /var/www/headmin/vendor/mpociot/pipeline/src/Pipeline.php(102): call_user_func_array(Object(Closure), Array)
#5 /var/www/headmin/vendor/botman/botman/src/Middleware/MiddlewareManager.php(126): Mpociot\\Pipeline\\Pipeline->then(Object(Closure))
#6 /var/www/headmin/vendor/botman/botman/src/BotMan.php(656): BotMan\\BotMan\\Middleware\\MiddlewareManager->applyMiddleware('sending', Array, Array, Object(Closure))
#7 /var/www/headmin/vendor/botman/botman/src/BotMan.php(642): BotMan\\BotMan\\BotMan->sendPayload(Array)
#8 /var/www/headmin/app/Http/Controllers/ChatbotController.php(60): BotMan\\BotMan\\BotMan->reply('I can't hear wh...')
#9 /var/www/headmin/vendor/botman/botman/src/BotMan.php(520): App\\Http\\Controllers\\ChatbotController->App\\Http\\Controllers\\{closure}(Object(BotMan\\BotMan\\BotMan))
#10 /var/www/headmin/vendor/botman/botman/src/BotMan.php(501): BotMan\\BotMan\\BotMan->callFallbackMessage()
#11 /var/www/headmin/vendor/botman/botman/src/BotMan.php(425): BotMan\\BotMan\\BotMan->callMatchingMessages()
#12 /var/www/headmin/app/Http/Controllers/ChatbotController.php(62): BotMan\\BotMan\\BotMan->listen()
#13 /var/www/headmin/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\ChatbotController->handleSMS()

### Steps To Reproduce:

**Comment by filippotoso** [comment]
It's a Twilio Driver issue: https://github.com/botman/driver-twilio/issues/10
