### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by Tsjippy** [mpociot/botman#1248]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I just have a question. Are there any plans to support Signal messenger?

### Steps To Reproduce:

**Comment by kovinet** [comment]
I would also like to make a bot for Signal. Would it be possible to write driver or are there any known obstacles?

**Comment by filippotoso** [comment]
At this time to focus is on Botman and a subset of the existing drivers.
