### ISSUE TITLE
Choose cache driver while creating botman with service container

### ISSUE THREAD

**Issue by rgr** [mpociot/botman#1253]
- BotMan Version: 2.6
- PHP Version: 7.4
- Cache Driver: LaravelCache

### Description:
Hi,

I would like to create the Botman app with the service container while specifying which cache option to use otherwise it's the array cache that is used. My question is how would you do that?

Thanks

### Steps To Reproduce:

```php
    public function talk()
    {
        $bot = app('botman');                                             // Works
        $bot = app('botman', [config('botman'), new LaravelCache()]);     // Does not work

        $bot->middleware->received(new BotReceived());

        $bot->middleware->sending(new BotSending());

        $bot->listen();
    }
```

**Comment by filippotoso** [comment]
Register your own singleton that accepts the required parameters:

https://github.com/botman/botman/blob/2.0/src/BotManServiceProvider.php#L33

The use `makeWith()` to pass the cache you want;

https://laravel.com/docs/9.x/container#the-make-method

Finally instance Botman using the new singleton.

Or simply don't use the service container and instance Botman directly.
