### ISSUE TITLE
Botman Route

### ISSUE THREAD

**Issue by arch2603** [mpociot/botman#1254]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

I was wondering Botman allows the definition of new routes that will hit the controller methods. In-addition, do Botman use routing when jumping between two different conversation pathway.

Is there a way I can obtain the flow diagram and some class diagram for the Botman app.
### Steps To Reproduce:

**Comment by brentkelly** [comment]
If using botman studio an incoming request comes in through Laravel as per normal which checks the routes defined in `routes/web.php`. By default there is a route bound which executes `BotManController@handle`.

This controller will check for conversation routes defined in `routes/botman.php` as per: https://botman.io/2.0/receiving & execute any where the incoming message matches the specified pattern.

**Comment by arch2603** [comment]
Thanks for clarifying, just to reiterate you cannot create the additional controllers, and would also be pointless.
