### ISSUE TITLE
Question: How reply to specific user

### ISSUE THREAD

**Issue by hussenk** [mpociot/botman#1255]
is there way to reply to specific user?
for example:

$botman->hears('order code #([0-9])', function ($bot, $name) {
    $user = $bot->getUser();
    $bot->reply('order saved');
});

   /*
       $user_id =$user->getId();
        //i get the user id  then i reply to them later
        say->to(user_id)->message('');
    */

**Comment by brentkelly** [comment]
@hussenk if you want to reply instantly but only to a certain user, then you can use a standard if statement around your `$bot->reply`

If you are wanting to send later, then you can store the recipient id (however you want - cache, db, whatever) and then use cron/queues or whatever mechanism you want to send an "originating message": https://botman.io/2.0/sending#originating-messages
