### ISSUE TITLE
I want to stop conversation, if my agent (human ) reply on the conversation? How could I do that?

### ISSUE THREAD

**Issue by sarwarcse** [mpociot/botman#1256]
- BotMan Version: 2.0
- PHP Version: 7.2.25
- Messaging Service(s):
- Cache Driver: symphone 

### Description:
I want to stop conversation, if my agent (human ) reply on the conversation? How could I do that?
Please advice me.

**Comment by cykonetic** [comment]
the stopsConversation() method will do that.
it is checked on the way back in.
You could set a protected var on your conversation ($this->isOver = true) then override the stopsConversation method to return that value
