### ISSUE TITLE
Botman Studio don't reply

### ISSUE THREAD

**Issue by hussenk** [mpociot/botman#1257]
- BotMan Version:  2
- PHP Version:7
- Messaging Service(s): 
- Cache Driver:

### Description:
I started a new project with Botman Studio

`composer create-project --prefer-dist botman/studio test`
then I do update

```
cd test
composer up
```
and then installed drivers : facebook and telegram .

```
composer require botman/driver-facebook
composer require botman/driver-telegram
```
done with installing

then I do

```
php artisan key:gen
php artisan serve
```
I go to localhost , it works fine. I say "hi" it replay "Hello!"

I edit .env file added token Facebook and Telegram

```
FACEBOOK_TOKEN=my_app_token
FACEBOOK_APP_SECRET=my_secret
FACEBOOK_VERIFICATION=my_verification
TELEGRAM_TOKEN='my_bo_ttoken'
```
I upload this project to my host

move `public `file to `public_html `edit index file

```
require __DIR__.'/test/vendor/autoload.php';
$app = require_once __DIR__.'/test/bootstrap/app.php';
```
the host works fine. I tested it Responded to all on web and telegram for every user . But in Facebook it Respond only to me like telegram and web `my_domain/botman/tinker` . when new user say "hi" , it not respond at all .

### Steps To Reproduce:

**Comment by anothermorena** [comment]
Did you find a solution to this problem? I am currently experiencing it too.

From the localhost, it works just fine but when I connect Facebook messenger it does not reply even though It shows on the ngrok logs that the request went through.

**Comment by brentkelly** [comment]
Have you checked your Laravel logs?

Here is a great guide on debugging: https://christoph-rumpel.com/2018/11/the-ultimate-botman-chatbot-debugging-guide

**Comment by adrian-schnell** [comment]
having the same issue. I don't receive a request on expose, but setup the bot in telegram and registered the expose url.

caused I dont get requests, my logs are empty

**Comment by sebaxakerhtc** [comment]
Very interesting...
My bot works with messenger and telegram one year, but from 24th June it stop work.
In Facebook developer panel now we have new interface for pages_messaging and we should have accepted account, but after all steps my bot still not work with messenger. Just Telegram work. I created issue on Facebook, but i don't trust them :)

**Comment by dr41d45** [comment]
Dear @sebaxakerhtc, how you solve it? I have the same quirk :(
> My bot works with messenger and telegram one year, but from 24th June it stop work.

**Comment by sebaxakerhtc** [comment]
> Dear @sebaxakerhtc, how you solve it? I have the same quirk :(
> 
> > My bot works with messenger and telegram one year, but from 24th June it stop work.

I recreate app key in FB Dev panel
