### ISSUE TITLE
Issue with CURL

### ISSUE THREAD

**Issue by borNfreee** [mpociot/botman#126]
Extracted from #97 

Because of this string, the Microsoft returns the bad response:

```php
curl_setopt($request, CURLOPT_SSL_VERIFYPEER, false);
```

If I set it to `true`, the correct `access_token` is returned.

Reproduced on PHP7. What would you suggest? Are you able to reproduce this issue? If so, how do you recommend to fix it?

**Comment by mpociot** [comment]
I was not able to reproduce this behavior, but it should be safe to set it to `true`.
And also this would be a lot safer, since it does not allow man-in-the-middle attacks.

I will change the code and test the various drivers.
