### ISSUE TITLE
Loading database data to build a Carousel (Facebook)

### ISSUE THREAD

**Issue by sherwinaval** [mpociot/botman#1265]
- BotMan Version: 2.0
- PHP Version: 7.4
- Messaging Service(s): Facebook
- Cache Driver:

### Description:
I want to load a Carousel which data is coming from a database. No errors are being raised, but no carousel is being loaded. Someone help please or point me to the right direction. Thank you.

### Steps To Reproduce:
$items = new Product();
$products = $items->GetProducts();
$i = 1;
$elements = array();
foreach ($products as $product) {
if ($i <= 10) {
    $newproduct[] = array(
        Element::create($product['name'].' ('.$product['price'].')')
            ->subtitle($product['subtitle'])
            ->image($product['img'])
            ->addButton(ElementButton::create('Order Now!')
            ->payload('add_order '.$product['id'])
            ->type('postback'))
    );    
    $elements = $newproduct;
    $bot->reply($elements);
    $i = $i+1;
}
else {
    $bot->reply(GenericTemplate::create()
        ->addImageAspectRatio(GenericTemplate::RATIO_SQUARE)
        ->addElements($elements));
    $i = 1;
    $elements = array();
}

**Comment by filippotoso** [comment]
Your code sends the reply up to 10 times, each time with an additional element in it (the `reply()` call is within the loop that populates the `$newproduct[]` arrray(). 

I suggest you to start sending a single element from static data and rewrite your code using a simple `$bot->reply($product['name'])` to see whats happening and fix your code accordingly.
