### ISSUE TITLE
BotMan Timeout

### ISSUE THREAD

**Issue by decadence** [mpociot/botman#1266]
- BotMan Version: 2.6.1
- PHP Version: 7.3.2
- Messaging Service(s): Skype, Telegram
- Cache Driver: none

### Description:
How do I set timeout for BotMan `say` method? I searched through documentation and source code but Curl.php has not any timeout options. By default cURL has very big timeout which is not applicable in the real app.

**Comment by decadence** [comment]
Temporary dirty fix is adding this line to `prepareRequest` method in file `vendor/botman/botman/src/Http/Curl.php`
```php
curl_setopt($request, CURLOPT_TIMEOUT_MS, 5000);
```

But ideally there should be way to pass it to BotMan methods.

**Comment by filippotoso** [comment]
It will be available in the next version. Just add the following option in your config file (for Botman and the drivers you are using) and it will work:

`'http_timeout' => 5000,`
