### ISSUE TITLE
Form in Slack Bot to Submit GitHub Issue 

### ISSUE THREAD

**Issue by bkuppala95** [mpociot/botman#1267]
- BotMan Version: #.#.#
- PHP Version: 7.2.34
- Messaging Service(s): Slack to Github
- Cache Driver:RTM

### Description: I have created a Slack app which can create GitHub issue using RTM driver. The app asks questions and the user has to enter one by one to create a GitHub issue.
But currently, I want to create a GitHub issue using the form or modal in the slack. The user needs to enter the form and submit instead of one-by-one answering. Is this possible to do via botman. What is the process to implement this type of behavior?

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Create a conversation with the questions you need answered: https://botman.io/2.0/conversations
Save the answer in the storage: https://botman.io/2.0/storing-information
At the end use your existing code to create the Github issue.
