### ISSUE TITLE
Start conversation without user input

### ISSUE THREAD

**Issue by gus-at-2122** [mpociot/botman#1268]
- BotMan Version: 2.6.1
- PHP Version:7.4
- Messaging Service(s):
- Cache Driver:

### Description:
I  would like to know how I can make botman initiate a conversation without prior user input. That is, when Botman loads that starts the conversation.
Thanks

### Steps To Reproduce:

**Comment by filippotoso** [comment]
You haven't specified the messaging service you want to use.
