### ISSUE TITLE
Middleware bypass

### ISSUE THREAD

**Issue by christophrumpel** [mpociot/botman#127]
I want to use a middleware bot, but not for every request. This is very helpful because API calls are expensive (time and request limits) and there are often messages that you do not need to send to the API because it is clear for you how to reply to them without AI.

E.g.

User: Hi!
Bot: Hello to you too!

It looks like there is no way now to do that without editing the middleware itself. A solution could be to provide "bypass" rules when you add the middleware.

```php
$bypassMessages = ['hi', 'hey', 'hello'];
$botman->middleware(ApiAiMiddleware::create('token'), $bypassMessages);
```

What do you think about that? Cheers

**Comment by mpociot** [comment]
Hey,

Isn't this what you're looking for?

https://github.com/mpociot/botman/commit/66d8da5b2192ad2ac145da2fc7ea6caadc93e2ff

This allows you to define per command middleware instead of only global middleware.

**Comment by christophrumpel** [comment]
Hey,

this is not exactly what I need. We already talked on Slack and some kind of route groups would be nice.
