### ISSUE TITLE
Not able to connect to telegram

### ISSUE THREAD

**Issue by AvneetSingh27** [mpociot/botman#1271]
I am a newbie to the Botman framework and am trying to connect to telegram for the first time. Please help me to solve this issue

 "php": "^7.1.3",
"botman/botman": "~2.0",
"botman/driver-telegram": "^1.6",

Hey, I am getting this error while running **php artisan botman:telegram:register** command
file_get_contents(https://api.telegram.org/bot/setWebhook?url=https://1bc20d0d08ce.ngrok.io/botman/tinker): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

But this works well:https://1bc20d0d08ce.ngrok.io/botman/tinker
at F:\Botman Chatbot\todobot\vendor\botman\driver-telegram\src\Console\Commands\TelegramRegisterCommand.php:44
40| $this->info('Using '.$url);
41|
42| $this->info('Pinging Telegram...');
43|

44| $output = json_decode(file_get_contents($url));
45|
46| if ($output->ok == true && $output->result == true) {
47| $this->info(
48| $remove

Exception trace:

1 file_get_contents()
F:\Botman Chatbot\todobot\vendor\botman\driver-telegram\src\Console\Commands\TelegramRegisterCommand.php:44

2 BotMan\Drivers\Telegram\Console\Commands\TelegramRegisterCommand::handle()
F:\Botman Chatbot\todobot\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29

Though I have set up the telegram auth token in the right manner.
But it's sending 404 Not found. Please help me in this context

**Comment by AvneetSingh27** [comment]
But if I send a post request using postman
https://api.telegram.org/botmytoken/setWebhook?url=https://1bc20d0d08ce.ngrok.io/botman/tinker

it works fine.

**Comment by Kenpachi080** [comment]
попробуй просто /botman. Tinker вроде как просто выводит бота тебе на изображение
