### ISSUE TITLE
Can't get working group method

### ISSUE THREAD

**Issue by sebaxakerhtc** [mpociot/botman#1272]
- BotMan Version: 2.0
- PHP Version: 7.4
- Messaging Service(s): Facebook, Telegram
- Cache Driver: TelegramDriver

### Description:

Can't get working group method.

### Steps To Reproduce:

As mentioned in [official documentation](https://botman.io/2.0/receiving),  i try:

```
$botman->group(['driver' => TelegramDriver::class], function($bot) {
    $bot->hears('keyword', function($bot) {
        $bot->reply('🤖: success.');
    });
});
```
But no answer from bot in messenger, telegram or web

**Comment by ale24** [comment]
**UPDATE:**
I checked Marcel videos and his workflow, and a lot of times in Botman videos he used some magic keys in Sublime Text editor, so I google it, and it was PHP Companion, so I installed Sublime Text and PHP Companion through Tools->Command Pallete, and clicked on VkCommunityCallbackDriver, and then again Tools->Command Pallete with command PHP Companion:Find Use, and this code appear:
```
use BotMan\Drivers\VK\VkCommunityCallbackDriver;
use BotMan\Drivers\Telegram\TelegramDriver;
```
the magic worked and now the group method with the driver works, I still don't understand why this is not indicated anywhere in the documentation or in video courses, as if the group method is not the main one.



same, only writing custom Middlewares helps to hear and detect platform

heres my for vk https://stackoverflow.com/questions/68939203/botman-studio-with-vk-community-callback-driver-hears-not-works-inside-group/68943904#68943904

telegram also does not work, so I think I'll have to somehow define its messages also through Middleware

Botman Studio php 7.4.22 with run through artisan and ngrok
