### ISSUE TITLE
One image not sending!

### ISSUE THREAD

**Issue by IljaPHP** [mpociot/botman#1277]
- BotMan Version: 2.6
- PHP Version: 7.4
- Messaging Service(s):
- Cache Driver: Symphony

### Description

This method can publish any image from yandex.ru that I find, any link, but not this: https://oir.mobi/uploads/posts/2019-12/1575344714_medved-grizli-4.jpg  
Why? What is wrong with it?
### Steps To Reproduce:

```
      // Create attachment
         $attachment = new Image('https://oir.mobi/uploads/posts/2019-12/1575344714_medved-grizli-4.jpg', [
         'custom_payload' => true,
      ]);

// Build message object
      $message = OutgoingMessage::create('This is my text')
         ->withAttachment($attachment);
      $this->bot->say($message, '-99999999999');
```

**Comment by filippotoso** [comment]
You haven't specified the messagin service nor the error message you got.
