### ISSUE TITLE
Dialogflow Knowledge

### ISSUE THREAD

**Issue by homemadestea58** [mpociot/botman#1282]
- BotMan Version: 2.0
- PHP Version: 7.3
- Messaging Service(s): Web
- Cache Driver: None

### Description:
I am having some trouble with getting the chatbot to read from the DialogFlow Knowledge base on my agent.

Any help would be appreciated.

**Comment by filippotoso** [comment]
If you have configured it correctly, you should be able to read the answer using a code like this:

```php
$bot->getMessage()->getExtras()["apiReply"]
```
