### ISSUE TITLE
Release missing for PR #1259 

### ISSUE THREAD

**Issue by riccardodallavia** [mpociot/botman#1286]
- BotMan Version: 2.6.1
- PHP Version: 8.0
- Messaging Service(s):
- Cache Driver:

### Description:
The latest release is not working with PHP 8.0+ for an issue described and resolved on pull request #1259 .
I've seen the given PR has been approved and merged but it has not been tagged.

Could you please release it? Or else all user messages with one or more named parameters cannot be handled.

Thank you!

**Comment by ajsheldon93** [comment]
Following up to @riccardodallavia post. Can this be tagged for release?

Thank you!
