### ISSUE TITLE
Successful telegram Webhook set, but no responding bot reply

### ISSUE THREAD

**Issue by royhg** [mpociot/botman#1287]
- BotMan Version: 2.6.1
- PHP Version: 7.3
- Messaging Service(s):
- Cache Driver:

### Description:
I already write script follow the instruction as link https://botman.io/2.0/installation without Botman Studio
I already set webhook to my telegram bot and set the url with json response:
{"ok":true,"result":true,"description":"Webhook was set"}
I already has response from GetWebhookInfo:
{"ok":true,"result":{"url":"https://mobi.1rhg.com/MobiBot.php ","has_custom_certificate":false,"pending_update_count":0,"max_connections":40,"ip_address":"111.68.113.28"}}
But when I run the script has following error:
Fatal error: Uncaught Error: Class 'Botman\Drivers\Telegram\TelegramDriver' not found in /home/kvpsshwb/public_html/mobi-1rhg-com/vendor/botman/botman/src/Drivers/DriverManager.php:173 Stack trace: #0 /home/kvpsshwb/public_html/mobi-1rhg-com/vendor/botman/botman/src/BotManFactory.php(68): BotMan\BotMan\Drivers\DriverManager->getMatchingDriver(Object(Symfony\Component\HttpFoundation\Request)) #1 /home/kvpsshwb/public_html/mobi-1rhg-com/MobiBot.php(34): BotMan\BotMan\BotManFactory::create(Array) #2 {main} thrown in /home/kvpsshwb/public_html/mobi-1rhg-com/vendor/botman/botman/src/Drivers/DriverManager.php on line 173
Error on line 173-> $driver = new $driver($request, $this->config, $this->http);

Which part that I missing here?
The Bot not responding to my text

**Comment by filippotoso** [comment]
Install the Botman Telegram driver: https://botman.io/2.0/driver-telegram

`composer require botman/driver-telegram`
