### ISSUE TITLE
BotMan + PostMan

### ISSUE THREAD

**Issue by sjollenbeck** [mpociot/botman#1289]
- BotMan Version: 2.6.1
- PHP Version: 8.0.10
- Messaging Service(s): WebDriver
- Cache Driver: SymfonyCache

### Description:

Hi,

My case is not really a problem, I need support to use BotMan together with PostMan. I want to simulate BotMan integration with some custom APIs. Can someone help me?

Thank you very much in advance. 

### Steps To Reproduce:

Postman, method POST, Body Json: {
    "driver": "web",
    "userId": "123",
    "message": "#sair",
    "attachment": null,
    "interactive": 0
}

Return BotMan:

Array
(
[0] => BotMan\Drivers\Web\WebDriver
)
The vaialble drivers are : 1

BotMan.php

use Symfony\Component\Cache\Adapter\FilesystemAdapter;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\BotMan\Cache\SymfonyCache;

DriverManager::loadDriver(\BotMan\Drivers\Web\WebDriver::class);

$config  = [
    'web' => [
    	'matchingData' => [
            'driver' => 'web',
        ],
    ]
];
$adapter = new FilesystemAdapter();
$botman  = BotManFactory::create($config, new SymfonyCache($adapter));

$botman->hears('#sair', function(BotMan $bot) {
    $bot->reply('Good by');
})->stopsConversation();

$botman->fallback(function($bot) {
    $bot->reply('Opção incorreta ...');
});

$botman->listen();

**Comment by haba-sensei** [comment]
bro i have same problem :S 
but... i can't recive any response for ask function 
![image](https://user-images.githubusercontent.com/72942765/145514591-2928ee67-09eb-4873-854b-4db4965924d6.png)

**Comment by sjollenbeck** [comment]
Hi,

Change json to form-data, is successfully... 

![Captura de Tela 2021-12-13 às 13 48 52](https://user-images.githubusercontent.com/4588206/145854487-7708603f-9b2a-403e-9d3f-db1338073e58.png)
