### ISSUE TITLE
have an implementation of telegram sponsored messages in mind ?

### ISSUE THREAD

**Issue by Antuan01** [mpociot/botman#1291]
following the docs [here](https://core.telegram.org/api/sponsored-messages) bots and channels that don't support sponsored messages will be disconnected on January 1 2022

i'm concerned about that news shutting down my project.

**Comment by filippotoso** [comment]
> **If their app allows its users to access content from Telegram channels**, third-party developers using the Telegram API are required to support and properly display official sponsored messages in their apps by January 1, 2022. Unfortunately, Telegram cannot financially sustain third-party apps that do not display sponsored messages and they will have to be disconnected.

Botman doesn't allow users to access content from Telegram channels. The disconnection doesn't apply.
