### ISSUE TITLE
How to send a video via telegram bot

### ISSUE THREAD

**Issue by Odilbukh** [mpociot/botman#1293]
BotMan Version: 2.0
PHP Version: 7.4
Messaging Service(s): Telegram
Cache Driver: Laravel

Description:
How to send video via telegram bot to user. Please help
I installed Telegram driver on to BotManStudio. It works good! But I can't send video to user via telegram bot

I tried this. But it does not work

```
$attachment = new Video($url);
    $message = OutgoingMessage::create()->withAttachment($attachment);

   $bot->reply($message);
```

### Steps To Reproduce:

**Comment by filippotoso** [comment]
What do you mean with "it does not work".

What the user receives on Telegram?
Which kind of error is shown/logged when you send the video?
Have you tried the documentation example as it's written?

```php
use BotMan\BotMan\Messages\Attachments\Video;
use BotMan\BotMan\Messages\Outgoing\OutgoingMessage;

// Create attachment
$attachment = new Video('http://video-url-here.mp4', [
    'custom_payload' => true,
]);

// Build message object
$message = OutgoingMessage::create('This is my text')
            ->withAttachment($attachment);

// Reply message object
$bot->reply($message);
```
