### ISSUE TITLE
Basic Usage without BotMan Studio and Stand alone

### ISSUE THREAD

**Issue by mintyPT** [mpociot/botman#1297]
So, on this page "https://botman.io/2.0/installation" on the section "Basic Usage without BotMan Studio" it's written "Make sure to place this code in a file that is accessible through the web - like a controller class."

So, I want to make a standalone bot running on slack. So, how do I launch botman this way?

**Comment by filippotoso** [comment]
Create a route that points to a controller method where you place the botman initializantion and listen code.

Take the url of the route and use it to configure you Slack application as per documentation.
