### ISSUE TITLE
Can't install with Laravel 9

### ISSUE THREAD

**Issue by decadence** [mpociot/botman#1299]
- BotMan Version: 2.6.1
- PHP Version: 8.0.8
- Messaging Service(s): Telegram, Skype

### Description:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - botman/botman[2.6.0, ..., 2.6.1] require symfony/http-foundation ^2.8 || ^3.0 || ^4.0 || ^5.0 -> found symfony/http-foundation[v2.8.0-BETA1, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires botman/botman ^2.6 -> satisfiable by botman/botman[2.6.0, 2.6.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require botman/botman:*" to figure out if any version is installable, or "composer require botman/botman:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Seems like we need symfony/http-foundation ^6.0 in composer.json.

### Steps To Reproduce:
- Install Laravel 9
- composer require botman/botman

**Comment by norellanac** [comment]
same issue, trying to update to Laravel 9

> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires botman/botman ^2.6.1 -> satisfiable by botman/botman[2.6.1].
    - botman/botman 2.6.1 requires symfony/http-foundation ^2.8 || ^3.0 || ^4.0 || ^5.0 -> found symfony/http-foundation[v2.8.0-BETA1, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but it conflicts with your root composer.json require (^6.0.3).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by LevChurakov** [comment]
As a workaround, you can use
`"symfony/http-foundation": "6.0.3 as 5.4.3"`
in your composer.json

**Comment by decadence** [comment]
@LevChurakov can you provide link for documentation of this "as" syntax? I can't find it.

I don't use symfony/http-foundation directly, it's Laravel dependency, so I can't change it.

**Comment by LevChurakov** [comment]
@decadence Sure: https://getcomposer.org/doc/articles/aliases.md Inline alias.
That's a tricky way, but i have no errors in my project now.

> I don't use symfony/http-foundation directly, it's Laravel dependency, so I can't change it.

You still can put this line to the `require` part of your composer.json

**Comment by decadence** [comment]
Thanks!

**Comment by abrshdir** [comment]
This didn't work for me. I uninstalled and installed composer, wamp server, and laravel again. It worked fine

> As a workaround, you can use `"symfony/http-foundation": "6.0.3 as 5.4.3"` in your composer.json

**Comment by FiruzShirinov** [comment]
Did anyone get the package working? I'm still getting the error:
Problem 1
    - botman/botman[2.6.0, ..., 2.6.1] require symfony/http-foundation ^2.8 || ^3.0 || ^4.0 || ^5.0 -> found symfony/http-foundation[v2.8.0-BETA1, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires botman/botman ^2.6 -> satisfiable by botman/botman[2.6.0, 2.6.1].

-W gives even more errors.
I've included `"symfony/http-foundation": "6.0.3 as 5.4.3"` to composer.json under require and that didn't do anything.

**Comment by bigperson** [comment]
I have some problem, after added `"symfony/http-foundation": "6.0.3 as 5.4.3"`:

```
Problem 1
    - botman/botman[2.6.0, ..., 2.6.1] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you l
ist it as an argument for the update command.
    - Root composer.json requires botman/botman ^2.6 -> satisfiable by botman/botman[2.6.0, 2.6.1].
```

**Comment by bigperson** [comment]
```
"psr/container": "2.0.2 as 1.1.2",
"symfony/http-foundation": "6.0.3 as 5.4.3"
```

worked for me

**Comment by filippotoso** [comment]
Try with version 2.6.2

**Comment by bigperson** [comment]
@filippotoso 
i have problem 
 Declaration of BotMan\BotMan\Container\LaravelContainer::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool

**Comment by filippotoso** [comment]
The latest version should be compatible:

https://github.com/botman/botman/blob/2.0/src/Container/LaravelContainer.php

**Comment by c-myers1** [comment]
@filippotoso : where is the 2.6.2 you refer to? Latest version I see in this rep is 2.6.1

**Comment by filippotoso** [comment]
Latest version is 2.7.1: https://github.com/botman/botman/tags

**Comment by c-myers1** [comment]
Sorry to ask a very basic question: to use this is by simply unzipping into the project folder, overwriting all the existing 2.6.1 stuff? Nothing else to be done right?

Also does a fresh botman installation pull in the 2.6.1 release then or the 2.7.1 tag?

**Comment by mfn** [comment]
The recommended way is definitely to use composer, with everything else you are on your own.

> Also does a fresh botman installation pull in the 2.6.1 release then or the 2.7.1 tag?

Using composer it will install the latest tagged release matching your dependencies (e.g. PHP version, other libs).

You might have a better understanding when you look at https://packagist.org/packages/botman/botman and see that the latest default release is v2.7.1 , what requirements it has, etc.

---
I agree though on one point: it would be really nice to have proper releases on github with changelogs.

**Comment by c-myers1** [comment]
Noted with thanks
