### ISSUE TITLE
Getting Started Issue - Argument 1 passed to Mpociot\SlackBot\SlackBot::__construct()

### ISSUE THREAD

**Issue by seivad** [mpociot/botman#13]
```Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mpociot\SlackBot\SlackBot::__construct() must be an instance of SuperClosure\Serializer```

Hey I've copied and pasted your starter code and I get the following area above when using:

```
 $slackBot = new SlackBot();
        $slackBot->initialize(env('SLACK_TOKEN'));
```

The documentation isn't very clear to me about how to interact with the bot from your tutorial or github page, I did get the url verified in Slack but when I write to the bot "hello" I get no response back due to the error above.

**Comment by mpociot** [comment]
Hello,

Are you using my package inside of a Laravel application?
If not, you need to add quite a few more dependencies to the constructor:

https://github.com/mpociot/slackbot/blob/master/src/Mpociot/SlackBot/SlackBotServiceProvider.php#L25

I still need to add a factory method to simplify this step, but need to add some generic cache interfaces. 
If you want to help me with a implementation for your framework, you are welcome.

**Comment by seivad** [comment]
yeah it is inside of a fresh 5.3 project, just can't even get this started - it's really odd with throwing this error, are you meant to new it up and then initialize? or are the docs out of date?

**Comment by mpociot** [comment]
No, the docs are just using the framework agnostic API.
If you use it within a Laravel app and you added the ServiceProvider + Alias, just replace all `$slackbot->` calls with the SlackBot facade.
You don't need to new it up or initialize it.

Just use: `SlackBot::hears` etc.

**Comment by seivad** [comment]
dude are you sure?

```
ErrorException in SlackBotController.php line 30:
Non-static method Mpociot\SlackBot\SlackBot::hears() should not be called statically
```

Have you tried just setting up a new project with your package and not using the package it was developed on? This is fresh 5.3, with a handle() function with:

```
public function handle(Request $request)
    {
        $payload = $request->json();

        if ($payload->get('type') === 'url_verification') {
            return $payload->get('challenge');
        }

        SlackBot::hears('hello', function (SlackBot $bot) {
            $bot->respond('hi');
        });
    }
```

**Comment by jerairrest** [comment]
Alternatively, if you like hinting you can you the following example after registering the SlackBotServiceProvider:

`
       /** @var \Mpociot\SlackBot\SlackBot $slackBot */
        $slackBot = app('slackbot');

        $slackBot->hears('ping', function (SlackBot $bot) {
            $bot->reply('PONG');
        });

        $this->bindPing($slackBot);

        $slackBot->listen();
`

Also add the following to your config/services.php to get around initializing your token every time.

`
    'slack' => [
        'bot_token' => env('SLACK_TOKEN')
    ]
`

**Comment by mnapoli** [comment]
> No, the docs are just using the framework agnostic API.

But the docs don't guide on how to set the project up, I faced the same issue.

**Comment by mpociot** [comment]
I'll gladly accept a PR for the documentation with a "getting started" guide :)
