### ISSUE TITLE
Full conversation truncated in web widget when typing on mobile phone

### ISSUE THREAD

**Issue by c-myers1** [mpociot/botman#1301]
- BotMan Version: 2.6.1
- PHP Version: 7.3
- Messaging Service(s): n/a
- Cache Driver: redis

### Description:

When chatting with the bot using web widget, the last few lines of the conversation cannot be seen when the mobile keyboard appears. I'm experiencing this on various Android phones.

![image](https://user-images.githubusercontent.com/42839510/154274959-d011080c-4f9e-4149-b3e6-96ab82356203.png)

I suspect it's a CSS problem and not sue exactly where in the CSS to zero in. Also if its the JS, its in minified form.

Reducing the mobile height doesn't resolve it. It simply makes the chat area smaller but still the last lines cannot be viewed.

### Steps To Reproduce:

Install and configure the web widget/ driver as directed at botman.io. Then chat via a mobile (android at least) phone.

**Comment by c-myers1** [comment]
Bump! Is there any resolution to this?

**Comment by filippotoso** [comment]
Not yet.

**Comment by smsalert-mobi** [comment]
@c-myers1 What you can do in chat.html iframe after chat.js you can add this:

            window.addEventListener('load',
                function () {
                    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
                        document.getElementById("botmanChatRoot").getElementsByClassName("chat")[0].style.height= window.innerHeight - 57 + 'px';
                    }
                }
            );

**Comment by c-myers1** [comment]
@smsalert-mobi : below excerpt is what the chat.html iframe looks like after the change but it has made no difference.

@filippotoso : if you tested and it works for you, please do share details.

      <body>         
        <script id="botmanWidget" src='  https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/chat.js'>
            window.addEventListener('load',
                function () {
                    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
                        document.getElementById("botmanChatRoot").getElementsByClassName("chat")[0].style.height= window.innerHeight - 57 + 'px';
                    }
                }
            );
        </script>     
      </body>
