### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by afiqiqmal** [mpociot/botman#1303]

**Comment by brentkelly** [comment]
It still flinches when you kick it.

I'd say it's lacking active maintainers as opposed to completely dead.

**Comment by alies-dev** [comment]
@filippotoso

If I invest my time to update this repo to work with latest PHP and Laravel version, what is the chance that it will be approved and merged?

**Comment by filippotoso** [comment]
I have been added as maintainer today. In the next days/weeks I'll try to merge the most useful PR and solve the critical issue. 

I just pushed a new version with Laravel 9 support.

If you send PRs that pass the tests, I'll merge them as soon as I can check them.

Thanks.
