### ISSUE TITLE
$bot->userStorage()->delete() doesn't work!

### ISSUE THREAD

**Issue by c-myers1** [mpociot/botman#1304]
- BotMan Version: Latest
- PHP Version: 7.3
- Messaging Service(s): Telegram
- Cache Driver: Redis

### Description:

Storage deletion doesn't work. With this code:

    $botman->hears('show-delete', function($bot) {
	    $stuff = $bot->userStorage()->all();
	    $bot->reply(serialize($stuff)); // first dump
	    $bot->userStorage()->delete();
	    $stuff = $bot->userStorage()->all();
	    $bot->reply(serialize($stuff)); // shows exactly same stuff as first dump
    }); 

I expect the second reply statement should be an empty object but its exactly the same as the first, i.e. the delete method is actually not doing anything. Meanwhile, [this](https://github.com/botman/botman/issues/473) confirms it should work. Is it a bug?

### Steps To Reproduce:

Just run the code above.

**Comment by filippotoso** [comment]
I tried the following code with the latest version of Botman and web driver:

```php
        $botman->hears('show-delete', function ($bot) {
            $bot->userStorage()->save([
                'name' => 'test'
            ]);
            $stuff = $bot->userStorage()->all();
            $bot->reply(serialize($stuff));
            $bot->userStorage()->delete();
            $stuff = $bot->userStorage()->all();
            $bot->reply(serialize($stuff));
        });
```

And obtained the following result:

```
a:1:{i:0;O:29:"Illuminate\Support\Collection":2:{s:8:"*items";a:1:{s:4:"name";s:4:"test";}s:28:"*escapeWhenCastingToString";b:0;}}

a:0:{}
```

It seems to work correctly.

**Comment by c-myers1** [comment]
I’m using the Telegram driver actually. If not too much to ask, can you simulate that too?

**Comment by filippotoso** [comment]
Just tested with the Telegram driver and it works correctly as well.

**Comment by c-myers1** [comment]
I’m yet to understand why. The only difference with your code I see are:

1) the config object I pass to the Botman factory includes a Redis cache
2) I call the save function within conversations and delete back in the main thread.

will keep experimenting.
