### ISSUE TITLE
Random error happening : ErrorException: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by PaGury** [mpociot/botman#1305]
- BotMan Version: 2.6.1
- PHP Version: 7.4.23
- Messaging Service(s): custom
- Cache Driver: redis

### Description:
We have botman in production since a couple of months.
On a period of 2 weeks, we have a total amount of 140K requests hitting a Laravel Controller calling the `listen()` function of botman. And a total of 2K errors for this 140K calls.

The 2K errors are all the same : 
```ErrorException: Trying to access array offset on value of type null```

Here is the stack trace : 
```error
ErrorException: Trying to access array offset on value of type null
#0 /app/vendor/botman/botman/src/Traits/HandlesConversations.php(110): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to acces...', '/app/vendor/bot...', 110, Array)
#1 /app/vendor/botman/botman/src/Traits/HandlesConversations.php(289): BotMan\BotMan\BotMan->removeStoredConversation()
#2 /app/vendor/botman/botman/src/Traits/HandlesConversations.php(241): BotMan\BotMan\BotMan->callConversation(Object(Opis\Closure\SerializableClosure), Array, Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): BotMan\BotMan\BotMan->BotMan\BotMan\Traits\{closure}(Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), 0)
#4 /app/vendor/botman/botman/src/Traits/HandlesConversations.php(248): Illuminate\Support\Collection->each(Object(Closure))
#5 /app/vendor/botman/botman/src/BotMan.php(422): BotMan\BotMan\BotMan->loadActiveConversation()
#6 /app/app/Http/Controllers/BotManController.php(123): BotMan\BotMan\BotMan->listen()
#7 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\BotManController->handle()
#8 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('handle', Array)
#9 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\BotManController), 'handle')
...
```

I digged a little in the code, and the error happens here : https://github.com/botman/botman/blob/master/src/Traits/HandlesConversations.php#L110
```
        if ($this->getStoredConversation($message)['time'] == $this->currentConversationData['time']) {
            $this->cache->pull($this->message->getConversationIdentifier());
            $this->cache->pull($this->message->getOriginatedConversationIdentifier());
        }
```

The `$this->getStoredConversation($message)` call returns null and it cause a crash.

I don't understand how the conversation could not be longer available in the cache if it's available in the previous calls in the stack ? (I.E in the `loadActiveConversation()` call).

We could fix it by checking if the conversation still exists before trying to delete it. But in fact I think there is a deeper problem that would make the cached conversations disappear.

Thanks for helping me ! 

### Steps To Reproduce:
I'm not able to reproduce it, it's really random, I would like to discuss about the probable causes.

**Comment by filippotoso** [comment]
I added the workaround in version 2.7.5.
It also happens randomly in some of my bots.
Still unable to reliably replicate the problem to find a solution.
