### ISSUE TITLE
Configuration for Microsoft Teams Bot

### ISSUE THREAD

**Issue by razvan-deskare** [mpociot/botman#1310]
- BotMan Version: 2.6.1
- PHP Version: 8.1.2

Hello,
I'm trying to implement a Microsoft Teams bot for my existing Laravel application (I don't use Botman Studio).
My web.php looks like this:
```
Route::post('/botman', function () {  
    Log::info('botman');  
    $config = [  
        'botframework' => [  
            'app_id' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  
            'app_key' => '',  
        ]  
    ];  
    DriverManager::loadDriver(\BotMan\Drivers\BotFramework\BotFrameworkDriver::class);  
    $botman = BotManFactory::create($config);  
    $botman->listen();  
});
```
On the bot side, the endpoint is correctly configured (I manage to get the 'botman' log).
However, I am pretty sure that I don't successfully create the Botman instance.
My questions are:

1. Am I doing thing rightly at first sight?
2. I guess that YOUR-MICROSOFT-APP-ID is simply the app ID of my bot. But what is exactly the YOUR-MICROSOFT-APP-KEY? Where can I find it (for the moment, I leaved it blank)?
3. On version 1.5, it seems that another configuration field,  is required:
```
'botman' => [
    'microsoft_bot_handle' => 'YOUR-MICROSOFT-BOT-HANDLE',
    'microsoft_app_id' => 'YOUR-MICROSOFT-APP-ID',
    'microsoft_app_key' => 'YOUR-MICROSOFT-APP-KEY',
]
```
Can you confirm that only YOUR-MICROSOFT-APP-ID and YOUR-MICROSOFT-APP-KEY are mandatory for the version of Botman I am using (2.6.1)?

Thank you.

**Comment by filippotoso** [comment]
Have you registered a developer account with the [Bot Framework Developer Portal](https://dev.botframework.com/) and created the app there to obtain the APP ID and APP KEY?
