### ISSUE TITLE
[Spring cleaning] Closing issues older than 2 years

### ISSUE THREAD

**Issue by filippotoso** [mpociot/botman#1311]
Hi everybody!

I'm going to close all the issues more than 2 years old.

If you still have a problem, please open a new issue including all the details required.

Thanks for using Botman!

**Comment by xurizaemon** [comment]
Hi there! https://github.com/botman/botman/issues/1263 was closed without comment, is one year old by my reckon, and might snag you $50/mo if the available funding is true.

**Comment by filippotoso** [comment]
I closed the issues more than 2 years old without checking them.

I closed many issues more recent than 2 years old after checking them. The one remaining are the one that I'll work on in the next few weeks.

I closed your because the  I'm not interested. If other active maitainers are interested in that service, they can subscribe and access the funds.

**Comment by chimit** [comment]
@filippotoso are you going to be the new main maintainer of this package? If so I'm glad to see it's not abandoned anymore.
