### ISSUE TITLE
Web-Driver issue with http-Foundation Version 6

### ISSUE THREAD

**Issue by MaGiCmAsTeR0511** [mpociot/botman#1312]
- BotMan Version: 2.6.2
- PHP Version: 8.1.5
- Messaging Service(s): Web-Driver 1.5.1
- Cache Driver:

### Description:
I run in following Error und the Web-driver implementation in Botman:

_{name: "Exception",…}
code: 0
file: "C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\driver-web\\src\\WebDriver.php"
line: 192
message: "Call to undefined method Symfony\\Component\\HttpFoundation\\Response::create()"
name: "Exception"
stack-trace: [,…]
0: "#0 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\BotMan.php(438): BotMan\\Drivers\\Web\\WebDriver->messagesHandled()"
1: "#1 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\modules\\chatbot\\controllers\\ChatbotrestController.php(52): BotMan\\BotMan\\BotMan->listen()"
2: "#2 [internal function]: mip\\modules\\chatbot\\controllers\\ChatbotrestController->actionHearbot()"
3: "#3 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)"
4: "#4 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)"
5: "#5 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('hearbot', Array)"
6: "#6 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('chatbot/chatbot...', Array)"
7: "#7 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(common\\models\\core\\ModifiedRequest))"
8: "#8 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\web\\index.php(42): yii\\base\\Application->run()"
9: "#9 {main}"
type: "Error"_

The Problem is that the Dependecies from Botman especially the symfony/http-foundation in Version 6.0 isn't working because the create function of the Response class doesn't exist there anymore, when i downgrade from the Version from 6 to ^5 then everything is working

### Steps To Reproduce:
can't reproduce this

**Comment by filippotoso** [comment]
Try with version 1.5.2 of the web driver.

**Comment by MaGiCmAsTeR0511** [comment]
I will try it in the afternoon.

**Comment by MaGiCmAsTeR0511** [comment]
this doesn't work because then i get another Error in symfony/http-foundation ParameterBag.php

**Comment by filippotoso** [comment]
> this doesn't work because then i get another Error in symfony/http-foundation ParameterBag.php

Please post the detailed error message.

**Comment by MaGiCmAsTeR0511** [comment]
{name: "PHP Fatal Error",…}
code: 1
file: "C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\ParameterBag.php"
line: 19
message: "During inheritance of IteratorAggregate: Uncaught yii\\base\\ErrorException: Return type of Symfony\\Component\\HttpFoundation\\ParameterBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\ParameterBag.php:220\nStack trace:\n#0 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\ParameterBag.php(19): yii\\base\\ErrorHandler->handleError(8192, 'Return type of ...', 'C:\\\\Users\\\\N56983...', 220)\n#1 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\composer\\ClassLoader.php(480): include('C:\\\\Users\\\\N56983...')\n#2 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\composer\\ClassLoader.php(346): Composer\\Autoload\\includeFile('C:\\\\Users\\\\N56983...')\n#3 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\Request.php(273): Composer\\Autoload\\ClassLoader->loadClass('Symfony\\\\Compone...')\n#4 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\Request.php(255): Symfony\\Component\\HttpFoundation\\Request->initialize(Array, Array, Array, Array, Array, Array, NULL)\n#5 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\Request.php(2095): Symfony\\Component\\HttpFoundation\\Request->__construct(Array, Array, Array, Array, Array, Array, NULL)\n#6 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\symfony\\http-foundation\\Request.php(314): Symfony\\Component\\HttpFoundation\\Request::createRequestFromFactory(Array, Array, Array, Array, Array, Array)\n#7 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\BotManFactory.php(61): Symfony\\Component\\HttpFoundation\\Request::createFromGlobals()\n#8 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\modules\\chatbot\\controllers\\ChatbotrestController.php(29): BotMan\\BotMan\\BotManFactory::create(Array)\n#9 [internal function]: mip\\modules\\chatbot\\controllers\\ChatbotrestController->actionHearbot()\n#10 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#11 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#12 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('hearbot', Array)\n#13 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('chatbot/chatbot...', Array)\n#14 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(common\\models\\core\\ModifiedRequest))\n#15 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\web\\index.php(42): yii\\base\\Application->run()\n#16 {main}"
name: "PHP Fatal Error"
stack-trace: ["#0 [internal function]: yii\base\ErrorHandler->handleFatalError()", "#1 {main}"]
0: "#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()"
1: "#1 {main}"
type: "yii\\base\\ErrorException"

sry i forgot this is ehte erro Message 
i neede to use the botman dev-master to use the web-driver 1.5.2

**Comment by filippotoso** [comment]
Please check the composer.lock to see which version of symfony/http-foundation you are using.

**Comment by MaGiCmAsTeR0511** [comment]
i was using Version 6 but now i downgradin to 5.4.8 now it seems to be working but now i get this Warning Message

name: "PHP Deprecated Warning",…}
code: 8192
file: "C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\opis\\closure\\src\\SerializableClosure.php"
line: 18
message: "Opis\\Closure\\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)"
name: "PHP Deprecated Warning"
stack-trace: [,…]
0: "#0 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\opis\\closure\\src\\SerializableClosure.php(18): yii\\base\\ErrorHandler->handleError(8192, 'Opis\\\\Closure\\\\Se...', 'C:\\\\Users\\\\N56983...', 18)"
1: "#1 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\composer\\ClassLoader.php(480): include('C:\\\\Users\\\\N56983...')"
2: "#2 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\composer\\ClassLoader.php(346): Composer\\Autoload\\includeFile('C:\\\\Users\\\\N56983...')"
3: "#3 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\Traits\\HandlesConversations.php(123): Composer\\Autoload\\ClassLoader->loadClass('Opis\\\\Closure\\\\Se...')"
4: "#4 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\Traits\\HandlesConversations.php(156): BotMan\\BotMan\\BotMan->serializeClosure(Object(Closure))"
5: "#5 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\Traits\\HandlesConversations.php(45): BotMan\\BotMan\\BotMan->prepareCallbacks(Object(Closure))"
6: "#6 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\Messages\\Conversations\\Conversation.php(67): BotMan\\BotMan\\BotMan->storeConversation(Object(mip\\modules\\chatbot\\conversations\\Onboardingconversation), Object(Closure), 'Hello! What is ...', Array)"
7: "#7 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\modules\\chatbot\\conversations\\Onboardingconversation.php(25): BotMan\\BotMan\\Messages\\Conversations\\Conversation->ask('Hello! What is ...', Object(Closure))"
8: "#8 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\modules\\chatbot\\conversations\\Onboardingconversation.php(41): mip\\modules\\chatbot\\conversations\\Onboardingconversation->askFirstname()"
9: "#9 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\Traits\\HandlesConversations.php(28): mip\\modules\\chatbot\\conversations\\Onboardingconversation->run()"
10: "#10 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\modules\\chatbot\\controllers\\ChatbotrestController.php(32): BotMan\\BotMan\\BotMan->startConversation(Object(mip\\modules\\chatbot\\conversations\\Onboardingconversation))"
11: "#11 [internal function]: mip\\modules\\chatbot\\controllers\\ChatbotrestController->mip\\modules\\chatbot\\controllers\\{closure}(Object(BotMan\\BotMan\\BotMan))"
12: "#12 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\BotMan.php(507): call_user_func_array(Object(Closure), Array)"
13: "#13 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\botman\\botman\\src\\BotMan.php(430): BotMan\\BotMan\\BotMan->callMatchingMessages()"
14: "#14 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\modules\\chatbot\\controllers\\ChatbotrestController.php(52): BotMan\\BotMan\\BotMan->listen()"
15: "#15 [internal function]: mip\\modules\\chatbot\\controllers\\ChatbotrestController->actionHearbot()"
16: "#16 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)"
17: "#17 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)"
18: "#18 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('hearbot', Array)"
19: "#19 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('chatbot/chatbot...', Array)"
20: "#20 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(common\\models\\core\\ModifiedRequest))"
21: "#21 C:\\Users\\N56983\\Documents\\Entwicklung\\yii_git\\yii\\mip\\web\\index.php(42): yii\\base\\Application->run()"
22: "#22 {main}"
type: "yii\\base\\ErrorException"

**Comment by filippotoso** [comment]
It's a warning about Opis\Closure. It doesn't depend on Botman.
