### ISSUE TITLE
BC Break in last patch version

### ISSUE THREAD

**Issue by jderusse** [mpociot/botman#1313]
- BotMan Version: 2.6.3
- PHP Version: n/a
- Messaging Service(s): slack
- Cache Driver: n/a

### Description:

In https://github.com/botman/botman/commit/421333042fb38282ff1679922a54221ee9e0426e a new `typesAndWaits` method has been added to the `DriverInterface` interface.

This is a BC break which make https://github.com/botman/driver-slack falling with the following error
> BotMan\Drivers\Slack\SlackRTMDriver contains 1 abstract method and must
> therefore be declared abstract or implement the remaining methods
> (BotMan\BotMan\Interfaces\DriverInterface::typesAndWaits) in
> /app/vendor/botman/driver-slack/src/SlackRTMDriver.php on line 24

### Steps To Reproduce:

`composer require botman/botman botman/driver-slack`

**Comment by filippotoso** [comment]
Try with version 2.2.1 of the Slack Driver

**Comment by jderusse** [comment]
Thank you for the quick reply. It works for `driver-slack`.

But I believe the same issue occurs for all implementation of `DriverInterface` (that could exist in 3rd party packages.)

**Comment by filippotoso** [comment]
The problem exists only on non HTTP drivers. I'll check all the packages that implements DriverInterface and submit PRs if needed in the next few days.
