### ISSUE TITLE
WebDriver addButton additionalParameter url not opening new window

### ISSUE THREAD

**Issue by rajm** [mpociot/botman#1316]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
iam using web driver, need to send button with link, when clicked on the button it should open up the new window. i tried addButton additionalParameters url option but it is not working.

please help!

### Steps To Reproduce:

$question = Question::create('click on the button below 👇')
    ->addButtons([
        Button::create('link to Guide')
		->value('guide')
		->additionalParameters(['url' => 'https://xyz.net']),
    ]); 

$bot->reply($question);

**Comment by rajm** [comment]
no help here???

**Comment by filippotoso** [comment]
As far as I can understand, it's not a feature you get out of the box.

If you need it, you have to fork the web widget and add it here:

https://github.com/botman/web-widget/blob/master/src/chat/messages/action.tsx
