### ISSUE TITLE
receivesImages method gets value of "1" instead of an array of images 

### ISSUE THREAD

**Issue by c-myers1** [mpociot/botman#1317]
-BotMan Version: Latest
-PHP Version: 7.3
-Messaging Service(s): Telegram
-Cache Driver: Redis

### Description:

Using pure PHP, not Laravel, I'm trying to respond to images sent to the bot (not in a conversation, simply hearing an image attachment).

I initially had the problem of the bot ignoring messages but stumbled on [this](https://github.com/botman/botman/issues/1168) which solved the problem (i.e. loading the necessary Telegram drivers first).

Thereafter I found the closure is being invoked but the image array is NOT received. Testing with code below:

    $botman->receivesImages(function($bot, $images) {
	    $qty = sizeof($images);
	    $details = print_r($images);
	    $bot->reply("received $qty images => $details");
    });

I get the following reply in the Telegram chat:

    received 1 images => 1

This piece of code is between 2 $botman->hears statements which are working perfectly. Also, conversation and other simple "hears" closures work perfectly. 

What else can I do to pinpoint the problem?

Does botman store received images anywhere on the server and if so where can I check it really gets the image at all?

**Comment by filippotoso** [comment]
Please read carefully the documentation for https://www.php.net/print_r , especially about the second parameter and the return value of the function.
