### ISSUE TITLE
Hears with Command Parameter not Recognized

### ISSUE THREAD

**Issue by c-myers1** [mpociot/botman#1318]
- BotMan Version: Latest
- PHP Version: 7.3
- Messaging Service(s): Telegram
- Cache Driver: Redis

### Description:

I have a command paramter hears statement like this:

    $botman->hears('makeqr {param}', function ($bot, $param) {
       $bot->reply("Hey, I got into the closure!");

       // perform actions
    });

Along with other single word hears statements as well as a fallback for unrecognized commands.

However whenever I try to use this command e.g.

    makeqr testing

It simply invokes the fallback. All other single-word commands and conversations work.

How can I troubleshoot?

### Steps To Reproduce:

**Comment by filippotoso** [comment]
This code works as expected:

```php
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);

$config = array_merge(
    config('botman.config'),
    [
        'telegram' => config('botman.telegram', [])
    ]
);

$botman = BotManFactory::create($config);

$botman->hears('makeqr {param}', function ($bot, $param) {
    $bot->reply("You sent " . $param);
});

$botman->listen();
```

**Comment by c-myers1** [comment]
The only difference I have with your code is this part:

    $config = [
	"telegram" => [
		"token" => "<auth-string-here>"
	 ]
    ];

Is that the cause?
