### ISSUE TITLE
Buttons on multiple rows

### ISSUE THREAD

**Issue by Kaos1337** [mpociot/botman#132]
Hello,
I'm using your library for Telegram and Facebook Messenger.
I'm having a little problem with Telegram inline buttons, if there are multiple buttons (ex. 4) they are all compressed in a single row, this implicates that the button text is cut and unreadable.
This image represents the result that I'm trying to achieve: https://core.telegram.org/file/811140659/1/RRJyulbtLBY/ea6163411c7eb4f4dc
This is what I'm obtaining: https://core.telegram.org/file/811140217/1/NkRCCLeQZVc/17a804837802700ea4
How can I force one button per row?
Thank you.

**Comment by mpociot** [comment]
Hm..do you know about the native Telegram API which you would use to create this kind of multi-row buttons?

**Comment by Kaos1337** [comment]
It should depends on the multiarray input.
In nodejs (this code is in use in another bot of mine) I use this multiarray dimension to obtain one button per line:

```
var opts = {
     reply_markup: JSON.stringify({
           inline_keyboard: [
                   [{ text: 'Text 1', callback_data: 'text1' }],
                   [{ text: 'Text 2', callback_data: 'text2' }],
                   [{ text: 'Text 3', callback_data: 'text3' }]
           ]
     })
};
```

Actually with you library I'm doing this:

```
->addButtons([
        Button::create('Text 1')->value('text1'),
        Button::create('Text 2')->value('text2'),
        Button::create('Text 3')->value('text3'),
]);
```

**Comment by mpociot** [comment]
I see. I think we should switch to this layout as the default, as it makes more sense for buttons.

**Comment by mpociot** [comment]
Fixed
