### ISSUE TITLE
Example of Response object from sending low level sendRequest

### ISSUE THREAD

**Issue by c-myers1** [mpociot/botman#1320]
- BotMan Version: latest
- PHP Version: 7.3
- Messaging Service(s): Telegram
- Cache Driver: Redis

### Description:
On the website and tests folder on GitHub, I don’t find any examples of how to access and use the Response object. Can you point me to this and also how does the response object relate to  $bot->getMessage()->getPayload()?

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Here is the Response class source code:

https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/HttpFoundation/Response.php

There you can see all the methods available.

> Can you point me to this and also how does the response object relate to $bot->getMessage()->getPayload()?

They don't relate directly. The structure of the message payload depends on the driver you are using. Response is a lower level object that represents the HTTP response of a request.

**Comment by c-myers1** [comment]
Ok its just the standard http response in a symphony class.

It's still not clear to me how to intercept it in the code though.

**Comment by filippotoso** [comment]
Please state you use case . 
I developed tens of bots and never used Response.

**Comment by c-myers1** [comment]
Maybe I don't have the full understanding but as the sendRequest documentation says "it is not possible to have all API methods for each messaging service in the core of BotMan", I don't know how to generally capture responses after using sendRequest especially within conversations. 

Would it always be available in $answer->getText()?
If so, what if the response to the sendRequest is an image? How would that be decoded?

**Comment by filippotoso** [comment]
Why are you using sendRequest()?

You don't need it for 99.9% of the use cases.

Just read the documentation and use say(), replay(), ask() and so on.

**Comment by c-myers1** [comment]
I want the native look of Telegram button etc. But for instance, if I use ->addButtons, It presents each button in a different line and doesn't look native. With sendRequest I can have multiple buttons on same line and looks native.

Maybe I missed how to achieve all this in the docs and would appreciate your pointer. And yes I'm aware botman is primarily to enable creation of multi-messenger bots but I would still like to get as native as possible with Telegram.

**Comment by filippotoso** [comment]
Please post a sample code with addButtons() and one with sendRequest() where you try to achieve the same results but obtain different buttons layouts.

**Comment by c-myers1** [comment]
![comparison](https://user-images.githubusercontent.com/42839510/168053138-bb634964-98ed-465f-87dc-62d6ea8ebcd2.jpg)



This     
    
    $keyboard = [
        ['Yes', 'No'],
    ];

    $bot->sendRequest("sendMessage", ["text" => 'Hello', 'reply_markup' => json_encode([
        'keyboard' => $keyboard,
        'one_time_keyboard' => true,
        'resize_keyboard' => true
        ])
    ]);


vs

    $question = BotMan\BotMan\Messages\Outgoing\Question::create('Add line item?')
				->addButtons([
					BotMan\BotMan\Messages\Outgoing\Actions\Button::create('Yes')->value('yes'),
					BotMan\BotMan\Messages\Outgoing\Actions\Button::create('No')->value('no'),
				]);

			$this->ask($question, function (BotMan\BotMan\Messages\Incoming\Answer $answer) {
				if ($answer->isInteractiveMessageReply()) {
					$selectedValue = $answer->getValue(); // will be either 'yes' or 'no'
					$selectedText = $answer->getText(); // will be either 'Yes' or 'No'
				}

**Comment by filippotoso** [comment]
Botman Telegram driver uses inline keyboard to convert buttons added with the addButtons() method.

If you want to use the keyboard instead, you should relay on the $additionalParameters in the ask() method (see https://github.com/botman/botman/blob/2.0/src/Messages/Conversations/Conversation.php#L64 and https://github.com/botman/driver-telegram/blob/master/src/TelegramDriver.php#L336) to pass your custom keyboard payload using ask() instead of sendRequest().

**Comment by c-myers1** [comment]
Ok thanks, will check it out
