### ISSUE TITLE
How do I stop a conversation with a specified user without his response?

### ISSUE THREAD

**Issue by cyrtolat** [mpociot/botman#1321]
- BotMan Version: 2.6.3
- PHP Version: 8.0
- Messaging Service(s): Telegram
- Cache Driver: file

### Description:
Hi!

I want to unilaterally stop the conversation with the specified user in my Laravel project. I know his chat_id (sender) and the driver class (telegram), but i dont have the BotMan instance with him. Of course, i cant do "artisan cache:clear" because it will clear all other conversations with other users.

I need something like this:

    

    use BotMan\BotMan\Facades\BotMan;
    use BotMan\Drivers\Telegram\TelegramDriver;
    
    ...
    
    $chat_id = "1234567890";
    $driver = TelegramDriver::class;

    BotMan::stopConversation($chat_id, $driver);

Is it possible to do what I need in any way?

Thanks.

**Comment by filippotoso** [comment]
You can do that in the same way Botman does it:

https://github.com/botman/botman/blob/2.0/src/Traits/HandlesConversations.php#L196

https://github.com/botman/botman/blob/2.0/src/Messages/Incoming/IncomingMessage.php#L94
https://github.com/botman/botman/blob/2.0/src/Messages/Incoming/IncomingMessage.php#L104

Recreate the ID and pull them from the cache.

**Comment by Cyrtolat** [comment]
I did it. Its work. Thank you!

**Comment by cyrtolat** [comment]
> You can do that in the same way Botman does it:
> 
> https://github.com/botman/botman/blob/2.0/src/Traits/HandlesConversations.php#L196
> 
> https://github.com/botman/botman/blob/2.0/src/Messages/Incoming/IncomingMessage.php#L94 https://github.com/botman/botman/blob/2.0/src/Messages/Incoming/IncomingMessage.php#L104
> 
> Recreate the ID and pull them from the cache.

Thanks! It works. Just in case, I'll show my solution if anyone needs it.

    use Illuminate\Support\Facades\Cache;
    
    Cache::forget('conversation-'.sha1($chat_id).'-'.sha1($chat_id));
