### ISSUE TITLE
A problem with sending message in Telegram when there is no user in cache

### ISSUE THREAD

**Issue by ilia-kolesnikov** [mpociot/botman#1323]
- BotMan Version: 2.7.1
- PHP Version: 7.4.25
- Messaging Service(s):
- Cache Driver: Telegram

### Description:
I try to originate messages by starting new Conversation.
`$bot->startConversation(new ReadyConversation(), $client->chat_id, TelegramDriver::class);`

It works fine when user is in cache.
But when there are no user in cache I got an error  Error retrieving user info: Bad Request: chat_id is empty

So I can't originate new Conversations with users from database

### Steps To Reproduce:
Starting new conversation with user without cache or comment getting user from cache in Botman.php
`//if ($user = $this->cache->get('user_' . $this->driver->getName() . '_' . $this->getMessage()->getSender())) {
    //         return $user;
        // }`

**Comment by filippotoso** [comment]
I just tested and it works correctly clearing the cache before initiating the conversation.

Check what you are sending, logging the BotMan\BotMan\Http\Curl::executeRequest() method content.

If Telegram says that chat_id is empty, probably it is.

**Comment by ilia-kolesnikov** [comment]
It is empty, I try to dump botman config:

`array:4 [
  "config" => array:3 [
    "conversation_cache_time" => 40
    "user_cache_time" => 30
    "curl_options" => []
  ]
  "telegram" => array:2 [
    "token" => "xxxxxxxxxxxxx"
    "hideInlineKeyboard" => true
  ]
  "web" => array:1 [
    "matchingData" => array:1 [
      "driver" => "web"
    ]
  ]
  "bot_id" => ""
]`

There is nothing about bot_id in documentation, where should I store it?

**Comment by filippotoso** [comment]
If your `$client->chat_id` is empty it means you have a problem in another part of your code.

**Comment by ilia-kolesnikov** [comment]
$client->chat_id  is not empty. I have telegram user_id there(recipient).
`$botman->startConversation(new PizzaConversation(), 'my-recipient-user-id', TelegramDriver::class);`

Botman use getChatMember function of telegram api to get User info. There is 2 parameters: chat_id and user_id. Botman gets user_id from entry params and gets chat_id from config:
`$this->config['bot_id'] = $this->config['bot_id'] ?? '';

        ---

        $this->message = new IncomingMessage('', '', '', null, $this->config['bot_id']);`

And there is no bot_id in config.

**Comment by filippotoso** [comment]
This code works correctly:

```php
Artisan::command('telegram:test', function () {
    Artisan::call('cache:clear');

    DriverManager::loadDriver(TelegramDriver::class);

    $config = array_merge(
        config('botman.config'),
        [
            'telegram' => config('botman.telegram', [])
        ]
    );

    $botman = BotManFactory::create($config, new LaravelCache);

    $botman->startConversation(new OnboardingConversation(), '26238803', TelegramDriver::class);
});
```

**Comment by ilia-kolesnikov** [comment]
There is no clearing the cache in this example.
Try to add `dd('not in cache');` in 238 line of vendor/botman/botman/src/BotMan.php and you'll see, that botman gets user from cache(a little bit magic here...)

**Comment by filippotoso** [comment]
The first row in the closure (`Artisan::call('cache:clear');`) clears the cache.

To be sure, I maually deleted the content of storage/framework/cache before executing the code and it still works fine.

**Comment by filippotoso** [comment]
I finally found out the source of  your initial problem.

You were trying to use `getUser()` in the first message you sent from the initiated conversation. Telegram requires an additional parameter (chat_id) to get the user. This parameter is not present in the IncomingMessage used to start the conversation. Here's a code that solves you problem:

```php
// Instead of this:
// $user = $this->bot->getUser();

// Use this:
$message = new IncomingMessage('', $recipient, $recipient, null);
$user = $this->bot->getDriver()->getUser($message);

$this->say($user->getFirstName());
```

**Comment by ilia-kolesnikov** [comment]
Got it, thanks a lot!
I'll try this solution.
