### ISSUE TITLE
Is it possible to send a message in Slack as other user than the bot user?

### ISSUE THREAD

**Issue by WendellAdriel** [mpociot/botman#1324]
- BotMan Version: 2.7.1
- PHP Version: 7.4.3
- Messaging Service(s): Slack
- Cache Driver: Redis

### Description:
I need to send a message to a channel or a DM using my bot but as another user, is that possible to send messages as another user?

### Steps To Reproduce:
N/A

**Comment by filippotoso** [comment]
You should use the Slack API directly:

https://api.slack.com/
