### ISSUE TITLE
Empty answers in conversions

### ISSUE THREAD

**Issue by Roywcm** [mpociot/botman#1325]
- BotMan Version: 2.7.3
- PHP Version: 7.4
- Messaging Service(s): none
- Cache Driver: file

### Description:
When setting up a conversion, the answer/reply from the users is empty since version 2.7.3.

### Steps To Reproduce:

In a conversation:

```
public function askQuestion()
{
        $this->ask("what's the answer?", function(Answer $answer) {

            $answer = $answer->getText(); // returns an empty string

        });
}
```

**Comment by filippotoso** [comment]
Fixed in 2.7.4
