### ISSUE TITLE
Can't install Botman Studio

### ISSUE THREAD

**Issue by l1rak** [mpociot/botman#1326]
- BotMan Version: ~2.0
- PHP Version:8.0
- Messaging Service(s):/
- Cache Driver:/

### Description:
Hi, 
I am trying to install BotMan studio and trying to work my way around it for a project. But when installing, I am getting a lot of errors and bugs. First I am using PHPStorm as an IDE, I am running PHP version 8.0 on my system but I am getting an error which says
```
  Problem 1
    - Root composer.json requires php ^7.1.3 but your php version (8.0.10) does not satisfy that requirement.

```
I tried downgrading my version of PHP to 7.1.3 from XAMPP and tried running it but its still not working. 
![2022-06-02 14_41_05-chatbotFINALTEST – composer json](https://user-images.githubusercontent.com/15997982/171632161-8a1806a1-6dac-4f08-b499-c3e8d0706701.png)
![2022-06-02 14_40_49-chatbotFINALTEST – composer json](https://user-images.githubusercontent.com/15997982/171632181-295df235-5886-4642-a199-b26731c8af5c.png)

### Steps To Reproduce:
Fix installation problems.

**Comment by filippotoso** [comment]
Please open the ticket in the correct repository: https://github.com/botman/studio/issues
