### ISSUE TITLE
Facebook bot dont reply messages

### ISSUE THREAD

**Issue by nazar-goyda** [mpociot/botman#1327]
- BotMan Version: 2.0
- PHP Version: 8.0
- Messaging Service(s):
- Cache Driver: LaravelCache
- Laravel 8

### Description:
FaceboootkB does not respond at all. The post request comes, but nothing happens. I dont use Botman Studio.
![Screenshot from 2022-06-09 12-26-29](https://user-images.githubusercontent.com/13732728/172817430-8e3e3275-3f6e-47fe-8729-6ea91ef96550.png)

this is request from ngrok that the POST from FB is okay
![Screenshot from 2022-06-09 12-27-11](https://user-images.githubusercontent.com/13732728/172817780-5e7a2f78-6258-4334-b215-4eae27276ee6.png)

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Check you laravel.log file for errors.

Also, the configuration should be something like:

```php
$config = array_merge(
    config('botman.config'),
    [
        'facebook' => config('botman.facebook', [])
    ]
);

$botman = BotManFactory::create($config, new LaravelCache);
```

**Comment by nazar-goyda** [comment]
@filippotoso no errors in log. Still not working with this configuration(

**Comment by filippotoso** [comment]
At the beginning of the listen() method place a code like this:

```php
file_put_contents(__DIR__ . '/log.json', file_get_contents('php://input'));
```

Then send a message to the bot and post the content of the log.json file.

**Comment by nazar-goyda** [comment]
`{"object":"page","entry":[{"id":"104517412293075","time":1654770782696,"messaging":[{"sender":{"id":"5351519048203661"},"recipient":{"id":"104517412293075"},"timestamp":1654770782213,"message":{"mid":"m_knMZ_b60DXxWmlUhKiq5rDhY1eCo3qYKiK8tCnAikoKguO5Kd4Lmu9vTt2Oh9nDqzIpH2dN08hKRNedFnFj4lg","text":"test","nlp":{"intents":[],"entities":{},"traits":{"wit$sentiment":[{"id":"5ac2b50a-44e4-466e-9d49-bad6bd40092c","value":"neutral","confidence":0.6777}]},"detected_locales":[{"locale":"ru_RU","confidence":0.4622}]}},"thread_id":null}],"thread_id":null}]}`

**Comment by Atikur-hummingbird** [comment]
We are also facing similar issue, suddenly facebook messenger not responding.

[2022-06-09 11:45:02] local.ERROR: #0 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/forge/chatbot.hood.ai/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()

**Comment by bytemewebdev** [comment]
I am having the same problem. My facebook bot suddenly stopped working. It is working fine then suddenly today I received tons of tickets saying that the facebook messenger was not responding at all. `messaging_referrals` are working fine, but the `hears` function is not working.

**Comment by guiassemany** [comment]
It also happened to me today... I am still testing it and for some reason, if I remove the "thread_id" from the request, my service starts to respond with some json. When the thread_id: null is present, it does not return anything.

If I find something, I will update here.

**Comment by aalmonte** [comment]
Problem is at FacebookDriver. It has filters over message attributes that doesn't include new attribute thread_id.

As a quick fix override [hasMatchingEvent](https://github.com/botman/driver-facebook/blob/3345db228acf167296a214c5d9da4eb486425ef6/src/FacebookDriver.php#L127) and [getEventFromEventData](https://github.com/botman/driver-facebook/blob/3345db228acf167296a214c5d9da4eb486425ef6/src/FacebookDriver.php#L154) events to include new attribute in except method

```
/**
     * @return bool|DriverEventInterface
     */
    public function hasMatchingEvent()
    {
        $event = Collection::make($this->event->get('messaging'))->filter(function ($msg) {
            return Collection::make($msg)->except([
                    'sender',
                    'recipient',
                    'timestamp',
                    'message',
                    'postback',
                    'thread_id',
                ])->isEmpty() === false;
        })->transform(function ($msg) {
            return Collection::make($msg)->toArray();
        })->first();

        if (! is_null($event)) {
            $this->driverEvent = $this->getEventFromEventData($event);

            return $this->driverEvent;
        }

        return false;
    }

    /**
     * @param array $eventData
     * @return DriverEventInterface
     */
    protected function getEventFromEventData(array $eventData)
    {
        $name = Collection::make($eventData)->except([
            'sender',
            'recipient',
            'timestamp',
            'message',
            'postback',
            'thread_id',
        ])->keys()->first();
        switch ($name) {
            case 'referral':
                return new MessagingReferrals($eventData);
                break;
            case 'optin':
                return new MessagingOptins($eventData);
                break;
            case 'delivery':
                return new MessagingDeliveries($eventData);
                break;
            case 'read':
                return new MessagingReads($eventData);
                break;
            case 'account_linking':
                return new Events\MessagingAccountLinking($eventData);
                break;
            case 'checkout_update':
                return new Events\MessagingCheckoutUpdates($eventData);
                break;
            default:
                $event = new GenericEvent($eventData);
                $event->setName($name);

                return $event;
                break;
        }
    }
```

I left a [PR](https://github.com/botman/driver-facebook/pull/119) to main repo

**Comment by bytemewebdev** [comment]
> Problem is at FacebookDriver. It has filters over message attributes that doesn't include new attribute thread_id.
> 
> As a quick fix override [hasMatchingEvent](https://github.com/botman/driver-facebook/blob/3345db228acf167296a214c5d9da4eb486425ef6/src/FacebookDriver.php#L127) and [getEventFromEventData](https://github.com/botman/driver-facebook/blob/3345db228acf167296a214c5d9da4eb486425ef6/src/FacebookDriver.php#L154) events to include new attribute in except method
> 
> ```
> /**
>      * @return bool|DriverEventInterface
>      */
>     public function hasMatchingEvent()
>     {
>         $event = Collection::make($this->event->get('messaging'))->filter(function ($msg) {
>             return Collection::make($msg)->except([
>                     'sender',
>                     'recipient',
>                     'timestamp',
>                     'message',
>                     'postback',
>                     'thread_id',
>                 ])->isEmpty() === false;
>         })->transform(function ($msg) {
>             return Collection::make($msg)->toArray();
>         })->first();
> 
>         if (! is_null($event)) {
>             $this->driverEvent = $this->getEventFromEventData($event);
> 
>             return $this->driverEvent;
>         }
> 
>         return false;
>     }
> 
>     /**
>      * @param array $eventData
>      * @return DriverEventInterface
>      */
>     protected function getEventFromEventData(array $eventData)
>     {
>         $name = Collection::make($eventData)->except([
>             'sender',
>             'recipient',
>             'timestamp',
>             'message',
>             'postback',
>             'thread_id',
>         ])->keys()->first();
>         switch ($name) {
>             case 'referral':
>                 return new MessagingReferrals($eventData);
>                 break;
>             case 'optin':
>                 return new MessagingOptins($eventData);
>                 break;
>             case 'delivery':
>                 return new MessagingDeliveries($eventData);
>                 break;
>             case 'read':
>                 return new MessagingReads($eventData);
>                 break;
>             case 'account_linking':
>                 return new Events\MessagingAccountLinking($eventData);
>                 break;
>             case 'checkout_update':
>                 return new Events\MessagingCheckoutUpdates($eventData);
>                 break;
>             default:
>                 $event = new GenericEvent($eventData);
>                 $event->setName($name);
> 
>                 return $event;
>                 break;
>         }
>     }
> ```
> 
> I left a [PR](https://github.com/botman/driver-facebook/pull/119) to main repo

It is not working on Originating Messages. But I used the work around for quick replies and conversations

**Comment by nazar-goyda** [comment]
@aalmonte it work for me with reply method. But if i want to send messages all subscribers with command laravel, bot nothind send. No errors.

**Comment by bytemewebdev** [comment]
> @aalmonte it work for me with reply method. But if i want to send messages all subscribers with command laravel, bot nothind send. No errors.

use the old FacebookDriver for sending messages to all your subscribers

**Comment by bun4uk** [comment]
We faced the same issue

**Comment by nazar-goyda** [comment]
> 

its not working with old driver too

**Comment by filippotoso** [comment]
The latest version of the Facebook driver works correctly:

```php
    $config = array_merge(
        config('botman.config'),
        ['facebook' => config('botman.facebook', [])]
    );

    $botman = BotManFactory::create($config, new LaravelCache());

    $botman->say('Hello world!', 'recepient-id', FacebookDriver::class);
```
If you get the error_subcode 2018001, go into the developer dashboard and regenerate the token.
