### ISSUE TITLE
Deprecated: preg_match(): Passing null to parameter of type string

### ISSUE THREAD

**Issue by bun4uk** [mpociot/botman#1329]
- BotMan Version: master
- PHP Version: 8.1
- Messaging Service(s): Facebook Messenger
- Cache Driver: 

### Description:

We have a lot of deprecated level errors `"preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated"`
File: `/src/Messages/Matcher.php` 
Line: `57`

### Steps To Reproduce:
Just use Botman with PHP 8.1 and Facebook Messenger as Messaging Service

![image](https://user-images.githubusercontent.com/14631690/174628265-99861652-790f-465b-a3a3-c34be6bb36c3.png)

**Comment by filippotoso** [comment]
Should be solved in version 2.7.6
