### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by SergiX44** [mpociot/botman#133]
This is a nice library, but the documentation in the readme is not enough, because often I'm forced to see the source code of the library to try to understand how to do a certain thing.
It's possible to write a proper documentation using readthedocs or similar?
Thanks in advance

**Comment by mpociot** [comment]
I have already prepared a new website for this project, which will hold the documentation. See http://botman.io

If you want to help me with the documentation, here is the github repository for it: https://github.com/mpociot/botman-docs
