### ISSUE TITLE
When the package will be updated for Laravel 9 and PHP 8.1 ?

### ISSUE THREAD

**Issue by Odilbukh** [mpociot/botman#1331]
When the package will be updated for Laravel 9 and PHP 8.1 ?

- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Steps To Reproduce:

**Comment by filippotoso** [comment]
It already supports Laravel 9 and PHP 8.1.
 
https://github.com/botman/botman/discussions/1308#discussioncomment-3008604
