### ISSUE TITLE
How to send keyboard to telegram?

### ISSUE THREAD

**Issue by crazybee69** [mpociot/botman#1332]
- BotMan Version: 2.6.1
- PHP Version: 7.4
- Messaging Service(s): Telegram
- Cache Driver:

### Description:
I download telegram driver and configured it. The driver includes extensions in the form of Keyboard and Keyboard Button. How can I send them to the recipient? I have not found documentation on this issue anywhere.

### Steps To Reproduce:

**Comment by filippotoso** [comment]
https://github.com/botman/driver-telegram/issues/66
