### ISSUE TITLE
When Laravel 9 ?

### ISSUE THREAD

**Issue by Odilbukh** [mpociot/botman#1333]
Please update the package for support Laravel 9 and PHP 8.1

**Comment by filippotoso** [comment]
It already supports Laravel 9 and PHP 8.1.

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604

**Comment by Odilbukh** [comment]
How about Botman Studio ?

**Comment by filippotoso** [comment]
Botman Studio has very low practical use.

You can setup Botman in a Laravel application in 5 minutes following these steps:

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604
