### ISSUE TITLE
Configuration file path

### ISSUE THREAD

**Issue by clementmas** [mpociot/botman#1335]
- BotMan Version: 2.7.7

Thanks for the latest updates. I just published the configuration file using:

```
php artisan vendor:publish --tag=config --provider="BotMan\BotMan\BotManServiceProvider"
```

But it creates `config/botman/config.php` instead of `config/botman.php`.

Is that intentional? Can it be changed to the more conventional config file path?

**Comment by filippotoso** [comment]
It's the correct behaviour.
