### ISSUE TITLE
why are there 2 say() functions which take different parameters in different contexts?

### ISSUE THREAD

**Issue by valentinomariotto** [mpociot/botman#1340]
- BotMan Version: 2.7
- PHP Version: 8.1
- Messaging Service(s): Telegram (driver v1.6.2)
- Cache Driver: Laravel file

### Description:
Trying to originate a message from within a conversation causes an exception error:
`TypeError: Unsupported operand types: string + array in file /var/www/vendor/botman/driver-telegram/src/TelegramDriver.php on line 351`
> Because the contents of `$recipients` variable in the `say($message, $recipients... )` function is then passed to the `reply()` function as `$additionalParameters`, and it should not. 
> > Because you created a `public function say($message, $additionalParameters = [])` method for the `conversation::class ` and a `public function say($message, $recipients, $driver = null, $additionalParameters = [])` method for the `botman::class`, which IMHO makes no sense. 
Also, there's no mention of this in the documentation.

### Steps To Reproduce:

```
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Cache\LaravelCache;
use BotMan\Drivers\Telegram\TelegramDriver;
use BotMan\BotMan\Messages\Conversations\Conversation;

$botman = BotManFactory::create(config('botman'), new LaravelCache());

        $botman->hears('start',  function (BotMan $bot) { 
                        $bot->startConversation(new myConv);
                    });


class myConv extends Conversation {
 public function run(): void
    {
       $this->say("this is a test", "A_TELEGRAM_ID", TelegramDriver::class);
    }
}
```

### Workaround
```
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Cache\LaravelCache;
use BotMan\Drivers\Telegram\TelegramDriver;
use BotMan\BotMan\Messages\Conversations\Conversation;

$botman = BotManFactory::create(config('botman'), new LaravelCache());

        $botman->hears('start',  function (BotMan $bot) { 
                        $bot->startConversation(new myConv);
                    });


class myConv extends Conversation {
 public function run(): void
    {
       $this->bot->say("this is a test", "A_TELEGRAM_ID", TelegramDriver::class);
    }
}
```

**Comment by filippotoso** [comment]
Can't understand the issue.

The method say() in the Conversation class is used to communicate with the user that's currently in that conversation.

The higher leve method say() in the BotMan class allows to originate messages to any user.

**Comment by valentinomariotto** [comment]
How am I supposed to know that if there's nothing in the docs? 

Any confusion could have been avoided by using different names for the 2 different methods. 
Besides, $conversation->say() is just an alias for $conversation->bot->reply(), so it could have been named reply() as well.

**Comment by valentinomariotto** [comment]
mandi!

**Comment by filippotoso** [comment]
The documentation is clear about how to originate messages:

https://botman.io/2.0/sending#originating-messages
