### ISSUE TITLE
How to actually use say()?

### ISSUE THREAD

**Issue by jlauding** [mpociot/botman#1342]
- BotMan Version: 2.7
- PHP Version: 8.0
- Messaging Service(s): botman/driver-telegram
- Cache Driver:

### Description:
I'm confused. Have read the documentation and old issues but some things seems old and not answered.

1. How can I send messages without an active conversation?
I've tried using say() but nothing get sent until a user say something in. Let's say I want to send a morning message every morning at 8 am? Can this be solved somehow? (using Telegram driver)

Setting 'http_timeout' => 5000 is better but not perfect. Is it possible to use the webhook to force botman to trigger say on a certain time?

2. How to use say to groups chats? 

## Not working:
$group_id = $botman->getChannel()->getId();
$botman->say('Group id is: ' . $group_id , [$group_id], TelegramDriver::class );

### Steps To Reproduce:

**Comment by filippotoso** [comment]
> 1. How can I send messages without an active conversation?

As [per documentation](https://botman.io/2.0/sending#originating-messages):

```php
DriverManager::loadDriver(TelegramDriver::class);

$config = array_merge(
    config('botman.config'),
    [
        'telegram' => config('botman.telegram', [])
    ]
);

$botman = BotManFactory::create($config, new LaravelCache);

$botman->say('Message', 26238803, TelegramDriver::class); // 26238803 is the recepient id
```

> 2. How to use say to groups chats?

The prevous code should work also for groups. Be sure to use the correct recepient id. You can easily obtain the recepient id (chat_id) following these instructions: https://stackoverflow.com/a/46247058

**Comment by jlauding** [comment]
Thanks, I added logging and could get the chat id.

But still problem with sending messages out whenever I want. The messages passed with say() gets sent only after a user sent something to the group. (Telegram)

Any clues in order to solve this?

**Comment by filippotoso** [comment]
That's probably Telegram intended behaviour to reduce spam.

**Comment by jlauding** [comment]
I tried and used curl to ping my webhook which triggers the say. 

So I'm thinking; this a behaviour in botman, or maybe something with my server. I have no experience in sockets and not sure if botman actually works this way. So I guess I could set a cronjob to ping my own webhook to broadcast messages to users and/or groups.
