### ISSUE TITLE
Multiple answers to questions

### ISSUE THREAD

**Issue by AtefR** [mpociot/botman#1353]
How to allow multiple answers to a question?
all I could think of is storing the conversation again after receiving an answer, Is there a better way?

**Comment by filippotoso** [comment]
It depends on the driver you are using.

In drivers like Telegram and Facebook, you can show a numbered list of answers and ask the user to insert the number/letter of the answers he wants. Then in the conversation you can parse the text to extract the values.

In the web driver you can extends the driver and widget to include a checkbox payload to allow multiple selections.

**Comment by AtefR** [comment]
> 

I actually wrote a custom driver for Whatsapp. 
And the user can click on Whatsapp buttons. every button is an answer, But when the user clicks a button (Answer) the conversation ends and he has to initiate it again.

My question was how to allow the user to pick multiple answers and keeping the conversation.

**Comment by filippotoso** [comment]
WhatsApp behaves like Telegram and Facebook: when you click a button, the payload is sent to the bot. 
These platform don't provide a native way to send multiple "answers" through buttons.

What you can do is a looping method in the conversation. 
- On the first call you send a list of answers.
- You save the first answer and then recall the same method.
- On the second and subsequent call you show only the remaining answers and an additional button called something like "I'm done".

The loop continues until the users selects all the answers (you can also set a limit like "max 3 answers") or clicks on "I'm done".

Then you continue with the conversation.

In alternative, you implement the text base solution suggested in the previous comment.
