### ISSUE TITLE
How to show detailed information in listing of data ?

### ISSUE THREAD

**Issue by sergeynilov** [mpociot/botman#1354]
In laravel 9 app with botman/botman 2.7 and botman/driver-web 1.5  I have listing of data where I show only some header
information and I need selecting some item in this listing to show detailed information only for this selected item, like
collapse/hide block with data, modal popup or something like that...
Are there some decisions? Please link to example...

Thanks!

**Comment by filippotoso** [comment]
You must code this feature by hand.

Maybe implementing a generic HTML payload in the web driver and web widget. In this way you can do almost anything you want.
