### ISSUE TITLE
Can't integrate with Laravel 9

### ISSUE THREAD

**Issue by adolfoholzer** [mpociot/botman#1356]
- BotMan Version: 2.7
- PHP Version: 8.1.0
- Messaging Service(s): TELEGRAM
- Cache Driver: file

### Description:

I'm trying to integrate Botman with Laravel 9 and it's not working. When my app is responding the message is OK but for some reason I can't identify it throws a TelegramConnectionException.

I enabled **throw_http_exceptions** in **config/botman/telegram.php**

In TelegramDriver printed:

```
$response = $this->http->post($url, $urlParameters, $postParameters, $headers, $asJSON);
$responseData = json_decode($response->getContent(), true);
```

Response is:

```
[2023-01-22 16:44:55] local.INFO: RESPONSE in DRIVER: Symfony\Component\HttpFoundation\Response Object
(
    [headers] => Symfony\Component\HttpFoundation\ResponseHeaderBag Object
        (
            [headers:protected] => Array
                (
                    [cache-control] => Array
                        (
                            [0] => no-cache, private
                        )

                    [date] => Array
                        (
                            [0] => Sun, 22 Jan 2023 16:44:55 GMT
                        )

                )

            [cacheControl:protected] => Array
                (
                )

            [computedCacheControl:protected] => Array
                (
                    [no-cache] => 1
                    [private] => 1
                )

            [cookies:protected] => Array
                (
                )

            [headerNames:protected] => Array
                (
                    [cache-control] => Cache-Control
                    [date] => Date
                )

        )

    [content:protected] => 
    [version:protected] => 1.0
    [statusCode:protected] => 500
    [statusText:protected] => Internal Server Error
    [charset:protected] => 
)

[2023-01-22 16:44:55] local.ERROR: Status Code: 500
Description: No description from Telegram
Error Code: No error code from Telegram
Parameters: No parameters from Telegram
URL: https://api.telegram.org/botTELEGRAM-TOKEN-HIDDEN/sendMessage
URL Parameters: Array
(
)

Post Parameters: Array
(
    [chat_id] => {CORRECT CHAT ID}
    [text] => Hello!
)

Headers: Array
(
)

 {"exception":"[object] (BotMan\\Drivers\\Telegram\\Exceptions\\TelegramConnectionException(code: 0): Status Code: 500
```

### Steps To Reproduce:

Followed this [instructions](https://github.com/botman/botman/discussions/1308)

**Comment by filippotoso** [comment]
Are you testing this online or locally using a service like "ngork"?

If you send the same exact request using Postman, does it work?

**Comment by adolfoholzer** [comment]
I debugged printing values into logs, in TelegramDriver method postWithExceptionHandling botman sends the post request and when evaluates if it's OK gets a 500 error so the function still going and throws the exception.


```
private function postWithExceptionHandling(
        $url,
        array $urlParameters = [],
        array $postParameters = [],
        array $headers = [],
        $asJSON = false,
        int $retryCount = 0
    ) {
        $response = $this->http->post($url, $urlParameters, $postParameters, $headers, $asJSON);
        $responseData = json_decode($response->getContent(), true);
        if ($response->isOk() && isset($responseData['ok']) && true ===  $responseData['ok']) {
            return $response;
        } elseif ($this->config->get('retry_http_exceptions') && $retryCount <= $this->config->get('retry_http_exceptions')) {
            $retryCount++;
            if ($response->getStatusCode() == 429 && isset($responseData['retry_after']) && is_numeric($responseData['retry_after'])) {
                usleep($responseData['retry_after'] * 1000000);
            } else {
                $multiplier = $this->config->get('retry_http_exceptions_multiplier')??2;
                usleep($retryCount*$multiplier* 1000000);
            }
            return $this->postWithExceptionHandling($url, $urlParameters, $postParameters, $headers, $asJSON, $retryCount);
        }
        $responseData['description'] = $responseData['description'] ?? 'No description from Telegram';
        $responseData['error_code'] = $responseData['error_code'] ?? 'No error code from Telegram';
        $responseData['parameters'] = $responseData['parameters'] ?? 'No parameters from Telegram';


        $message = "Status Code: {$response->getStatusCode()}\n".
            "Description: ".print_r($responseData['description'], true)."\n".
            "Error Code: ".print_r($responseData['error_code'], true)."\n".
            "Parameters: ".print_r($responseData['parameters'], true)."\n".
            "URL: $url\n".
            "URL Parameters: ".print_r($urlParameters, true)."\n".
            "Post Parameters: ".print_r($postParameters, true)."\n".
            "Headers: ". print_r($headers, true)."\n";

        $message = str_replace($this->config->get('token'), 'TELEGRAM-TOKEN-HIDDEN', $message);
        throw new TelegramConnectionException($message);
    }
```

I have 2 projects waiting for this (facepalm)

I make a demo but with botman-studio (laravel 5.6) and it works fine. When I want to integrate botman to Laravel 9 or 10 it's not working.

Any ideas?

**Comment by filippotoso** [comment]
You haven't answered to any of the questions in the previous comment.

**Comment by adolfoholzer** [comment]
Sorry.

I have the app in my local windows and set the Telegram webhook using ngrok. Works in the demo with botman-studio (laravel 5.6) and the same thing doesn't work integrating botman with Laravel 9|10.

I sent a request to the url provided by ngrok and the response is a 200 with no text at all (also tested with another route to know if the request hit the app and it's correct responding with a string)

**Comment by filippotoso** [comment]
> If you send the same exact request using Postman, does it work?

What I ment is: if you send the request created by Botman to Telegram, does it work?

Create a working payload that you are able to send to Telegram (and see the message in the bot).
Then compare it with what Botman is sending.

**Comment by adolfoholzer** [comment]
I printed all parameters in

`$response = $this->http->post($url, $urlParameters, $postParameters, $headers, $asJSON);`

Url is correct.
Url parameters are empty.
Post parameters are chat_id and text.
Headers are empty.

Using postman sent a request to Telegram (url from above + post parameters) and the bot answers to chat_id user, so it's working.

**Comment by filippotoso** [comment]
This is a working Laravel 9 Telegram bot.

[demo.zip](https://github.com/botman/botman/files/10832063/demo.zip)

**Comment by adolfoholzer** [comment]
Demo.zip is 7kb only and has no files, just directories.

**Comment by adolfoholzer** [comment]
Downloaded.

composer install

.env TELEGRAM_TOKEN set

php artisan serve

webhook set

Test in Telegram---> Same error.

Something weird is happening here. I noticed you used botman/driver-telegram 1.6, in my newer tests it uses 2.0.

Changed the pc, tried again, not working either.

**Comment by filippotoso** [comment]
The provided demo works. The problem must be on your end.

**Comment by filippotoso** [comment]
Upgraded to Telegram driver version 2.0.4, still working correctly.

**Comment by adolfoholzer** [comment]
Still haven't found the error.

Created new repository with your project code, uploaded to my server using Forge. It works in production server, not local.

So weird.

Thanks for your time and patience Filippo.
