### ISSUE TITLE
Can I to show fontawesome-free icons? 

### ISSUE THREAD

**Issue by sergeynilov** [mpociot/botman#1357]
In laravel 9.19 app with botman/botman 2.7 and botman/driver-web 1.5 and @fortawesome/fontawesome-free 5.15.4
I want to show icons on botman messages, like :

```
        $quizText     = ‘<i class="fa fa-save"></i> ’; 
        $quizTemplate = BotManQuestion::create($quizText);


        $quizText     = ‘{!! <i class="fa fa-save"></i> !!} ’; 
        $quizTemplate = BotManQuestion::create($quizText);

```
But in both cases I see just text, not icons.
In other parts of the app such  icons are shows ok.
If there is  way to show fontawesome-free icons? Maybe icons of some other libraries?

Thanks!

**Comment by filippotoso** [comment]
You have to customize the web widget to parse the content of the message and display the icons. 

In alternative you can customize the web driver and web widget to support a generic HTML payload so you can rendere whatever you want in the messages.

In any case you need to import the CSS in the view that renders the chat.

**Comment by sergeynilov** [comment]
Could, you please to provide links to such examples/mamuals?

**Comment by filippotoso** [comment]
I just discovered that the web widget already supports HTML.

You just need need to import the CSS in the view that renders the chat.

```html
<!doctype html>
<html>
<head>
    <title>BotMan Widget</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/assets/css/chat.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
</head>
<body>
<script>
var botmanWidget = {
    chatServer: '/botman'    
};
</script>
    <script id="botmanWidget" src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/chat.js'></script>
</body>
</html>
```

And then simply send HTML to the widget:

```php
$botman->hears('Hello', function (BotMan $bot) {
    $bot->reply('Hi there <i class="fas fa-user"></i>');
});
```

**Comment by sergeynilov** [comment]
In my container blade file I have link to font-awesome all.min.css file and  botmanWidget is set

but your code :

`$bot->reply('Hi there <i class="fas fa-user"></i>');
`does not show icons: https://prnt.sc/FiI_37n5-GRR

If I have a piece of code with icon in BotManQuestion::create( code I see the code as it is : https://prnt.sc/fSs7twtS7jE-

Some additive configs ?

**Comment by filippotoso** [comment]
The previously suggested code works correctly.

BotManQuestion is not a native class of BotMan. 

Debug your BotManQuestion code to understand why it doesn't work with it (ie. there's an htmlentities() call somewhere, etc.)

**Comment by sergeynilov** [comment]
Looking at this issue one more time I see that icon class name is rendered a bit different : https://prnt.sc/wRgieWCjvGzS

My browser show i element as “i.fas.fa-user”, not “fas fa-user”.
1) Can it issue of the problem on my side?

2) Looking at source of page
https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/assets/css/chat.min.css
I wonder can salvation be to  create manually “i.fas.fa-user” class in my app? 
But how to copy code of this class from refernced css file ?

**Comment by filippotoso** [comment]
i.fas.fa-user is a CSS selector that identify the <i class="fas fa-user"> tag:

https://www.w3schools.com/cssref/css_selectors.php

Use your browser developer console and check if fontawesome assets are correctly loaded.

As already said, the previous code works correctly.
