### ISSUE TITLE
Telegram force_reply

### ISSUE THREAD

**Issue by Kaos1337** [mpociot/botman#136]
Hello,
in a conversation I'd like to use in one step the [force_reply](https://core.telegram.org/bots/api#forcereply) option, it should be set as parameter inside the reply_markup, so into the ask function I should use it like this:
```php
$this->ask("Message...", function (Answer $answer) {
   // Code here...
}, ['reply_markup' => ['force_reply' => true]]);
```
but isn't correct, even if the same thing works with ` ['parse_mode' => 'Markdown']`
How should be used the force_reply?
Thank you.

**Comment by mpociot** [comment]
This will work:

```php
$this->ask("Message...", function (Answer $answer) {
   // Code here...
}, ['reply_markup' => json_encode(['force_reply' => true])]);
```
