### ISSUE TITLE
How to set time of conversation session?

### ISSUE THREAD

**Issue by PetroGromovo** [mpociot/botman#1361]
When in started conversation with opened quesion 

`            $template->addButton(Button::create('text') );
`

user makes a long pause(say 2 hours) without any action

the botman hang and no reaction to any click, inside or outside of buttons.

If I set in .env some big value:

`SESSION_LIFETIME=10080 # 1 week
`
looks like it is not applyed.

In file config/botman/config.php :I have 2 options :

```
<?php

return [
    'conversation_cache_time' => 10080, // 1 week
    'user_cache_time'         => 10080, // 1 week
];

```
But looks like thay are not applied ...

1) Where can I set time of conversation session?
2) If there is a way to catch such errors or trigger event when time has passed "

```
        "botman/botman": "^2.7",
        "laravel/framework": "^9.19",

```

     Thanks in advance!

**Comment by filippotoso** [comment]
Please include the complete code where you create the Botman instance.

**Comment by PetroGromovo** [comment]
I my BotManController i have :

```
    public function handle()
    {
        DriverManager::loadDriver(\BotMan\Drivers\Web\WebDriver::class);
        $config = array_merge(
            config('botman.config'),
            [
                'web' => config('botman.web', [])
            ]
        );
        $botman = BotManFactory::create($config, new LaravelCache);

        $botman->hears('{message}', function ($botman, $message) {
            if ($message === 'start') {
            ...
            
```

Is it enough ?

**Comment by filippotoso** [comment]
This will work:

```php
$config = array_merge([
    'config' => config('botman.config')
], [
    'web' => config('botman.web', [])
]);
```
