### ISSUE TITLE
Issues with conversations, cache and buttons

### ISSUE THREAD

**Issue by jupitern** [mpociot/botman#1362]
- BotMan Version: 2.7.8
- PHP Version: 8.0.26
- Messaging Service(s): WebDriver
- Cache Driver: Redis

### Description:

Issue 1:
Without adding cache messages work fine but conversations do not work. When I respond to question inside conversation goes to fallback.

Issue 2:
Using Redis cache. 
1. type a message > Bot presents response with buttons. I click on one of the buttons and it works fine.
2. type same message again > Bot presents response with buttons. I click on one of the buttons > payload is sent to php but response comes empty. {messages: [], status: 200}. I click again on same button > same payload is sent and response comes out as expected and it now works. 
3. Repeat (2.) with any messages that respond with buttons but only second click works although payloads are exactly the same

### code sample

$config = [
    'conversation_cache_time' => 10,
    'user_cache_time' => 10,
    'matchingData' => [
        'driver' => 'web',
    ],
];

$cache = new RedisCache('localhost', 6379, 'redispass');
$botman = BotManFactory::create($config, $cache);

$startQuestion = Question::create('Escolha uma das seguintes opções:')
    ->fallback('Por favor seleccione uma opção da lista apresentada')
    ->callbackId('menu_option')
    ->addButtons([
        Button::create('about')->value('about'),
        Button::create('information request')->value('credits'),
        Button::create('Our Missson')->value('mission'),
        Button::create('Contacts')->value('contacts'),
    ]);

$botman->fallback(function(BotMan $bot) use ($startQuestion) {
    $bot->reply("Sorry I did not understand");
    $bot->ask($startQuestion, function (Answer $answer) use($bot) {});
});

**Comment by filippotoso** [comment]
> Issue 1:
> Without adding cache messages work fine but conversations do not work.

The cache is required for Botman to "remember" the conversation state.

> Issue 2:

To ask questions, use a conversation:
https://botman.io/2.0/conversations#asking-questions
