### ISSUE TITLE
Install with guzzle ^7.0.1

### ISSUE THREAD

**Issue by agrimagsrl** [mpociot/botman#1364]
Running 

`composer require "botman/installer" -W` 

throws error 

`botman/installer[1.0.0, ..., 1.0.4] require guzzlehttp/guzzle ~4.0|~5.0|~6.0 -> found guzzlehttp/guzzle[4.0.0-rc.1, ..., 4.x-dev, 5.0.0, ..., 5.3.x-dev, 6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).`

I'm using Laravel 8.75

**Comment by filippotoso** [comment]
Open the issue it in the right repository.

**Comment by agrimagsrl** [comment]
I cannot see a "Issues" tab on the "botman/installer" repository.

**Comment by filippotoso** [comment]
If you need to use Botman, follows these steps:

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604
