### ISSUE TITLE
Suggestion: enable automatic updates on packagist.org

### ISSUE THREAD

**Issue by holtkamp** [mpociot/botman#1365]
### Description:
It seems https://packagist.org/packages/botman/botman is not updated automatically. 

The documentation on https://packagist.org/about#how-to-update-packages explains: 

> Existing packages without auto-updating (GitHub/BitBucket/GitLab/Gitea hook) will be crawled once a week for updates. When a hook is enabled, packages are crawled whenever you push, or at least once a month in case the crawl failed. You can also trigger a manual update on your package page if you are logged-in as a maintainer.

https://github.com/botman/botman/releases/tag/v2.8.1 was created on Monday 27-02-2023 14:28 GMT+1, but on [packagist](https://packagist.org/packages/botman/botman) the most recent version is `2.8.0`, even though one week has passed:

![Screenshot 2023-03-08 at 10 22 44](https://user-images.githubusercontent.com/776405/223673934-eb2cc90c-24fc-4641-9e7a-eab93ba86ad9.png)

Not sure what the cause of this delay is, but would it be an idea to enable automatic updates for https://packagist.org/packages/botman/botman ?

**Comment by filippotoso** [comment]
I manually update because I don't have access to the packagist account.

**Comment by holtkamp** [comment]
@filippotoso ah, ok, thanks for the swift reaction. 

@mpociot, you are listed as package maintainer: https://packagist.org/users/mpociot/, is this something you could consider to configure?
