### ISSUE TITLE
Whatsapp API

### ISSUE THREAD

**Issue by theo-1** [mpociot/botman#1366]
### Description:

Can anyone just kindly give some more detailed guidance as to how to really build a Whatsapp driver for the non-experts amongst us?

Using the Botman guidance (https://botman.io/2.0/drivers#setup) and the actual Telegram driver code (https://github.com/botman/driver-telegram/blob/master/src/TelegramDriver.php), vis-a-vis the actual Telegram API (https://core.telegram.org/bots/api#chat), I simply don't see where "message", "edited_message" and "channel_post" tags come from. Talk less of how to adapt it to whatsapp api here (https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#guides).

I presume there is some license issue that's preventing someone from sharing their whatsapp driver code but I am willing to slug it out and build one myself if there can be some solid guidance. Perhaps if just this buildPayload can be thoroughly clarified, it should be easier to figure out the rest.

Thanks in advance!

**Comment by filippotoso** [comment]
Multiple community WhatsApp drivers are already available:

https://packagist.org/?query=botman%20whatsapp

**Comment by theo-1** [comment]
Awesome, thanks for the link. Every other response hitherto seen on this site has been the "write you own driver" mantra. 

:-)

**Comment by mohapinkepane** [comment]
For anyone looking for Botman WhatsApp Cloud API driver in 2025 :  https://github.com/mohapinkepane/driver-whatsapp-cloud
