### ISSUE TITLE
How can i save chat logs to a log file?

### ISSUE THREAD

**Issue by oredal** [mpociot/botman#1367]
Hi everyone, I'm developing a simple chatbot with the webdriver, php 8.0.13 but without using botman studio, laravel or other frameworks. I would like to save the content of requests from users and responses from the bot to later analyze chats. Do you have any suggestions about? Thanks to everyone who wants to help me.

**Comment by filippotoso** [comment]
Build a middleware and implement the received and sending methods.

https://botman.io/2.0/middleware

In them log the requests as needed.

**Comment by oredal** [comment]
Ok, and this implementation can also be used with the driver for facebook and telegram right?

**Comment by filippotoso** [comment]
Yes

**Comment by oredal** [comment]
Thank you Filippo!
