### ISSUE TITLE
Separate "models",  error forum/slack and Discord support

### ISSUE THREAD

**Issue by StrangerGithuber** [mpociot/botman#1368]
Hi
I tried to register to the forum and going to the slack but I get error message such as "Whoops, looks like something went wrong."
So I am writing here my question.
I am using laravel 10 and I am curious of some things:
How I can make for conversations in different models? Such as AIML files are in categories and in 1 AIML file can have a lot text.
Do you planning to have Discord driver too?

Thank you in advance the answers.

**Comment by filippotoso** [comment]
Botman doesn't support AIML files.

>Do you planning to have Discord driver too?

https://packagist.org/?query=botman%20discord

**Comment by StrangerGithuber** [comment]
I just gave as example. Is it possible to separate the hear and reply things to categories?

For example:
Animals.PHP - Just animal questions
Computers.PHP - Just computer related questions 
Nature.PHP - Just nature related questions.
Weather.PHP - Just weather related questions
Etc...

Is it possible to do such thing?

> Botman doesn't support AIML files.
> 
> 
> 
> >Do you planning to have Discord driver too?
> 
> 
> 
> https://packagist.org/?query=botman%20discord

**Comment by filippotoso** [comment]
Botman supports conversations: https://botman.io/2.0/conversations

You can create different conversations for different "domains".

In DialogFlow, train you questions and create a some sort of database with the answers. Then use the action to match questions and answers.
