### ISSUE TITLE
Welcome message when web widget opened?

### ISSUE THREAD

**Issue by oredal** [mpociot/botman#1369]
Hi everyone, I'm developing a simple chatbot with the webdriver, php 8.0.13 but without using botman studio, laravel or other frameworks. I would like the bot to send one or even more welcome messages as soon as the chat opens. I've used botmanChatWidget.whisper(text) and it works fine, but I'd like something that is automatic when the chat window opens. Any suggestion? Thanks.

**Comment by filippotoso** [comment]
Customize the widget source code as needed.
