### ISSUE TITLE
Slow bot reply with telegram-driver

### ISSUE THREAD

**Issue by tayyabbashir2224** [mpociot/botman#1371]
- BotMan Version: 2.0
- PHP Version:7.1.3
- Messaging Service(s):Telegram
- Cache Driver:

### Description:
Slow reply

### Steps To Reproduce:
i just have installed bot on laravel and it is working, but it replies very slow.
but it is working smothly with tinker.

**Comment by filippotoso** [comment]
Are you using ngrok or a similar too to locally test the bot or the bot is installed on a web server?

**Comment by tayyabbashir2224** [comment]
> Are you using ngrok or a similar too to locally test the bot or the bot is installed on a web server?

I have already installed it on server and it was not replying. But bot reply after 5 mins.

**Comment by filippotoso** [comment]
Add some logging code and check the time when you receive the message from Telegram webhook and the time you sent the message to Telegram (ie. using say(), reply(), etc.).

**Comment by tayyabbashir2224** [comment]
> Add some logging code and check the time when you receive the message from Telegram webhook and the time you sent the message to Telegram (ie. using say(), reply(), etc.).
Sometime Receiving message every minute even no command was send.

**Comment by filippotoso** [comment]
Have you added the logging code?
Where have you added it?
What are the results?

Are there errors in the laravel.log file?

**Comment by tayyabbashir2224** [comment]
No error in laravel.log,
