### ISSUE TITLE
cURL error 60: SSL: no alternative certificate subject name matches target host name 'graph.facebook.co'

### ISSUE THREAD

**Issue by zerexei** [mpociot/botman#1380]
- BotMan Version: 2.8
- "botman/botman": "^2.8",
- "botman/driver-facebook": "^1.11",
- PHP Version: 8.1.22
- Messaging Service(s): facebook
- Cache Driver: LaravelCache

### Description:
Botman is sending curl to graph.facebook.co not graph.facebook.com

cURL error 60: SSL: no alternative certificate subject name matches target host name 'graph.facebook.co' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

```
curl -vks https://graph.facebook.co
* About to connect() to graph.facebook.co port 443 (#0)
*   Trying 157.240.254.35...
* Connected to graph.facebook.co (157.240.254.35) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.facebook.com,O="Meta Platforms, Inc.",L=Menlo Park,ST=California,C=US
*       start date: Jun 10 00:00:00 2023 GMT
*       expire date: Sep 08 23:59:59 2023 GMT
*       common name: *.facebook.com
*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: graph.facebook.co
> Accept: */*
>
< HTTP/1.1 302 Found
< Location: https://www.facebook.com/
< Content-Type: text/html; charset="utf-8"
< X-FB-Debug: +uZp53FZIOptgwIVF9ULV8VTjEA+tPB6NEaq4L2zdwGoZBievq4oazqzRp/g549TdyCgVvwEIsrIIWTVm1+h9A==
< Date: Fri, 01 Sep 2023 02:32:53 GMT
< Alt-Svc: h3=":443"; ma=86400
< Connection: keep-alive
< Content-Length: 0
<
* Connection #0 to host graph.facebook.co left intact
```
![image](https://github.com/botman/botman/assets/69749146/4c94a71f-7d26-44a2-9de0-f50eb2e5761b)

![image](https://github.com/botman/botman/assets/69749146/d109ce80-db96-40e2-9ced-aacf6e081470)

![image](https://github.com/botman/botman/assets/69749146/fa0cf044-d33d-418c-bc1d-d609b026b29e)

![image](https://github.com/botman/botman/assets/69749146/7616ad5b-19e2-4ff0-9ba9-69e55917d6f3)

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Please send the excerpt of the source code where the call is made.

As far as I can see, the call is not generated by Botman (or the Facebook driver) because the URL doesn't include the v3.0 prefix:

```
... for https://graph.facebook.com/592... 
```

**Comment by zerexei** [comment]
I didn't specify it and I tried using vscode `ctr+shift+f` (also included gitignore) but it didnt show any __graph.facebook.co__ url

here is the complete error log
Exception in file /home/DOMAIN/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php

at line 211: 

cURL error 60: SSL: no alternative certificate subject name matches target host name 'graph.facebook.co' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://graph.facebook.co/PAGE-ID?access_token=

**Comment by filippotoso** [comment]
On line 210 of CurlFactory.php insert a call to `debug_print_backtrace()` and post the output when the error is raised.

**Comment by zerexei** [comment]
> On line 210 of CurlFactory.php insert a call to `debug_print_backtrace()` and post the output when the error is raised.

nothing is raised, maybe the cpanel server doesn't show errors

**Comment by filippotoso** [comment]
Let's try again...

On line 210 of CurlFactory.php insert:

```php
ob_start();
debug_print_backtrace()
file_put_contents(__DIR__ . '/log-' . microtime() . ' .txt', ob_get_clean());
```

Post the log file created.

**Comment by zerexei** [comment]
no file created also tried with ls -la, no txt log

![image](https://github.com/botman/botman/assets/69749146/0b2c369d-d1ba-46ac-818a-14d9d42daa83)

![image](https://github.com/botman/botman/assets/69749146/ab61195b-4e9d-4bd5-93c4-d0bdb5b8b718)

**Comment by filippotoso** [comment]
If the file has not been created, it means the code has not been executed, and the exception "cURL error 60: SSL: no alternative certificate..." has not been raised.

I'm closing this as it's not a Botman issue.
