### ISSUE TITLE
Bad Request: invalid user_id specified

### ISSUE THREAD

**Issue by chimit** [mpociot/botman#1381]
- BotMan Version: 2.8.1
- PHP Version: 7.4
- Messaging Service(s): Telegram
- Cache Driver: Redis

### Description:

As suggested by @mpociot [here](https://github.com/botman/botman/issues/536#issuecomment-329446733) I'm trying to get a user via a driver in my Received middleware:

```php
public function received(IncomingMessage $message, $next, BotMan $bot)
{
    info($message->getSender());
    info($message->getRecipient());
    info($message->getPayload());

    $botman_user = $bot->getDriver()->getUser($message);
```

Everything works in most cases, but sometimes (I can't find any pattern) I get errors in logs:

```
[2023-09-01 07:18:41] production.ERROR: Error retrieving user info: Bad Request: invalid user_id specified {"exception":"[object] (BotMan\\Drivers\\Telegram\\Exceptions\\TelegramException(code: 0): Error retrieving user info: Bad Request: invalid user_id specified at /home/example/example.com/vendor/botman/driver-telegram/src/TelegramDriver.php:88)
[stacktrace]
```

Based on logs, looks like Botman sends `0` instead of a correct user ID to Telegram. Any ideas on how it can be possible?

Logs:
```
[2023-09-01 08:25:38] production.INFO: 0                  // $message->getSender()
[2023-09-01 08:25:38] production.INFO:                    // $message->getRecipient()
[2023-09-01 08:25:38] production.INFO: {"from":{"id":0}}  // $message->getPayload()
```

**Comment by filippotoso** [comment]
Log the entire $message payload and start from there.

If `getSender()` returns 0, then `getUser()` will fail.

**Comment by chimit** [comment]
Here is the `$message` content when it happens:

```
[2023-09-03 15:27:08] production.INFO: BotMan\BotMan\Messages\Incoming\IncomingMessage::__set_state(array(
   'message' => NULL,
   'sender' => 0,
   'recipient' => NULL,
   'bot_id' => '',
   'images' => 
  array (
  ),
   'videos' => 
  array (
  ),
   'payload' => 
  Illuminate\Support\Collection::__set_state(array(
     'items' => 
    array (
      'from' => 
      array (
        'id' => 0,
      ),
    ),
     'escapeWhenCastingToString' => false,
  )),
   'extras' => 
  array (
  ),
   'audio' => 
  array (
  ),
   'files' => 
  array (
  ),
   'location' => NULL,
   'contact' => NULL,
   'isFromBot' => false,
))  
```

**Comment by filippotoso** [comment]
There's nothing there. Someone or something (ie. a crawler) is calling the endpoint without passing any data.

**Comment by chimit** [comment]
This happens when a bot is added or removed from a group. Looks like Received middleware captures such service messages:

```
{
    "update_id": 22069942,
    "my_chat_member": {
        "chat": {
            "id": -222222222,
            "title": "Test",
            "type": "group",
            "all_members_are_administrators": true
        },
        "from": {
            "id": 111111111,
            "is_bot": false,
            "first_name": "Example",
            "username": "Example",
            "language_code": "fr"
        },
        "date": 1693746567,
        "old_chat_member": {
            "user": {
                "id": 3333333333,
                "is_bot": true,
                "first_name": "Botname",
                "username": "botnamebot"
            },
            "status": "left"
        },
        "new_chat_member": {
            "user": {
                "id": 3333333333,
                "is_bot": true,
                "first_name": "Botname",
                "username": "botnamebot"
            },
            "status": "member"
        }
    }
}
```

Is there a way to skip such messages?

**Comment by filippotoso** [comment]
Just write some code in your Middleware to exclude the processing of this kind of messages.

**Comment by chimit** [comment]
Yes, I did it this way:

```php
public function received(IncomingMessage $message, $next, BotMan $bot)
{
    // Ignore service messages
    if (! $message->getSender()) {
        return $next($message);
    }
```

For those who are looking how to capture service messages here are the list of [supported Telegram events](https://github.com/botman/driver-telegram/blob/b681bf94a8e1537c385a34131e8de8075c3866c8/src/TelegramDriver.php#L31-L37). Usage is described [here](https://botman.io/2.0/receiving#payload).

**Comment by chimit** [comment]
Another way to ignore service messages is not to use the Received middleware but instead use Heard and Captured.

**Comment by chimit** [comment]
I realized that one of the reasons for this error is when users add a bot into a channel. Messages from channel admins are anonymous so `getUser()` method fails. I had to ignore channels in the middleware.
