### ISSUE TITLE
FacebookDriven verification error

### ISSUE THREAD

**Issue by yashiroiori** [mpociot/botman#1388]
- BotMan Version: ^2.8
- PHP Version: 8.2
- Messaging Service(s): Facebook ^1.11
- Cache Driver: none

### Description:
I try to set config "verification" word like this

<img width="318" alt="image" src="https://github.com/botman/botman/assets/17031855/2630588c-71f5-4361-837a-2d95ecf2d179">

### Steps To Reproduce:
But send me error

<img width="949" alt="image" src="https://github.com/botman/botman/assets/17031855/d799a2a7-b68e-4d7b-97f9-596e9f604e54">

Into FacebookDrive say
<img width="946" alt="image" src="https://github.com/botman/botman/assets/17031855/9352197e-8fdb-4da9-b366-62e462cbd863">

**Comment by filippotoso** [comment]
Try the latest version of the Facebook driver (v. 1.11.2)
