### ISSUE TITLE
Conversation lost when reload page

### ISSUE THREAD

**Issue by HuynhLoan** [mpociot/botman#1389]
How can we store the chat as whenever i reload the page or visits any other page in my website my chat gets removed and I have to start the chat again.

**Comment by filippotoso** [comment]
Are you using the web widget?

If that's the case, post on the web widget repository. It's a client side feature that need to be implemented (i.e. storing the messages into the local storage and restore the on startup)

**Comment by HuynhLoan** [comment]
Can you tell me how to restore chat on startup? I have tried many ways but still cannot solve the problem

**Comment by filippotoso** [comment]
You have to implement it in the web widget.

When it sends/receives messages, put them in the local storage:

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

On startup, load them from the local storage.

**Comment by HuynhLoan** [comment]
I tried with this code but it doesn't save my chat to local Storage. Help me!!!
`<!doctype html>
<html>
<head>
    <title>BotMan Widget</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/assets/css/chat.min.css">
</head>
<body>
    <script>
        // Function to set chat messages in local storage
        function setChatMessages(messages) {
            localStorage.setItem('chatMessages', JSON.stringify(messages));
        }

        // Function to get chat messages from local storage
        function getChatMessages() {
            var storedMessages = localStorage.getItem('chatMessages');
            return storedMessages ? JSON.parse(storedMessages) : [];
        }

        // Function to add a new message to local storage
        function addMessageToStorage(type, content) {
            var chatMessages = getChatMessages();
            chatMessages.push({ type: type, content: content });
            setChatMessages(chatMessages);
        }

        var botmanWidget = {
            frameEndpoint: '/widget',
            introMessage: "✋ Hi!",
            customPayload: {
                sendCallback: function (event, message) {
                    // Add the sent message to local storage
                    addMessageToStorage('sent', message);
                },
                receiveCallback: function (event, message) {
                    // Add the received message to local storage
                    addMessageToStorage('received', message.content);
                }
            }
        };
    </script>
    <script src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/widget.js'></script>
</body>
</html>`

**Comment by HuynhLoan** [comment]
It's really difficult for me, it doesn't save to local storage when sending/receiving messages. Please help me!!
`<!doctype html>
<html>
<head>
    <title>BotMan Widget</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/assets/css/chat.min.css">
</head>
<body>
    <script>
        // Function to set chat messages in local storage
        function setChatMessages(messages) {
            localStorage.setItem('chatMessages', JSON.stringify(messages));
        }

        // Function to get chat messages from local storage
        function getChatMessages() {
            var storedMessages = localStorage.getItem('chatMessages');
            return storedMessages ? JSON.parse(storedMessages) : [];
        }

        // Function to add a new message to local storage
        function addMessageToStorage(type, content) {
            var chatMessages = getChatMessages();
            chatMessages.push({ type: type, content: content });
            setChatMessages(chatMessages);
        }

        var botmanWidget = {
            frameEndpoint: '/botman/chat',
            introMessage: "✋ Hi!",
            customPayload: {
                sendCallback: function (event, message) {
                    // Add the sent message to local storage
                    addMessageToStorage('sent', message);
                    console.log('Sent message:', message);
                },
                receiveCallback: function (event, message) {
                    // Add the received message to local storage
                    addMessageToStorage('received', message);
                    console.log('Received message:', message);
                }
            }
        };

    </script>
    <script src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/widget.js'></script>
</body>
</html>`

**Comment by HuynhLoan** [comment]
I feel helpless, I've tried but it still can't save received/sent messages to local storage

**Comment by filippotoso** [comment]
This is where you have to load the messages from localStorage:
https://github.com/botman/web-widget/blob/master/src/chat/chat.tsx#L20

```js
var messages = localStorage.getItem("messages") 
messages = (null !== messages) ? messages : []; 
```

This is where you have to write the messages into localStorage:
https://github.com/botman/web-widget/blob/master/src/chat/botman.ts#L31

```js
localStorage.setItem("messages", messages);
```
