### ISSUE TITLE
What are the limitations on Botman's regex capabilities?

### ISSUE THREAD

**Issue by theo-1** [mpociot/botman#1390]
- BotMan Version: 2.7.4
- PHP Version: 7.4
- Messaging Service(s): Telegram
- Cache Driver: Redis

### Description:

The following (which correctly matches an alphanumeric sequence of characters with optional hyphen on regex101.com)

`$botman->hears('/item (\w+(-*\w+))', function($bot, $inv) { ... });`

fails to be recognized by Botman and hits my fallback response. There are quite a few other regex failures I've had in the past which I never bothered to report.

Do I need a Botman version bump or some other way to write the regex?

**Comment by filippotoso** [comment]
The matching is done here:

https://github.com/botman/botman/blob/2.0/src/Messages/Matcher.php#L45C13-L45C13

You can try to debug why you pattern isn't working extracting the processing logic and trying with your inputs that fails to match,
