### ISSUE TITLE
Need Laravel 11 Support 

### ISSUE THREAD

**Issue by iEgria** [mpociot/botman#1396]
Since Laravel 11 was released yesterday, this package requires compatibility with Laravel 11 in order to function properly.

**Comment by ianrothmann** [comment]
I made a fork here that seems to work fine in my Laravel 11 project. However, I cannot submit a pull request to Botman as there is an issue with orchestra/testbench, which is a dev dependency. It needs to be upgraded as well for the tests to pass.

https://github.com/ianrothmann/botman/tree/laravel11
