### ISSUE TITLE
Telegram Bot Driver Issue

### ISSUE THREAD

**Issue by downygg** [mpociot/botman#1398]
- BotMan Version: 2.8
- PHP Version: 8.2
- Messaging Service(s): Telegram 2.0
- Cache Driver: Redis

I deploy telegram bot with this package, It's run perfectly and fast response until a week. After a week, I got slow response on my bot. I don't know how its happened. Anyone same with this issue ? and how to fix it?

Thanks

**Comment by filippotoso** [comment]
If you haven't changed the code, you shoud search the problem elsewhere (i.e. in you own code, in the server, etc.).

Try profiling the application and see where the bottleneck is.

**Comment by downygg** [comment]
I use this code for handle incomming webhook
```
require(base_path('routes/botman.php'));
app('botman')->listen();
```

is it best practice for handle it?

**Comment by filippotoso** [comment]
This post describe how to setup a Telegram bot step by step.

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604
