### ISSUE TITLE
Write message in a chatbox user session

### ISSUE THREAD

**Issue by dimar7** [mpociot/botman#1401]
- BotMan Version: v2.8.1
- PHP Version: 7.4.12
- Messaging Service(s):
- Cache Driver:

### Description:
I want to write the message in the current user session of the chatbox, I pass the userId to the say command, but it doesn't work. It's a api end point that target http://localhost:8000/api/botman, I receive the message "Message sent successfully to user with ID: $userId" using Postman

```
use Illuminate\Http\Request;
use BotMan\BotMan\BotMan;
use Illuminate\Support\Facades\Log;

Route::post('/botman', function(Request $request) {
    try {
        // Extract the message and userId from the request
        $message = $request->input('message');
        $userId = $request->input('userId');

        // Retrieve the BotMan instance
        $botman = app('botman');

        // Reply to the user or session identified by the userId
        $botman->say($message, $userId);

        // Log success message
        Log::info("Message sent successfully to user with ID: $userId");

        return response()->json(['message' => 'Mensaje enviado con éxito ' . $userId]);
    } catch (\Exception $e) {
        // Log error message
        Log::error("Error sending message: " . $e->getMessage());

        // Return error response
        return response()->json(['error' => 'Error sending message'], 500);
    }
});
```
### Steps To Reproduce:

**Comment by filippotoso** [comment]
Which Messaging Service are you using?

**Comment by dimar7** [comment]
> 

> Which Messaging Service are you using?

Are you talking about the driver? In that case it's web driver initially, next it will be Facebook messenger driver.

**Comment by filippotoso** [comment]
Try using this example as starting point to make an instance working with the Web Driver:

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604

**Comment by dimar7** [comment]
How do I pass the message to the user id  or chat session?

**Comment by filippotoso** [comment]
Almost all BotMan drivers send messages in response to an HTTP request. That request contains all the information that BotMan needs to send the response, including the user id or chat session. So, to answer a user message you only need:

```php
$botman->hears('Hi', function (BotMan $bot) {
    $bot->reply('Hello!');
});
```

**Comment by dimar7** [comment]
Sorry, I think I may have misunderstood. I need to respond to a message from another server via a web service. What would I need to respond in a specific conversation?

**Comment by filippotoso** [comment]
Using the current version of the web widget you cannot send a message to the user outside an HTTP request initiated by the user. To implement an async functionality you could use a websocket server or some kind of pulling system.

With services like Telegram and Messenger you can do it as follows:

1. Instantiate the driver with the correct configuration
2. Build the payload accordingly to the service (i.e. check Messenger official documentation). The payload will include data such as the message, the session user ID, etc.
3. Call the sendPayload() method on the driver instance.

**Comment by dimar7** [comment]
Thank you, I was using WebDriver for testing. I will use Facebook as you say

**Comment by dimar7** [comment]
> 2\. Messenger official documentation

I have this code, but it'snot working:

Messenger official documentation

> Using the current version of the web widget you cannot send a message to the user outside an HTTP request initiated by the user. To implement an async functionality you could use a websocket server or some kind of pulling system.
> 
> With services like Telegram and Messenger you can do it as follows:
> 
> 1. Instantiate the driver with the correct configuration
> 2. Build the payload accordingly to the service (i.e. check Messenger official documentation). The payload will include data such as the message, the session user ID, etc.
> 3. Call the sendPayload() method on the driver instance.

I have this code, but it's not working: 

```
try {
    $botman = app('botman');
    $accessToken = '***';
    $recipientId = '***';
    $payload = [
        'access_token' => $accessToken,
        'recipient' => ['id' => $recipientId],
        'message' => ['text' => 'Hello, world!']
    ];
    $botman->sendPayload($payload);
    Log::info('Payload sent successfully.');
    return response()->json(['status' => 'success']);
} catch (\Exception $e) {
    Log::error('Error sending payload: ' . $e->getMessage());
    return response()->json(['status' => 'error', 'message' => $e->getMessage()], 500);
}
```
Laravel log doesn't show anything, only the successful sent message

**Comment by filippotoso** [comment]
You are not following the provided instructions.

1. You are not "instantiating the driver with the correct configuration", you are just creating an instance of the driver.

This is the driver you have to instantiate: https://github.com/botman/driver-facebook/blob/master/src/FacebookDriver.php

2. Build the payload accordingly to the service

Here you can find an example of payload: https://github.com/botman/driver-facebook/blob/master/src/FacebookDriver.php#L370

As you can see, and as per Messenger documentation, you are missing fields like messaging_type.

3. Call the sendPayload() method on the driver instance.

You are calling the sendPayload() method on BotMan not on the driver.

**Comment by dimar7** [comment]
using the driver instance, should it be something like this?:
           
```
    public function handle()
    {
        try {
            $botman = app('botman');
            $facebookDriver = $botman->getDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);
    
            if ($facebookDriver && $facebookDriver instanceof FacebookDriver) {
                $recipient = '1**';
                $message = 'hello world';
    
                $payload = [
                    'messaging_type' => 'RESPONSE',
                    'recipient' => [
                        'id' => $recipient
                    ],
                    'message' => [
                        'text' => $message
                    ]
                ];
    
                $facebookDriver->sendPayload($payload);
                Log::info('Payload sent successfully to recipient: ' . $recipient);
                
                return response()->json(['status' => 'success']);
            } else {
                Log::error('Failed to retrieve Facebook driver or driver is not an instance of FacebookDriver.');
                return response()->json(['status' => 'error', 'message' => 'Failed to retrieve Facebook driver.'], 500);
            }
        } catch (\Exception $e) {
            Log::error('Error sending payload: ' . $e->getMessage());
            return response()->json(['status' => 'error', 'message' => $e->getMessage()], 500);
```
        }
    }
api.php:

`Route::post('/botman', [BotManController::class, 'handle']);`

**Comment by dimar7** [comment]
> You are calling the sendPayload() method on BotMan not on the driver.

how can I achieve that? I'm new on PHP
