### ISSUE TITLE
Ubuntu Apache2 returns 408

### ISSUE THREAD

**Issue by niyazialpay** [mpociot/botman#1404]
- BotMan Version: Latest
- PHP Version: 8.3
- Messaging Service(s): Telegram
- Cache Driver: no

### Description:

I can't get response from bot on apache server, I can get response only with ngrok. But I want to get response without ngrok. Becouse ngrok is not secure for my project. Also ngrok changing webhook url every start.

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Where are you hosting your BotMan application?
Is it hosted locally?
If that's the case, how are you exposing your local web server to the Internet without using a solution like ngrok?

**Comment by niyazialpay** [comment]
Botman is installed on our VDS server, ngrok is unfortunately not a solution for us, we have to keep the data in-house, we cannot proxy through a 3rd party software. Ubuntu 22.04 operating system is installed on the server, Botman is served via Apache2 and Nginx, there is a public IP address and domain address.

**Comment by filippotoso** [comment]
Please follow these instructions to setup a Laravel instance with a working Telegram bot:

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604

If you still get an errror, it means the problem is on the Apache / Nginx / Networking side.

**Comment by niyazialpay** [comment]
I don't think there is a misconfiguration for apache or nginx, because apache and nginx installation and configuration don't require special processes, I just installed them directly and uploaded the files to the relevant directory. Can you specify if there is a special nginx or apache configuration for Botman? There is also no firewall protection or blocking on the server side

**Comment by filippotoso** [comment]
Please, follow the suggested instructions. If they work, it means the problem is in you code, otherwise is in the environment.

**Comment by niyazialpay** [comment]
Thank you, problem solved
