### ISSUE TITLE
Bot Commands Not Executing on First Attempt

### ISSUE THREAD

**Issue by emirhanerturkx** [mpociot/botman#1406]
- BotMan Version: Latest
- PHP Version:8.2
- Messaging Service(s): Telegram
- Cache Driver:Laravel Cache

### Description:
When a message comes from the bot, it doesn't process other commands from users. It works and responds if we write it a second time. For example, we send a message from the bot via cronjob, and the user wants to perform an action, like running the /start command. However, when they type /start, no response is given. The command works when typed for the second time.

### Steps To Reproduce:

**Comment by filippotoso** [comment]
Please follow these steps to setup a Telegram bot and verify if works correctly;

https://github.com/botman/botman/discussions/1308#discussioncomment-3008604

If it doesn't work it means there's something wrong in you stack (fireall, web server miss configuration, etc.) that prevents it from working correctly.

**Comment by emirhanerturkx** [comment]
> Please follow these steps to setup a Telegram bot and verify if works correctly;
> 
> [#1308 (comment)](https://github.com/botman/botman/discussions/1308#discussioncomment-3008604)
> 
> If it doesn't work it means there's something wrong in you stack (fireall, web server miss configuration, etc.) that prevents it from working correctly.

Yes, I read what you sent, but there is no problem with the way it works, it works the same as there. My bot works but sometimes I need to send the same command twice.

**Comment by downygg** [comment]
> > Please follow these steps to setup a Telegram bot and verify if works correctly;
> > [#1308 (comment)](https://github.com/botman/botman/discussions/1308#discussioncomment-3008604)
> > If it doesn't work it means there's something wrong in you stack (fireall, web server miss configuration, etc.) that prevents it from working correctly.
> 
> Yes, I read what you sent, but there is no problem with the way it works, it works the same as there. My bot works but sometimes I need to send the same command twice.

I have some problem, but I think this problem on Telegram Datacenter's is slow to send an update command from bot.

**Comment by jalexmelendez** [comment]
@filippotoso I love this library, it is extremely simple to build bots and does not force you to use LLMs or NLP like all the other chatbot libs or frameworks, how can I assist you to update this lib to be compatible with newer laravel versions? I updated the botman studio project (i have a fork in my profile) a while back, maybe we could push v2.5 with some upgrades? I really want this package to gain more traction and I think it deserves more attention and love by the community
