### ISSUE TITLE
Receive data back when use Botman->say

### ISSUE THREAD

**Issue by milad-jfr** [mpociot/botman#1407]
- BotMan Version: 2.8
- PHP Version: 8.2
- Messaging Service(s): web-telegram
- Cache Driver: laravelCache

Description:
User started a conversation from Webwiget and said 'Hello',
I sent 'Hello' to a Telegram user-id using Botman->say and Telegram user received it ,
now i want to get the Answer from Telegram user ( on existing conversation ) ,
something like when use Botman->ask , but it seems Ask not support send message to user-id ,

What can i do in this situation ? 
Thanks in advance

**Comment by filippotoso** [comment]
You need to implement such feature using a websocket server (recommended) or a push/pull http solution within the web widget itself.

**Comment by milad-jfr** [comment]
> You need to implement such feature using a websocket server (recommended) or a push/pull http solution within the web widget itself.

Thanks for your reply ,

is there any simpler solution to get this done ? 
for example get the data from Ask or something like that ?
or start a new conversation with telegram user and send back the conversation data to the top Level Conversation ? 
is it possible to transfer data between conversation's ?

**Comment by filippotoso** [comment]
I’m sorry but the proposed solutions are the only I can think of. It’s a problem of the way the Http protocol works, not Botman.
