### ISSUE TITLE
botman is not responding after adding php Ml

### ISSUE THREAD

**Issue by panashe78** [mpociot/botman#1413]
<?php
namespace App\Http\Controllers;

use BotMan\BotMan\BotMan;
use Illuminate\Http\Request;
use Phpml\Classification\NaiveBayes;
use Phpml\Dataset\ArrayDataset;

class BotManController extends Controller
{
    protected $classifier;

    public function __construct()
    {
        $this->classifier = new NaiveBayes();
        $this->trainClassifier();
    }

    public function handle()
    {
        $botman = app('botman');

        $botman->hears('{message}', function($botman, $message) {
            $response = $this->classifyMessage($message);
            $botman->reply($response);
        });

        $botman->listen();
    }

    protected function trainClassifier()
    {
        // Training data
        $samples = [
            ['hi'],
            ['hello'],
            ['bye'],
            ['thank you'],
            ['how are you?'],
        ];

        $labels = ['greeting', 'greeting', 'farewell', 'gratitude', 'greeting'];

        // Create dataset and train
        $dataset = new ArrayDataset($samples, $labels);
        $this->classifier->train($dataset->getSamples(), $dataset->getTargets());
    }

    protected function classifyMessage($message)
    {
        // Tokenize input
        $predictedClass = $this->classifier->predict([tokenize($message)])[0];

        // Response mapping
        $responses = [
            'greeting' => 'Hello! How can I help you today?',
            'farewell' => 'Goodbye! Have a great day!',
            'gratitude' => 'You’re welcome! If you need anything else, just ask.',
        ];

        return $responses[$predictedClass] ?? "I'm not sure how to respond to that.";
    }
}

**Comment by filippotoso** [comment]
Please include the required information when opening an issue.
