### ISSUE TITLE
hears only to @

### ISSUE THREAD

**Issue by Beertie** [mpociot/botman#146]
Can i make hear only response when u 1e tag the bot ?

```
$botman->hears('@bot test', function (BotMan $bot) {
            $bot->reply("Test");
 });
```

So now is i say test nothing happens but is i say @bot test then he response?

**Comment by mpociot** [comment]
Which driver do you use?

**Comment by Beertie** [comment]
Slack

**Comment by mpociot** [comment]
No that's not possible right now. 

This will only work with the Slack RTM driver / event API. 
The problem right now is, that Slack sends a message like this, once the bot gets mentioned with an `@mybot foo` command:

`<@U11QAMS0N> foo`

Where `U11QAMS0N` is the bot's user ID, which we currently do not have. In the meantime, you can gather the bot user ID yourself and modify your `hears` command to something like:

```php
$botman->hears('<@YOUR_BOT_USER_ID> test', ...
```

**Comment by jtreminio** [comment]
@mpociot I was looking for this as well. Your explanation is great, would suggest you include it in documentation for others!

**Comment by Jeroen-G** [comment]
This is how I've solved it:

```php
$prefix = '';
if ($botman->getDriver()->getName() === SlackDriver::DRIVER_NAME) {
    $prefix = '<@YOUR_BOT_USER_ID> ';
}

$botman->hears($prefix.'hi', function ($bot) {
    $bot->reply('Hello!');
});
```

It is not the most clean solution, so I am wondering if I can PR it to a Botman core function somehow.
