### ISSUE TITLE
Add Laravel example to readme.md

### ISSUE THREAD

**Issue by jerairrest** [mpociot/botman#15]
When I get a chance I'll update the readme.md with a working implementation on how to get SlackBot up and running from a Laravel 5 app.

**Comment by darkgoldblade01** [comment]
If you need any code (like what I have now from the #14 issue), let me know.

**Comment by mpociot** [comment]
I still want to provide a separate repository with a Laravel example application to get you started. But I haven't found the time yet.

If you find some things in the documentation that could be improved, feel free to send pull requests.

**Comment by darkgoldblade01** [comment]
Quick question, I see that the repo does support buttons, does it accept button requests too, or just send them?

**Comment by mpociot** [comment]
What do you mean by "Button requests"?
It allows sending (and responding) to [Slack message buttons](https://api.slack.com/docs/message-buttons).

**Comment by darkgoldblade01** [comment]
That's what I meant, so in the `value` do you put the same thing that's in the `->hears()` section?

**Comment by darkgoldblade01** [comment]
So from my code from yesterday, something like this, would it work?

        public function handleBotRequest(Request $request)
        {
            $payload = $request->json();
            if ($payload->get('type') === 'url_verification') {
                return $payload->get('challenge');
            }
    
            $team = Company::find(1);
    
            $slackBot = app('slackbot');
    
            $slackBot->initialize($team->slack_info->bot->bot_access_token);
            $slackBot->hears('ping', function (SlackBot $bot) {
                $bot->reply(Question::create('PONG')->addButton(Button::create('Ping')->value('ping'))->callbackId('PINGPONG'));
            });
            $slackBot->listen();
        }

**Comment by mpociot** [comment]
Yes exactly, that should work.

Here is an example from one of my bots:

```php
$question = Question::create('Do you need a database?')
            ->fallback('Unable to create a new database')
            ->callbackId('create_database')
            ->addButtons([
                Button::create('Yes')->value('yes'),
                Button::create('No')->value('no'),
            ]);

$bot->reply($question, function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                $decision = $answer->getValue();
                if ($decision === 'yes') {}
            }
});
```

Please note that the bot `reply` method no longer exists. It got renamed to `respond`

**Comment by darkgoldblade01** [comment]
Ah, okay! Also, I scrapped what I had created and started a repo to make it easy, I can transfer if you want and I also have a dev site setup on a forge server so I could play with it more.

https://github.com/darkgoldblade01/slackbot-laravel

**Comment by darkgoldblade01** [comment]
How are you using `$bot->reply($question, function())` when the second argument is supposed to be an array?

**Comment by mpociot** [comment]
Ah - this was taken from a Conversation class and I just changed the syntax from `$this->ask` (which only accepts two arguments) to `$bot->reply`

So this should be inside of a conversation too, since you need to get the users input.

**Comment by darkgoldblade01** [comment]
Okay, I am hoping to compile the examples we are coming up with into the repo I created for the laravel example.

**Comment by webmestre-comeul** [comment]
Btw, thanks @darkgoldblade01 for that repo, it'll come handy, I did try to follow @mpociot's blog post on it, but somehow I failed miserably ;-) I hope yours will get me through it!

**Comment by mpociot** [comment]
Sorry for that - I wrote the blog post while writing the library, which has now a more stable API.
I'll update the blogpost soon :)

**Comment by webmestre-comeul** [comment]
No worries about that, that'll just teach me to blindly follow step by step :P

**Comment by webmestre-comeul** [comment]
Well, thank you guys, I finally re-read this issue correctly (And #14) and got my bot working just fine on my part! Now the fun part begins...

**Comment by jerairrest** [comment]
If you encounter any issues that could be shared let us know! :-)

**Comment by webmestre-comeul** [comment]
Honestly, at this moment, the only issue I encountered was probably due to the fact that I was trying to follow the blog post, the readme and two issues at the same time ;-)

**Comment by mpociot** [comment]
I'll close this issue for now. With the new version of this library, I will create a demo repository showing off all supported messaging platforms.
