### ISSUE TITLE
Chaining questions in conversation

### ISSUE THREAD

**Issue by kre8or69** [mpociot/botman#152]
Not sure if i'm doing something wrong but wanted to check if there is a way to chain a question inside a question.

Wanted to have 1 after the other but it seems to stop after the first ask() (as in an ask inside and ask doesn't seem to work).

Is there a way to do that?

**Comment by mpociot** [comment]
Can you show me some code?
Make sure the second ask is on the first ask closure. 
Which cache driver do you use?

**Comment by kre8or69** [comment]
Ohh wow seems like i may have jumped the gun! Adding the storage driver and moving over the events API method seems to work as expected! 

Originally i was using the "listen" method with php react for RTM conversations and I moved the the Events API method and had the same problem. Adding the storage driver was the final thing i needed to do :)

Love the package! sorry for bugging you!!!
