### ISSUE TITLE
Cache key character with Symfony cache

### ISSUE THREAD

**Issue by gromez** [mpociot/botman#153]
Hello,

I'm using botman in a composer project, and I had to include Symfony cache in order to do conversations.

There is a small issue with the conversation identifier : https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Message.php#L69

Error: `Cache key "conversation:279775023-279775023" contains reserved characters {}()/\@:`
Maybe replace `:` with another character.

Thank you

**Comment by mpociot** [comment]
Fixed in dev-master
