### ISSUE TITLE
botman->say()

### ISSUE THREAD

**Issue by jacquesvn** [mpociot/botman#155]
Hi There,

Firstly, awesome library, what more can be said.

I was wondering if someone has a working example of botman->say, I am new to all of this and try as I may I can not originate messages to either skype or telegram, my own ignorance I am sure. (Got everything else working, hears, replies, conversations).

What I am trying to do is originate a message to a user, using laravel, simple get route for testing as follows:

    public function testOriginate()
    {
    	\\ log at this point shows I get here
    	$botman = app('botman');
		$botman->say('Hello There I have some interesting news','29:xxx',BotFrameworkDriver::class);
    }

switching to telegram driver and user id has no effect.
No errors in the log etc. Just seems to disappear into a dark abyss. 

Would appreciate a push down the rabbit hole.

Thanks in advance.

**Comment by mpociot** [comment]
Hello,

I guess you're using the wrong User-IDs. Can you tell me how you obtain them?

**Comment by jacquesvn** [comment]
Hi Marcel,

Hope you are well.

I get the user id from $bot->getMessage()->getUser() in a separate conversation, this is then saved to the DB. I have compared the saved value to a dump of $bot->getMessage()->getPayload() and it is the same value.

Apart from initializing botman using  $botman = app('botman'); and issuing the $botman->say command should I be doing anything else?

Thanks again.

**Comment by mpociot** [comment]
Hey,

I just added a new method to the `master` branch of this package that allows you to get generic user information.
The problem is - some drivers use `getUser()` some `getChannel()` for the ID.

Please use: `$bot->getUser()->getId()`

**Comment by jacquesvn** [comment]
Hi Marcel, 

Thanks again for your assistance.

Ok, so I implemented the change - but the same problem exists.

I get $frameWork_user_id = $bot->getUser()->getId(); this I save to the DB, I also log it the logfile at the point of getting it - to make double sure. 

Retrieving from the DB or hard coding it in the following function yields no results.

public function testOriginate()
{
	\\ log at this point shows I get here
	$botman = app('botman');
	$botman->say('Hello There I have some interesting news','29:xxx',BotFrameworkDriver::class);
}

What I have now tried as well now is to create a new project on a different server from botman-laravel-starter (My original project where used composer to install botman was running laravel 5.2 & php 5.5x so just in case that was an issue) 

**Using Telegram Only**
I have tested the conversations, simple hello and test functions all working.

I get this in the hears hello bit in the BotmanController:
	$frameWork_user_id = $bot->getUser()->getId();
        \Log::info('$frameWork_user_id: ' . $frameWork_user_id);

Then I added the following route in web.php

        Route::get('/testoriginate', 'BotManController@testOriginate');

With the corresponding function:

  public function testOriginate()
    {
    	$botman = app('botman');
        $telegram_id = "XXX"; //double triple quadruple checked :-)
	$botman->say('I have some interesting news',$telegram_id,TelegramDriver::class);
	return "Sent to $telegram_id"; //I see this in out put.

    }

And nada, no message. 

If I dump the $botman->say this is the output (not sure if it will help but just in case)


BotMan {#112 ▼
  +payload: null
  #event: null
  #message: Message {#115 ▼
    #message: ""
    #user: ""
    #channel: ""
    #payload: null
    #extras: []
  }
  #driverName: null
  #currentConversationData: null
  #listenTo: array:2 [▼
    0 => Command {#113 ▼
      #pattern: "test"
      #callback: Closure {#110 ▼
        class: "App\Providers\RouteServiceProvider"
        this: RouteServiceProvider {#84 …}
        parameters: {▶}
        file: "...removed.../routes/botman.php"
        line: "6 to 8"
      }
      #in: null
      #driver: null
      #channel: null
      #middleware: []
    }
    1 => Command {#117 ▼
      #pattern: "Start conversation"
      #callback: "App\Http\Controllers\BotManController@startConversation"
      #in: null
      #driver: null
      #channel: null
      #middleware: []
    }
  ]
  #fallbackMessage: null
  #groupAttributes: []
  #matches: []
  #driver: NullDriver {#114 ▼
    #http: Curl {#111}
    #config: Collection {#116 ▶}
  }
  #config: array:1 [▼
    "telegram_token" => "...removed..."
  ]
  #middleware: []
  -cache: LaravelCache {#109}
  #storage: FileStorage {#102 ▼
    -path: "...removed.../storage/botman"
  }
  #loadedConversation: false
}

**Comment by jacquesvn** [comment]
Hi Marcel,

Hope you are well.

Ok, with very little knowledge of all of this on my side (So please excuse any obvious mistakes on my part) I have managed to track it down to this:

For some reason in my setup I need to pass the full name spaced path of the driver to the say command, and then this line in DriverManager.php Removes the word Driver from it

$name = rtrim(basename(str_replace('\\', '/', $name)), 'Driver'); 

so I temporarily tested by replacing that with $name = $name::DRIVER_NAME;

ELSE the comparison if ($driver->getName() === $name)  fails in the loop below. 

This then works for telegram and skype (Although with skype I get an unkown conversation id on the Microsoft side, will look at that next, at a quick glance seems one has to create a new conversation object or something for skype)

Most likely something on my side I know, but if you have any advice that I can look at for either the driver issue or skype it will be appreciated.

Thanks

**Comment by mpociot** [comment]
Could you please test this again with the latest stable version (1.4)?

**Comment by caglarvarol** [comment]
i can't seem to originate a message to skype using the same method with @jacquesvn (i am using 1.4).

**Comment by jacquesvn** [comment]
Hi Marcel,

Apologies I have been away.

I have done a quick test and confirm Skype still does not work using the latest version. 

From the last I looked at it, the problem appeared to be that Skype requires a new conversation "their terminology" to be initiated before one can send the message. But I did not get much further into this. 

I found a work around for my one use case in that I remembered the last chat I had with the user and then when the time came I simply replied to that.

As soon as I have a moment I will go through the Microsoft docs vs the origination bit of code on your end and see what I can figure out, I'll then report back to you if no progress has been made of course.

Thanks again for your assistance.

Jacques

**Comment by thedotedge** [comment]
Please try to dump serviceUrl from message received from the user and pass it in parameters when you originate as in #187.

**Comment by jacquesvn** [comment]
Just some quick feedback, have tested with latest version and also using the serviceUrl as suggested. Reults are the same.

**Comment by caglarvarol** [comment]
this worked for me:

`$botman->say('Hello!', '29:1Uzn3EivEkf9dTOTutalCpp07MX3aqBCwRvtiKfOFJOc', BotFrameworkDriver::class, ['serviceUrl'=>'https://smba.trafficmanager.net/apis/']);`

**Comment by vdnt** [comment]
Seems like, does not work for me either. Using BotFramework driver.

```
Route::get('/notify', 'NotificationController@handle');

class NotificationController extends BaseController
{
		public function handle()
		{
	            print 'Notifications!';
    		    $botman = app('botman');
		    $botman->say('Notification!', '29:......', BotFrameworkDriver::class, ['serviceUrl'=>'https://smba.trafficmanager.net/apis/']);
		}
}
```

**Comment by vdnt** [comment]
So the issue in my case was missing:
```
use Mpociot\Botman\Drivers\BotFrameworkDriver;
```

**Comment by jacquesvn** [comment]
I can confirm that the combination of adding:

use Mpociot\Botman\Drivers\BotFrameworkDriver;

and using 

['serviceUrl'=>'https://smba.trafficmanager.net/apis/'] in the say method 

Did the trick.

**Comment by holtkamp** [comment]
Regarding to https://github.com/botman/docs/pull/72, also encountered this. 

Isn't there a way for the BotFrameworkDriver to "detect" a "say" message and append this information by itself?

`['serviceUrl'=>'https://smba.trafficmanager.net/apis/']`

The current approach causes driver-specific logic to end up in userland code, which I would like to prevent:

```php
private function getAdditionalBotManDriverParameters(string $botManDriver): array
    {
        return $botManDriver === BotFrameworkDriver::DRIVER_NAME
            ? ['serviceUrl' => 'https://smba.trafficmanager.net/apis/']
            : [];
    }
```

**Comment by sugoireed** [comment]
For anyone having this challenge make sure that you have imported the Specific Driver you want to use i.e

use BotMan\Drivers\Facebook\FacebookDriver;

Or use the full qualified name on the method

        $botman->say($message,$chatId, \BotMan\Drivers\Facebook\FacebookDriver::class);

**Comment by CaptainChainsaw** [comment]
Is there a way to send a message to a user/group using `$conversation` like so?

    $conversation->say('Announcement: ',-123456789, \BotMan\Drivers\Telegram\TelegramDriver::class);

The code in context (which doesn't send the message):

		$bot->ask('What is your announcement?', function($answer, $conversation){
		   announcement::create([
			'announcement' => $answer,
			'username' => $conversation->getBot()->getUser()->getUsername(),
			'user_id' => $conversation->getBot()->getUser()->getId()	
		   ]);
		 $conversation->say('Announcement: ',-123456789, \BotMan\Drivers\Telegram\TelegramDriver::class);
		}, ['reply_markup' => json_encode(['force_reply' => true])]);

**Comment by CaptainChainsaw** [comment]
> Is there a way to send a message to a user/group using `$conversation` like so?
> 
> ```
> $conversation->say('Announcement: ',-123456789, \BotMan\Drivers\Telegram\TelegramDriver::class);
> ```
> 
> The code in context (which doesn't send the message):
> 
> ```
> 	$bot->ask('What is your announcement?', function($answer, $conversation){
> 	   announcement::create([
> 		'announcement' => $answer,
> 		'username' => $conversation->getBot()->getUser()->getUsername(),
> 		'user_id' => $conversation->getBot()->getUser()->getId()	
> 	   ]);
> 	 $conversation->say('Announcement: ',-123456789, \BotMan\Drivers\Telegram\TelegramDriver::class);
> 	}, ['reply_markup' => json_encode(['force_reply' => true])]);
> ```

Not sure if this is the best way to do this but I got it working by ammending the say method in the Conversation class.

    /**
     * @param string|\BotMan\BotMan\Messages\Outgoing\Question $message
     * @param array $additionalParameters
     * @return $this
     */
    public function say($message, $recipients=[], $additionalParameters = [])
    {
        if(!empty($recipients)){
            $this->bot->say($message, $recipients, $additionalParameters);
        } else {
            $this->bot->reply($message, $additionalParameters);
        }

        return $this;
    }
