### ISSUE TITLE
Start Conversation without hears

### ISSUE THREAD

**Issue by darkgoldblade01** [mpociot/botman#166]
Is there a way to start a conversation with `->hears()`?

We are wanting to have our bot ask a question every morning at a certain time, how could we go about that with a conversation?

**Comment by christophrumpel** [comment]
Couldn't you ask a question with some answer options and these answers trigger a new conv?

**Comment by darkgoldblade01** [comment]
```
$botman = BotManFactory::create($config);

$botman->ask(); // This won't work, ask needs to be in a convo

$botman->reply(Question::create('Question')); // I can't see any params for reply that will accept a response back from slack

$botman->say(Question::create('Question')); // Same, don't see any params for responses

$botman->startConversation(new Convo); // This handles taking responses back and everything, but I need to start it to specific people at a specific time every day

```

**Comment by mpociot** [comment]
Why do you need `hears` for that?
This sounds like you want to originate a conversation.

There is already the `say` method, as you mentioned and I already have a working version of originating conversations in the (wait for it) `originate-conversations` branch 🎉 

Here's the code for it: https://github.com/mpociot/botman/compare/originate-conversations?expand=1

So it basically allows you to write this:

`$botman->startConversation(new Convo, 'user-id', SlackDriver::class);`

Is this what you need? It works by simulating an incoming request and then "responding" to it.
So just like the `say` method, you need a user-id in advance.

**Comment by darkgoldblade01** [comment]
So here is my code currently:

```
public static function sendMessage() {
        $config = [
            'slack_token' => xxx,
        ];

        $botman = BotManFactory::create($config);

        $botman->startConversation(new Convo, 'USER ID');
}
```

would that be correct?

**Comment by darkgoldblade01** [comment]
@mpociot @christophrumpel any ideas on the above?

**Comment by mpociot** [comment]
You're close :)
You need to pass the driver to the startConversation method too. 
Just pass the driver class as a third parameter.

**Comment by christophrumpel** [comment]
@darkgoldblade01 So what @mpociot was saying is:

When you checkout the link you will see some changes in the code that would make it possible to start a conversation without the `listen`.

So what you need to do to test it is:

1. Make the changes to the BotMan library like shown here `originate-conversations`
2. Make a conversation and let the bot say something (like you would normally do with the listen)
3. Start the conversation like `$botman->startConversation(new Convo, 'user-id', SlackDriver::class);`

I am not familiar with the Slack stuff, I would say to start the conversation you then only need a `->say('..')` inside the conversation.

Haven't tried it yet, but this is how I would test it. Correct me if I am wrong @mpociot .

**Comment by darkgoldblade01** [comment]
Doing the following:

```public static function sendMessage() {
        $config = [
            'slack_token' => xxx,
        ];

        $botman = BotManFactory::create($config);

        $botman->startConversation(new Convo, 'U043B5E5L', SlackDriver::class); //This is actually my user id currently, don't mind sharing it :P
}```

In my convo I have:

```class Convo extends Conversation
{

    public function ask()
    {
        $this->ask(Question::create("Hello World"), function(Answer $answer) {
            \Log::debug($answer->getText());
        });
    }

    /**
     * @return mixed
     */
    public function run()
    {
        $this->ask();
    }
}```

Nothing is being logged, and the function sometimes returns NULL, and sometimes just kills `tinker`.

**Comment by darkgoldblade01** [comment]
I found the next problem, doing this actually makes it so it doesn't properly handle returns. So, my file with the slackbot listener in it, should look like the following correct?

```
class SlackBotController extends Controller
{
    /**
     * @param Request $request
     */
    public function handleBotRequest(Request $request)
    {
        $payload = $request->json();
        if ($payload->get('type') === 'url_verification') {
            return response()->json([$payload->get('challenge')]);
        }

        $team = Company::where('slack_team_id', $payload->get('team_id'))->first();

        $config = [
            'slack_token' => $team->slack_info['bot']['bot_access_token'],
        ];

        $botman = BotManFactory::create($config);

        \Log::debug($request->get('event')['user']);

        if (!$botman->isBot()) {

            $botman->startConversation(new Convo, 'U043B5E5L', SlackDriver::class);
            
            $botman->listen();
        } else {
            return response()->json(['status' => 'error']);
        }
    }

    /**
     * @param $user
     * @return bool
     */
    private function checkUser($user)
    {
        $u = SlackUser::where('slack_user_id', $user)->first();
        if ($u) {
            return $u;
        } else {
            return false;
        }
    }
}
```

**Comment by mpociot** [comment]
I'm currently not in front of my MacBook, just on the phone. So here's a brief reply:

The startConversation ONLY works in two situations:

Either inside a `hears` closure - which then requires a call to `listen` OR outside of the whole hears / listen structure. 
If you want to manually send out messages to your users that start a conversation- for example in a CEO job - use the manual `startConversation` approach. 

This would work just as you mentioned. There is no `listen` call involved. 

```php
$botman = app('botman');

$botman->startConversation(nee Convo(), '12345678', SlackDriver::class);

```

That's it. 

If you want to use startConversation when reacting to a command, you need to use the `hears` closure. 

I hope that cleared things up a bit.

**Comment by darkgoldblade01** [comment]
But then the problem is when they respond, I am using the event structure, does that start convo go under the endpoint for slack? I am using Laravel, so I have a controller for Slack called SlackBotController, under there a function called handleBotRequest. That is where I have the url_vertification, like above, and the listen. I attempted the convo, and it sends a message, but when I respond, it doesn't work, and doesn't continue the convo.

**Comment by mpociot** [comment]
If the conversations don't continue after you reply to them, please make sure that your array driver is *not* `array`. You need a persistent cache in order for this to work.

**Comment by darkgoldblade01** [comment]
@mpociot so using laravel, what cache driver should I use?

**Comment by mpociot** [comment]
I just merged the feature into master. Maybe you can give it a shot again. The `originate-conversation` branch was many commits behind master.

**Comment by mpociot** [comment]
Have you tried this again?

**Comment by jeffer8a** [comment]
@mpociot I'm using slack... this is working for me:

`$botman->say('some text again', '#jeff-tests');`

But when I try the hear() method like this:

`$botman->hears('hi', function (BotMan $bot) {
            $bot->reply("Tell me more!");
        }, '#jeff-tests');`

It's not working. (with or without the last $in param). What do you think ???

**Comment by mpociot** [comment]
I'm missing some information to help you out. 

How do you implement BotMan?
Is the slack webhook setup correctly or are you using the RTM API?
Do you have a $botman->listen

**Comment by TondaRuzicka** [comment]
Hi,

I know it's not directly related, but what I'm trying to achieve is to run a hears command at certain time.. So I need it to be triggered without messaging the bot (slack RTM API).

Can you help nudge me in the right direction please?

Inside of the loop:

`if (!(date("Hi") > "2230" || date("Hi") < "0100")) {
	$botman->say('Between 22:30 and 01:00', '#bot-testing');
} else {
	$botman->say('Outside 22:30 and 01:00', '#bot-testing');
}`

It gets triggered only once. Any ideas?

**Comment by mpociot** [comment]
@TondaRuzicka You should do that outside of the loop and simply place it inside a cronjob.

**Comment by TondaRuzicka** [comment]
Thanks for the quick reply. Does $botman->say() support running a function inside like this?

> $botman->say(function($bot) {
> 	$bot->reply("exit - breaks my neck");
> 	$bot->reply("reload - brings to live fresh me");
> 	$bot->reply("help - prints this list");	
> }, '#bot-testing', SlackDriver::class);

**Comment by mpociot** [comment]
No, the `say` method instantly sends the response. So in your case you would need to call `say` three times.

**Comment by jeffer8a** [comment]
This is the method in the controller 

`public function handle()
    {
        $botman = app('botman');

        $botman->hears('hi', function (BotMan $bot) {
            $bot->reply("Tell me more!");
        }, '#jeff-tests');
        //$botman->say('some text', '#jeff-tests');
    }`

I'm using the slack webhook. if I uncomment `$botman->say('some text again', '#jeff-tests');` I receive "some text" in slack. If I type anything in salack I get this request

`[2017-02-16 00:11:00] local.INFO: array (
  'token' => 'the-token',
  'team_id' => 'the-team-id',
  'team_domain' => 'the-domain',
  'service_id' => '888888888888',
  'channel_id' => 'the-channel-id',
  'channel_name' => 'jeff-tests',
  'timestamp' => '8888888888888',
  'user_id' => 'USLACKBOT',
  'user_name' => 'slackbot',
  'text' => 'some text again',
  'bot_id' => 'the-bot-id',
  'bot_name' => 'bot',
)  `

**Comment by mpociot** [comment]
It seems like you are missing the `$botman->listen();` call.

Also, please remove the `#jeff-tests` parameter - I think it will only work with channel id's right now.

**Comment by deeprajsinha** [comment]
i want a demo message ...means without typing any thing it has to say like this first time when i open the botman app....
" Hi!
Welcome to the BotMan documentation! 🙂
Most of the code samples and snippets throughout the documentation work in this widget - feel free to give it a try!"

How to do this any idea for which botman reply first message without hear();

**Comment by mpociot** [comment]
You can start conversations by originating them to a known user ID. See https://botman.io/2.0/conversations#originating-conversations

**Comment by teebazz** [comment]
please how can i hear inbetween and ongoing conversation???
