### ISSUE TITLE
Feature request: Viber support

### ISSUE THREAD

**Issue by Bogdaan** [mpociot/botman#167]
Hi, someone already implement driver for Viber?
Current documentation (REST api): https://developers.viber.com/api/rest-bot-api/index.html

**Comment by mpociot** [comment]
You can already extend BotMan with custom drivers. I'll document the steps necessary.

**Comment by kinoute** [comment]
I'm interested by the custom drivers documentation as well, to use botman with Twitter.

**Comment by mpociot** [comment]
Added the documentation: http://botman.io/extending-botman

**Comment by matrunchyk** [comment]
@Bogdaan  Would be very grateful if you would share the driver with the community! :)

**Comment by Bogdaan** [comment]
@matrunchyk hi, i recently implement viber support in this lib - https://github.com/Bogdaan/viber-bot-php

**Comment by yarkm13** [comment]
https://github.com/TheArdent/botman-viber-driver
