### ISSUE TITLE
Old-style CURL usage

### ISSUE THREAD

**Issue by Bogdaan** [mpociot/botman#168]
Decouple package from HTTP implementation.

The problem:
https://github.com/mpociot/botman/blob/fac769ad4ad21185d19f46bc493951ca01050884/src/Mpociot/BotMan/Http/Curl.php

- unable to change timeouts (secure option!)
- unable to secure requests (CURLOPT_SSL_VERIFYPEER)
- unable to debug / mock test

See:
http://httplug.io/
https://github.com/php-http/httplug

**Comment by Bogdaan** [comment]
link #126

**Comment by mpociot** [comment]
Thanks for the suggestion. I already wanted to implement Guzzle instead of the "old school" CURL implementation. Sadly this is not easily possible, because of the serialization of the BotMan class, which is needed for conversations and queueing support (similar to issue #156).

**Comment by Bogdaan** [comment]
Hm, but **call_user_func** is bad design, unsecure solution.

**Comment by mpociot** [comment]
What has Guzzle / CURL to do with `call_user_func`?

**Comment by Bogdaan** [comment]
Sory, yes **call_user_funct + serialize** - is separete story
