### ISSUE TITLE
Hear other data types (Image, Location , Audio)

### ISSUE THREAD

**Issue by kmarima** [mpociot/botman#169]
Not sure if this already exists but i want to listen for messages that are not text.

**Comment by mpociot** [comment]
Which driver are you talking about?

**Comment by kmarima** [comment]
Facebook and/or Telegram Driver. let me see if i can figure this out

**Comment by kmarima** [comment]
Here is what I am trying to achieve 

I want the user to send an image and a location as as part of a Conversation.. 
is this possible ??

**Comment by kmarima** [comment]
@mpociot  here is how botpress(nodejs) does it with the "type" parameter ... not sure how it would look in conversations though

`bp.hear({ type: 'postback', text: 'GETTING_STARTED' }, (event, next) => {
  bp.messenger.sendText(event.user.id, 'Hello, human!')
})`

**Comment by mpociot** [comment]
Closing this, as I'm working on it in issue #215
