### ISSUE TITLE
Error handling problem

### ISSUE THREAD

**Issue by Bogdaan** [mpociot/botman#173]
See:
https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L349

And driver-specific code (for example TelegramDriver):
https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Drivers/TelegramDriver.php#L205

We lose:
- alse api errors
- all transport (http/soocket) errors
- all driver specific api-responce

**Comment by Bogdaan** [comment]
Posible solution: 
1. add exceptions for each api error
2. remove this https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L351
3. return new object (driver-specific responce + BotMan interface)

**Comment by mpociot** [comment]
Would you be open to a pull request for this?

**Comment by mpociot** [comment]
Will be fixed / handled differently with #338 in place
