### ISSUE TITLE
Using botman on laravel 5.4

### ISSUE THREAD

**Issue by alejandrofloresm** [mpociot/botman#177]
I'm trying to use botman on laravel 5.4 but it appears that there's a dependency error, since laravel requires:
`mpociot/botman 1.3.0 requires symfony/http-foundation 2.8.*|3.0.*|3.1.*`
While Laravel 5.4 requires:
`symfony/http-foundation 3.2.*`

Any ideas on how to bypass that requirement?

**Comment by mpociot** [comment]
Yes, you need to use the 'dev-master' version of BotMan. I have not tagged the new version yet!

**Comment by alejandrofloresm** [comment]
Just in case someone gets here, install botman as:
`composer require mpociot/botman:dev-master`
👍 
Thanks @mpociot great work!
