### ISSUE TITLE
Facebook List Template details missing

### ISSUE THREAD

**Issue by christophrumpel** [mpociot/botman#178]
Hey @ngfw,

just came across the FB template  that you helped integrating. Thx for that!
I noticed two things are missing:

**1.) Liste Template Style**

There are two list template styles available with FB. One is with a cover image item and one without. FB uses the `top_element_style` property to distinguish. What I've seen so far in BotMan is that it is currently not available to select the style. Just one of them is used right now.

**2.) The Botman Facebook ElementButton does not support postbacks**

Currently it is not possible to use Postback buttons within templates, just button with external URLs.

https://developers.facebook.com/docs/messenger-platform/send-api-reference/list-template

It would be great if you could add them too. If you can't just let me know, then I will try to take care of that. Thx and cheers

**Comment by christophrumpel** [comment]
**3.) Template in question**

Correct me @mpociot if I am wrong but currently it is not able to use any templates with the `ask` method inside a conversation. So when I use a template a need a new `listener` to react to the answer. It would be better if it was possible to use it with the ask method so I do not need a new listeners and directly react to the answer in the conversation.

**Comment by mpociot** [comment]
A `Template` object should also be possible within the `ask` method. It just passes the given message/question/string to the "reply" method.

**Comment by christophrumpel** [comment]
Ok you're right it is possible give the `ask` method a template. But wouldn't it be more convenient do that with a question object?

And because of "2.)" I cannot use the template with the `ask` method because only URL buttons are possible to be added right now. No, post back buttons which I would need to get the answer inside the callback.

So I would say "1.)" and "2.)" would be important. "3.)" is a matter of style and how you would like the api to be. But I could see that adding it to the Question object could be confusing because this is just for Facebook. But then I guess it would make sense to add "text" to the template object which is the Question text und could be optional.

**Comment by christophrumpel** [comment]
Sry this is getting really long with too much info but to complete:

Right now it is also not able to make a button template, because the button template doesn't need elements, but "buttons".

**Comment by christophrumpel** [comment]
I am almost finished with a PR that adds more features. Will push it today or tomorrow just to let you guys know

**Comment by mpociot** [comment]
@christophrumpel I'll close this issue, since you provided a PR for this.
