### ISSUE TITLE
PSR-6 cache adapter with (at least) BotFramework

### ISSUE THREAD

**Issue by thedotedge** [mpociot/botman#191]
When using https://github.com/php-cache/redis-adapter via newly introduced `Psr6Cache` the following problem is triggered:
```
Invalid key: "conversation-29:160NysSVYcvoosHxDgqTzepm0A6sSUDje5CbXVE84UZw-29:160NysSVYcvoosHxDgqTzepm0A6sSUDje5CbXVE84UZw". The key contains one or more characters reserved for future extension: {}()/\@:
```

@Art4 @mpociot would it be an option to use sha1(key) instead?

**Comment by Art4** [comment]
Yes, that would be an option.

I was thinking about removing or replacing the reserved characters, but that could lead to key collisions (`foo:bar` and `foobar` would result in the same key).
We can not be sure what keys would be given, so using a hash would be the safest way.

**Comment by mpociot** [comment]
Fixed :)
