### ISSUE TITLE
no reply in conversation 

### ISSUE THREAD

**Issue by hackertron** [mpociot/botman#192]
First of all thanks for Botman :100:  . It's great !!

I am still learning it . I am stumbled at a part when i initiate a conversation after getting answer from user there is no reply back to user . 

what i am trying to do is  : when user type " recommendation "  ask the genre and reply back ok got it , then next step 

code 

index.php 

`$botman->hears('recommend ', function(Botman $bot) {
	 $bot->startConversation(new recommendation);
});`

recommendation.php 
`<?php

require_once(dirname(__FILE__) . '/vendor/autoload.php');
use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotMan;
use Mpociot\BotMan\Conversation;
use Mpociot\BotMan\Answer;

class recommendation extends Conversation
{
    protected $genre;

    public function askgenre()
    {
        $this->ask('tell me genre?', function(Answer $answer) {
            // Save genre for next question
            $this->genre = $answer->getText();

            $this->say('Got it. I will search based on  '.$answer->getText()); // this doesn't reply back 
        });
    }

    public function run()
    {
        // This will be called immediately
        $this->askgenre();
    }
}`

**Comment by mpociot** [comment]
This is probably related to a missing / wrong cache driver. Which one are you using? Conversations get persisted in the cache.

**Comment by hackertron** [comment]
yes there is cache folder in src : "vendor/mpociot/botman/src/Mpociot/BotMan/Cache" . I don't think i am using any . so how should i add it ?

**Comment by mpociot** [comment]
How do you create the BotMan object? 
Which framework are you using?

**Comment by hackertron** [comment]
i am not using any framework . I just simply used composer to install the botman and created index.php .

`require_once(dirname(__FILE__) . '/vendor/autoload.php');
require_once('recommendation.php');
use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotMan;

$config = [
    
    'facebook_token' => token,
    'facebook_app_secret' => token,
    
];

$botman = BotManFactory::create($config);`

**Comment by mpociot** [comment]
Please take a look at the configuration: http://botman.io/installation#cache-drivers

I just updated the documentation to point out the different cache drivers supported :)

**Comment by hackertron** [comment]
Hello , but i am not using any framework . what should i do then ?

**Comment by mpociot** [comment]
You can use the Doctrine cache without any specific framework.

**Comment by hackertron** [comment]
I am still having problem with conversation . 

where should i / how should i put doctrine cache in the code  

index.php : https://ghostbin.com/paste/8rmwe

(this is where  i wanna start a conversation ) recommendation.php : https://ghostbin.com/paste/qnbrr
