### ISSUE TITLE
say() method in slack primary messages without avatar and valid username

### ISSUE THREAD

**Issue by butteff** [mpociot/botman#198]
Hello, I have this in primary messages: 
http://rgho.st/7kmfvWzLl/thumb.png

So I have primary message from default slackbot without valid avatar and username.

The code is here:
```
$msg = 'Hello user';
$botman->say($msg, $userid);
```
How I can solve the problem?
It is in slack.

**Comment by mpociot** [comment]
Which Slack implementation did you choose?
If you're using the rtm API in general, i think you have to adjust the appearance of your bot using the "additionalParameters" configure array.

**Comment by butteff** [comment]
I use this:

```
$loop = Factory::create();
$botman = BotManFactory::createForRTM([
    'slack_token' => $config['slack_token'],
], $loop);
```

For example, if I will have array of params:

```
$params = [
                    'username' => 'somename',
                    'icon_url' => 'https://way_to_this_image.png',
                ];
```

How can I use them?

$botman->say($msg, $userid, $params); or $botman->say($msg, $userid, null, $params); don't work

Can you give any advice to me?

**Comment by butteff** [comment]
I've solved the problem with wrapi\slack again:

I've created another method:

```
   public function justsay($message, $channel) {
        $client = new slack($config['slack_token']); // wrapi slack class

        $response = $client->chat->postMessage(array(
            "channel" => $channel,
            "text" => $message,
            "username" => "username",
            'icon_url' => 'https://url_to_image.png',
            "as_user" => true,
            "parse" => "full",
            "link_names" => 1,
            "unfurl_links" => true,
            "unfurl_media" => false
          )
        );
    }
```

**Comment by barryvdh** [comment]
You could just do this, right?

```php
$botman->say($message, $userId, 'Slack', [
    'as_user' => true,
]);
```

That would post as the user created for your bot.

And if you want to use the icon url, you could use this, which is posted in the Slackbot channel

```php
$botman->say($message, $userId, 'Slack', [
    'as_user' => false,
    'icon_url' => 'http://mydomain/logo.png',
    "username" => "My Bot",
]);
```
