### ISSUE TITLE
BotFrameworkDriver storage issue

### ISSUE THREAD

**Issue by kiwina** [mpociot/botman#200]
Hi, found an issue with the storage on laravel 5.4 and BotFrameworkDriver "WINDOWS"
When setting the default key the usename has ":" a colum therefore fails to safe the file
i think normalizing the user id would be appropriate for all drivers and OS

**Comment by thedotedge** [comment]
See https://github.com/mpociot/botman/issues/191

**Comment by kiwina** [comment]
Great
