### ISSUE TITLE
Botman doesn't check Command's middleware

### ISSUE THREAD

**Issue by AlexVanderbist** [mpociot/botman#203]
Hi! 

First of all thanks for the awesome package, I have have however stumbled upon a small issue...

When using groups with middleware the `listen` method doesn't check `isMessageMatching` on the selected middleware.

I've got the following setup: 
```php
$botman->group(['middleware' => $apiAiMiddleware], function($bot) {
    $bot->hears('action', function ($bot) {
        //
    });
});
```

When a message is being received by Botman, the different middleware is succesfully attached to the `Command` through the `$groupAttributes`. It's also succesfully applied in the `listen` method [here](https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L257-L258).
 
The `isMessageMatching` method however is only being called for the middlewares attached to the botman instance (`$this`), not the middlewares attached to the `Command` ([here](https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L305)).

Any thoughts? If necessary I'll provide a clear example tomorrow.

**Comment by thedotedge** [comment]
@mpociot this is the problem I have tried to describe on slack last night.
This section would not trigger, however, if middleware is attached to top-level Botman as well as `hears()`, it works:
```
$botman->group(['middleware' => $aiMiddleware], function(BotMan $bot) {
            $bot->hears('action_project_list', function (BotMan $bot) {
                $bot->reply(var_export($bot->getMessage()->getExtras(), true));
            });
        });
```

**Comment by AlexVanderbist** [comment]
I've currently solved it by passing in the `Command` in the `isMessageMatching` method it's definitely not the cleanest way but it works:
```php
foreach ($this->middleware + $command->toArray()['middleware'] as $middleware) {
    return $middleware->isMessageMatching($message, $pattern, $regexMatched);
}
```
