### ISSUE TITLE
Middleware flow

### ISSUE THREAD

**Issue by AlexVanderbist** [mpociot/botman#209]
Hi again! 

I've ran into a couple more issues regarding middleware.

First of all when using multiple middlewares the result of the first middleware's `isMessageMatching` will immediatly be returned without checking the other middlewares at all. (see https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L308)

Apart from that issue it's not completly clear how middleware works in general...
From the docs it looks like if the return value of `isMessageMatching` is `false`, the `Command` should never match (sort of like Laravel's routes).
However the `ApiAi` middleware makes it look like returning `true` on `isMessageMatching` makes the `Command` _always_ match.

Hopefully this makes sense, if not, let me know :)

**Comment by mpociot** [comment]
Hi Alex,

the `isMessageMatching` method checks all middleware classes and if one of them returns `false` the message will not be matched. This is the expected behavior. Do you have a use case for a different implementation logic?

When returning `true` or `false` on the middleware class all messages either match or do not match, that's right. This allows you to add custom checks in your middleware. This is also done in the `ApiAi` middleware when testing for the api.ai action.

**Comment by AlexVanderbist** [comment]
> the isMessageMatching method checks all middleware classes and if one of them returns false the message will not be matched.

What I meant with the first issue is that when itterating over the `$mergesMiddleware` in the `isMessageMatching` method of `Botman`; the first itteration will cause the function to return and thus not check the other middlewares.

>When returning true or false on the middleware class all messages either match or do not match, that's right. This allows you to add custom checks in your middleware. This is also done in the ApiAi middleware when testing for the api.ai action.

My specific use case was the `ApiAi` middleware in combination with a `IgnoreSlackbotMiddleware` that (you guessed it) should ignore all messages from the slackbot (some messages slackbot whispered to Botman were triggering ApiAi). 
However when `ApiAi->isMessageMatching` returns `true`, the message matches regardless of the `IgnoreSlackbotMiddleware`...

**Comment by mpociot** [comment]
Ahh I see, you're right. It should check that **all** middlewares match the message.

**Comment by AlexVanderbist** [comment]
Thanks @mpociot, great work!
