### ISSUE TITLE
Unnecessary "new Curl()" in Readme.

### ISSUE THREAD

**Issue by huanga** [mpociot/botman#21]
On [Readme.md:97](https://github.com/mpociot/botman/blame/master/README.md#L97), there is a  `new Curl()` being passed to the Botman class; the [Botman Constructor](https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L77) does not know what to do with the extra argument. Is the Curl Handler something that is required in a future version, or is it something that is no longer necessary? Either way, the documentation should be updated to reflect the current version.

**Comment by mpociot** [comment]
The `Curl` dependency is not for `BotMan` but for the `DriverManager` - see https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/DriverManager.php#L35
