### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by xar** [mpociot/botman#213]
I'm using botman with laravel 5.4 when I try to run some conversation with ask function. It will result to Serialization of 'Closure' is not allowed. Example conversation:

```
<?php
namespace App\Conversations;

use Illuminate\Foundation\Inspiring;

use Mpociot\BotMan\Answer;
use Mpociot\BotMan\Button;
use Mpociot\BotMan\Conversation;
use Mpociot\BotMan\Question;

class ReservationConversation extends Conversation
{

    /**
     * First question
     */
    public function askReason()
    {
        $question = Question::create("Ahoj, ako ti pomozem?")
            ->fallback('Unable to ask question')
            ->addButtons([
                Button::create('Tell a joke')->value('joke'),
                Button::create('Give me a fancy quote')->value('quote'),
            ]);

        return $this->ask($question, function (Answer $answer) {
            $this->say('Hello');
        });
    }
    /**
     * Start the conversation
     */
    public function run()
    {
        $this->askReason();
    }
}
```
When I take a look to stack trace I see that error comes from FileStore.php 
```
public function put($key, $value, $minutes)
    {
        $this->ensureCacheDirectoryExists($path = $this->path($key));

        $this->files->put(
            $path, $this->expiration($minutes).serialize($value), true
        );
    }
```

**Comment by mpociot** [comment]
Can you tell me how you load the botman instance?

**Comment by xar** [comment]
for sure. I have botman:listen command from your example repo

```
<?php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\Cache\LaravelCache;
use React\EventLoop\Factory;

class BotManListen extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'botman:listen';
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Tell BotMan to listen with the Slack RTM API.';
    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        /** @var \Illuminate\Foundation\Application $app */
        $app = app('app');
        $loop = Factory::create();
        $app->singleton('botman', function ($app) use ($loop) {
            return BotManFactory::createForRTM(config('services.botman', []), $loop, new LaravelCache());
        });
        require base_path('routes/botman.php');
        $loop->run();
    }
}
```

and also routes/botman.php

```
<?php

use App\Http\Controllers\BotController;
use Mpociot\BotMan\BotMan;
use App\Conversations\ReservationConversation;

$botman = resolve('botman');

$botman->hears('Ahoj', function (BotMan $bot) {
    $bot->startConversation(new ReservationConversation());
});
```

**Comment by mpociot** [comment]
Okay, so you run the bot by calling the listen command? Are you using this in a Laravel application?

Do you get any output when you call the listen command?

**Comment by mario-laserna** [comment]
Hi, I have the same issue, when I call the listen command I don't get error

The bot works if I only have a $bot->reply, but if I create a conversation I get an error, something like this:

```
     return $this->ask('What do you need?', function (Answer $answer) {
            $extras = $this->bot->getMessage()->getExtras();
            $extras_text = implode(',', $extras);
            $text_answer = $answer->getText();
            $text_answer .= ' - ' .$this->bot->getMessage()->getUser();
            $text_answer .= ' - |' .$extras_text;

            $this->say('Got it. You say ' . $text_answer);
        });
```

To allow this works I have to do this (but I think is not a good solution)

```
        $me = $this;
        return $this->ask('What do you need?', function (Answer $answer) use ($me) {
            $extras = $me->bot->getMessage()->getExtras();
            $extras_text = implode(',', $extras);
            $text_answer = $answer->getText();
            $text_answer .= ' - ' .$this->bot->getMessage()->getUser();
            $text_answer .= ' - |' .$extras_text;

            $me->say('Got it. You say ' . $text_answer);
        });
```

The problem is when inside of ask function I use $this

**Comment by xar** [comment]
I'm sorry for my later response. I don't get any response to :listen command it only crash on start conversation then I find errors in log file. I'm using laravel

**Comment by peric** [comment]
I'm having the same issue, and this is the part of my stack trace:

```
Stack trace:
#0 /var/app/vendor/opis/closure/lib/SerializableClosure.php(194): serialize(Array)
#1 [internal function]: Opis\Closure\SerializableClosure->serialize()
#2 /var/app/vendor/mpociot/botman/src/Mpociot/BotMan/Traits/HandlesConversations.php(90): serialize(Object(Opis\Closure\SerializableClosure))
#3 /var/app/vendor/mpociot/botman/src/Mpociot/BotMan/Traits/HandlesConversations.php(123): Mpociot\BotMan\BotMan->serializeClosure(Object(Closure))
#4 /var/app/vendor/mpociot/botman/src/Mpociot/BotMan/Traits/HandlesConversations.php(43): Mpociot\BotMan\BotMan->prepareCallbacks(Object(Closure))
#5 /var/app/vendor/mpociot/botman/src/Mpociot/BotMan/Conversation.php(41): Mpociot\BotMan\BotMan->storeConversation(Object(App\Messenger\Conversation\OnewaySearchConversation), Object(Closure), 'Tell us your de...', Array)
#6 /var/app/app/Messenger/Conversation/OnewaySearchConversation.php(44): Mpociot\BotMan\Conversation->ask('Tell us your de...', Object(Closure))
```

**Comment by mpociot** [comment]
Which messaging driver are you using? SlackRTM?

**Comment by peric** [comment]
@mpociot no, it's a FacebookPostbackDriver.

**Comment by mpociot** [comment]
@peric Which cache driver do you use?

The problem occurs because BotMan needs to serialize the closure in order to load and call it later, when the conversation gets triggered again (through a response).
If you inject other dependencies into your conversation class, that use closures as well the serialization will not work.

In this case you would need to unset and reload those dependencies in the __sleep and __wakeup methods.

**Comment by peric** [comment]
@mpociot thanks for your answer.

And you're right, dependencies are problematic. I've removed that one dependency class from constructor (it's an API wrapper), and it works now. So'll have to figure out some kind of different method :)

**Comment by peric** [comment]
@mpociot but maybe to continue this...

I'm struggling with an idea to use conversations to get some information from the user and to also call 3rd party API during the conversation. But, since dependencies are not allowed - what would be your proposition to do this?

**Comment by mpociot** [comment]
Well you can use the dependency. You just need to reinitialize it in the wakeup method

**Comment by mario-laserna** [comment]
@mpociot I don't think this is a good solutions, please review my code example I left here before, if I am making a question, inside of ask I need to use the bot instance to send a reply

**Comment by mpociot** [comment]
Which version of BotMan are you using? I made some modifications to the way conversations get serialized in 1.4.1

**Comment by mario-laserna** [comment]
I have not tested with this new version if works because I had to make the change that I have described, I am going to test again with the normal way tomorrow with this new version

**Comment by peric** [comment]
> Well you can use the dependency. You just need to reinitialize it in the wakeup 

@mpociot do you maybe have any example of how to do this exactly? I'm using master branch and I have only __sleep in Conversation class, but not the wakeup one.

**Comment by mpociot** [comment]
It depends on how you pass / initialize the dependencies.
But you can do something like this in your conversation class:

```php
    public function __sleep()
    {
        $this->dependency = null;
        return parent::__sleep();
    }

    public function __wakeup()
    {
        $this->dependency = new Dependency();
        return parent::__sleep();
    }

```

**Comment by peric** [comment]
@mpociot thank you. Haven't worked with similar examples before, but makes sense, and it works.

**Comment by rksumon-zz** [comment]
Just clear Route cache in bootstrap/cache/route
