### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by baopham** [mpociot/botman#214]
I might have missed something but could not find anywhere that allows me to upload file as a reply message. Or maybe it's not in the scope of the project?

Currently, I would have to use the Slack client directly:

```
$this->slackClient = new ApiClient($loop);
$this->slackClient->setToken($config['slack_token']);
return $this->slackClient->apiCall('files.upload', [...]);
```

**Comment by mpociot** [comment]
This is a great addition to BotMan. It simply hasn't been developed yet. 

Would you like to work on a pull request for the Slack drivers? 
I think it would be good to add attachments using the Message class.

**Comment by baopham** [comment]
Yep. Let me try 🤔

**Comment by mpociot** [comment]
Awesome. Let me know if you need help. You can also reach out to me via Slack

**Comment by mpociot** [comment]
This is now available for the Slack RTM driver. I'll add it for the other drivers too!
