### ISSUE TITLE
Listen to other data types

### ISSUE THREAD

**Issue by mpociot** [mpociot/botman#215]
BotMan should be able to listen for other data types, such as images, audio, location or generic attachments.

**Proposed API**
```php
// Images
$botman->receivesImages(function($bot) {
   $data = $bot->getMessage()->getImages();
});

// Videos
$botman->receivesVideos(function($bot) {
   $data = $bot->getMessage()->getVideos();
});

// Audio
$botman->receivesAudio(function($bot) {
   $data = $bot->getMessage()->getAudio();
});

// Location
$botman->receivesLocation(function($bot) {
   $data = $bot->getMessage()->getLocations();
});

// Generic
$botman->receivesAttachments(function($bot) {
   $data = $bot->getMessage()->getAttachments();
});
```

Necessary Steps:

**Images**
- [X] Telegram Driver
- [X] Slack RTM Driver
- [X] Facebook Driver
- [x] MS Bot Framework Driver
- [x] WeChat Driver
- [ ] HipChat Driver

**Videos**
- [X] Telegram Driver
- [X] Slack RTM Driver
- [X] Facebook Driver
- [ ] MS Bot Framework Driver
- [x] WeChat Driver
- [ ] HipChat Driver

**Audio**
- [X] Telegram Driver
- [X] Slack RTM Driver
- [X] Facebook Driver ( @christophrumpel )
- [x] WeChat Driver
- [ ] HipChat Driver

**Location**
- [X] Telegram Driver
- [X] Facebook Driver ( @christophrumpel )
- [x] WeChat Driver
- [ ] HipChat Driver

**Generic**
- [X] Telegram Driver
- [X] Slack RTM Driver
- [X] Facebook Driver ( @christophrumpel )
- [X] MS Bot Framework Driver
- [ ] WeChat Driver
- [ ] HipChat Driver

Related issue: #169

**Comment by mpociot** [comment]
The branch for this feature is: https://github.com/mpociot/botman/tree/hear-other-data-types-issue-215
Any help is greatly appreciated

**Comment by christophrumpel** [comment]
I can start with the Facebook Audio Driver.

**Comment by aios** [comment]
need recievesContact.
Telegram has KeyboardButton with param request_contact. Can't hear on contacts
@mpociot

**Comment by ahmedash95** [comment]
@mpociot I will start working on Telegram

**Comment by christophrumpel** [comment]
Just noticed we need this vor videos too right? @mpociot can you update the dropdown list here?

**Comment by mpociot** [comment]
@christophrumpel yeah, you're right. I updated the list

**Comment by kmarima** [comment]
Have you thought about how this would work in a Conversation ??

**Comment by mpociot** [comment]
That's how you would access it from a conversation:

```
$this->ask('How are you doing?', function($answer) {
    $images = $answer->getMessage()->getImages();
});
```

**Comment by christophrumpel** [comment]
@ahmedash95 are you still working on Telegram? I could do some of them too. I like to see these features merged soon :-)

**Comment by ahmedash95** [comment]
@christophrumpel Hi Chris , unfortunately I couldn't start it until now, you can start on it and maybe we talk later and co-operate together.

**Comment by christophrumpel** [comment]
Ok thx @ahmedash95 , sounds great.  I started with Telegram Video and Audio.

**Comment by christophrumpel** [comment]
Did the Telegram Video driver, now working on the Telegram Audio driver

**Comment by mpociot** [comment]
I just looked into the Slack integration and noticed that Slack only supports receiving images, audio, etc. through the RTM API.

**Comment by christophrumpel** [comment]
Yeah I did too, you just get the text :-( guess it would be still possible to detect the file URL and type. But not very beautiful.

**Comment by christophrumpel** [comment]
So, still MS Bot Framework Driver, WeChat and HipChat missing. Maybe I can checkout MS, anyone willing to help with the others?

**Comment by ahmedash95** [comment]
@christophrumpel Hi chris .. do you need any help with telegram ? I have a free time this weekend and could work on something with you ?

**Comment by christophrumpel** [comment]
Hey, nice of you but Telegram is already finished 😉  On the top is a list with missing ones. Maybe you can do one of them?

**Comment by ahmedash95** [comment]
Good job man 👍 .

**Comment by kenkit** [comment]
so uhhm, how do you access the image url or fileid ?
I wish you could add method for accessing values from the raw message received.
My developement is stuck here, am on telegram btw.

**Comment by christophrumpel** [comment]
@kenkit you can get the image ur like mentioned above:

```php

// Images
$botman->receivesImages(function($bot) {
   $data = $bot->getMessage()->getImages();
});
```

The `data` is an array of images.

**Comment by christophrumpel** [comment]
@mpociot so just the HipChat drivers are now missing right?

**Comment by mpociot** [comment]
Yes 🎉

**Comment by zynamis** [comment]
Hi Guys....I'm trying to listen for locations but I am not receiving the locations callback.

These are my methods..
//Requesting for Location
$this->bot->reply($message, [
            'message' => [
                'quick_replies' => json_encode([
                    [
                        'content_type' => 'location'
                    ]
                ])
               ]
              ]);


$botman->receivesLocation(function($bot,$location) {
         //This never gets called.
          $lat = $location->getLatitude();
          $lng = $location->getLongitude();
          echo $lat;
    });


    $botman->hears('{text}', function (BotMan $bot,$text,$data) {
        $bot_user= $bot->getUser();

    });

**Comment by motti45** [comment]
how can i make botman to hear from another input ???

for example i wrote another piece of code that detect errors and make a json from each one.

i want to make botman hear them and when get one start a conversation with the user.

thanks :)
