### ISSUE TITLE
Usage of Telegram callback buttons

### ISSUE THREAD

**Issue by aios** [mpociot/botman#217]
Is it possible to add documentation for the use of callback buttons in the Telegram

**Comment by mpociot** [comment]
Please take a look at the conversation documentation. You can use the `ask` method inside conversations and use the `Question` class in combination with Buttons.

**Comment by aios** [comment]
Yeah thanks i finded!

**Comment by aios** [comment]
If i want to add additional options to buttons what i must do?
Now has only `text` and `callback_data`
https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Drivers/TelegramDriver.php#L142
