### ISSUE TITLE
Custom MiddleWare Not Fire isMessageMatching

### ISSUE THREAD

**Issue by aios** [mpociot/botman#218]
`$message = $this->applyMiddleware($message, $messageData['middleware']);`

that string doesnt merge `$this->middleware` with middlewares in `$messageData['middleware']`

so 
![image](https://cloud.githubusercontent.com/assets/737550/23026363/b5113090-f469-11e6-8da8-3152b597d7c3.png)
That example not working when we want to except message by something

**Comment by mpociot** [comment]
Please use `dev-master` in the meantime. I fixed this two days ago :)

**Comment by aios** [comment]
i fixed it

**Comment by aios** [comment]
thanks - will wait next release)
