### ISSUE TITLE
Initial Welcome Message (Facebook Messenger)

### ISSUE THREAD

**Issue by iadj** [mpociot/botman#219]
I want to show users a "Getting Started" Button Template as soon as they open a dialogue with my chat bot in Messenger. Is there a way to do this?

Also, this is by far the best chat bot framework I've found! Great job 🥇

**Comment by mpociot** [comment]
Hey,

thank you - keep spreading the word about it :)

You can enable the "Get started button" using this guide: https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

If you then want to listen for it, use the `FacebookPostbackDriver`:

```php

$botman->hears('MY_CUSTOM_PAYLOAD', function($bot) {
    $bot->reply('Lets get this party started!');
})->driver(FacebookPostbackDriver::class);
```

I think I have to add this to the FAQ :)

**Comment by iadj** [comment]
Hey Marcel,

Thanks for the prompt response! I also believe this belongs in the docs :)
I got it working by making a POST request as described in Facebook's 
example. I'm not sure if what I'm doing it optimal, though.

Do I make the POST request to create the Get Started button once, and 
then it's set forever?
Or should I initialize the POST request in `botman.php`?

**Comment by mpociot** [comment]
Yeah exactly. You only need to do this once. That's why it's not in BotMan :)

**Comment by iadj** [comment]
@mpociot Alright, thanks! It might be cool for the Laravel version to have some sort of dashboard that allows you to update these things (Greetings, Get Started Button, etc.) from an admin view. Perhaps a `botman-starter-kit` of sorts?

**Comment by mpociot** [comment]
Yeah, I already have quite a few ideas that will only work in the Laravel starter project :)
