### ISSUE TITLE
Starting conversation on the channel doesn't work 

### ISSUE THREAD

**Issue by thedotedge** [mpociot/botman#221]
It is possible to pass a channel to `startConversation`, however, the message is created with empty user: `new Message('', '', $channel)`.
Now, when we persist it to cache the user is blank for the cache key (channel is set properly):
```
public function getConversationIdentifier()
    {
        return 'conversation-'.sha1($this->getUser()).'-'.sha1($this->getChannel());
    }
```

When it's retrieved from the cache upon response, the user it no longer blank, which results in different key and cache miss, thus breaking the conversation.

Possible fix: I am not familiar with other drivers, will channel be different from user when initiating the conversation? Is it safe to initialise message user to channel?

**Comment by mpociot** [comment]
That's why there is a `getOriginatedConversationIdentifier` that ignores the user. So this is not an issue :)

**Comment by thedotedge** [comment]
@mpociot I hope PR explains it https://github.com/mpociot/botman/pull/223 :)

**Comment by mpociot** [comment]
Umm no, not really.
This code looks for the normal cache identifier first and if nothing was found it tries the identifier with a blank user instead:

https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Traits/HandlesConversations.php#L59-L62

Here is the code for the cache identifier: https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Message.php#L75-L78

**Comment by thedotedge** [comment]
I am able to reproduce behavior locally: 
when you `startConversation` user is blank and inside `getConversationIdentifier` you do `sha1('')`, which is not an empty string, which `getOriginatedConversationIdentifier` expects.
It was working fine indeed before hashing was introduced.

**Comment by mpociot** [comment]
Oh I see. Could you please modify the PR so that you change the `getOriginatedConversationIdentifier`? That's the one producing this issue then!

**Comment by thedotedge** [comment]
But wouldn't it be exactly the same as `getConversationIdentifier` then?
```
return 'conversation-'.sha1($this->getUser()).'-'.sha1($this->getChannel());
```

**Comment by thedotedge** [comment]
Of were you thinking about:
```
return 'conversation-'.sha1('').'-'.sha1($this->getChannel());
```

**Comment by mpociot** [comment]
Yeah, but I would like to have it in two separate methods, so it's clear why we do this

**Comment by thedotedge** [comment]
Done.
