### ISSUE TITLE
Mattermost support

### ISSUE THREAD

**Issue by cedricziel** [mpociot/botman#23]
> [Mattermost](https://www.mattermost.org/) is an open source, self-hosted Slack-alternative
>
> As an alternative to proprietary SaaS messaging, Mattermost brings all your team communication into one place, making it searchable and accessible anywhere. It’s written in Golang and React and runs as a production-ready Linux binary under an MIT license with either MySQL or Postgres.

Mattermost is bundled with GitLab Omnibus and it would be great if we could suport it

**Comment by mpociot** [comment]
I'll close this issue. If you want to create a pull request with a driver that supports Mattermost you would be my hero 👍

**Comment by stefanvangastel** [comment]
Mattermost is Slack compatible, is there a way to configure the endpoint for the Slack driver? So one could point it to a Mattermost installation?

**Comment by stefnats** [comment]
Is Mattermost still Slack compatible? I think the APIs differ now, an example on how to use the slack driver for mattermost would be appreciated :)
