### ISSUE TITLE
Making sure that replies are received to a slack client in the order you put them in

### ISSUE THREAD

**Issue by P1llus** [mpociot/botman#230]
Hello devs!

I am just wondering how i can ensure that the replies that botman sends to slack, is in the order i put them in.
I'm guessing that due to the `$loop->run(); ` at the end of the bot instance, there wont help anything to have `sleep(seconds)` between replies.

Here is an example:
```     $results = $this->service->ipSearch($ip);
        $bot->reply('Results for: '.$ip);
        $bot->reply('Target is running on: '.$results['data'][0]['os']);
        $bot->reply('Company: '.$results['data'][0]['asn']);
        $bot->reply('ISP is: '.$results['data'][0]['isp']);
        $bot->reply('Originates from: '.$results['country_name']);
        $bot->reply('Ports open are:');

        if(count($results['data']) > 0) 
        {
            foreach ($results['data'] as $data)
            {
                $bot->reply($data['transport'].' : '.$data['port'].' - '.$data['product']);
            }
        }
        $bot->reply('More results can be found on: '.'https://www.shodan.io/host/'.$ip);
```

When it comes back to slack, it will be in any random order, like this:
![image](https://cloud.githubusercontent.com/assets/8027539/23097173/c7817dbe-f62d-11e6-96e1-3ca2d1d4c488.png)

Is there any way i can preven this? Should i for example have all the replies in just one reply? Can i create newlines in any way if this is needed?

**Comment by mpociot** [comment]
Yes, this is related to the asynchronous messages / React PHP.
But you can just send one message and use line breaks.

```php
$bot->reply('Test 1' . PHP_EOL . 'Test 2' . PHP_EOL . 'Test 3');
```

**Comment by mpociot** [comment]
This is now fixed in dev-master
