### ISSUE TITLE
[Api.ai] sessionId parameter

### ISSUE THREAD

**Issue by ribb3r** [mpociot/botman#231]
Hi,

I think we should change `Mpociot/BotMan/Middleware/ApiAi.php:68`. Currently we use `'sessionId' => time()` to generate a new sessionId on every request. To keep continue the course of conversation we should use a user based sessionId. E. g. `'sessionId' => sha1($driver->getName() . $message->getUser())`.

Thank you.

**Comment by mpociot** [comment]
Could you provide a pull request for this change?

**Comment by ribb3r** [comment]
Yes, of course

**Comment by christophrumpel** [comment]
Ah thx @ribb3r , was on my list when I added the Driver but forgot.

**Comment by ribb3r** [comment]
I just opened a pull request. But there is an issue with the ApiAiTest. Maybe someone could look at the source?
