### ISSUE TITLE
Add rocket.chat support

### ISSUE THREAD

**Issue by a-komarev** [mpociot/botman#235]
It will be awesome to implement driver for rocket.chat support, while it's really the same as Slack but self-hosted solution.

**Comment by mpociot** [comment]
I'm closing this siissue since I don't plan to add rocket chat support soon. You can of course write your own service driver.

**Comment by dfridrich** [comment]
I think this should be consider agan. 🤖

**Comment by filippotoso** [comment]
I just published a basic driver for Rocket Chat:

https://github.com/filippotoso/driver-rocket-chat

In the next few weeks I'm going to add the support for media attachments.

**Comment by franzliedke** [comment]
@mpociot Would you accept this driver into your organization if it can be considered feature complete?

**Comment by mpociot** [comment]
@franzliedke yes!
