### ISSUE TITLE
API.ai integration does not seem to be working

### ISSUE THREAD

**Issue by august** [mpociot/botman#245]
I've set up my account at API.ai and configured everything properly. In my botman routes, I have this:

`$botman->hears('users.count', 'App\BotCommands\UserCount@handle')->middleware(ApiAi::create(env('APIAI_KEY'))->listenForAction());`

This never gets called.

I know that API.ai is set up correctly. I went into the `ApiAi@handle` method and logged the `$response`. The action being returned is `users.count` which is correct. That action just never calls the `UserCount` controller.

I've also tried without the controller and just doing a function. That doesn't work either.

I should mention I'm using Laravel and Slack RTM.

**Comment by mpociot** [comment]
Hello,

this issue was already fixed a while ago. I just tagged a new release ( 1.4.1 ). 
Should work after a composer update 👍

**Comment by august** [comment]
Thanks! Works great now!
