### ISSUE TITLE
Nexmo Virtual number on Originating messages

### ISSUE THREAD

**Issue by kre8or69** [mpociot/botman#250]
Hey Marcel

I had an issue with using nexmo to send out an originating message with a given virtual number.

I don't know if there is a proper way of doing this but i figured i would share what did. I added a user to the say to allow adding the virtual number on messages. Worked a treat!

```
/**
     * @param string|Question $message
     * @param string|array $channel
     * @param DriverInterface|null $driver
     * @param string $user
     * @param array $additionalParameters
     * @return $this
     */
    public function say($message, $channel, $driver = null, $user = '', $additionalParameters = [])
    {
        if (is_null($driver)) {
            $drivers = DriverManager::getConfiguredDrivers($this->config);
        } else {
            $drivers = [DriverManager::loadFromName($driver, $this->config)];
        }

        foreach ($drivers as $driver) {
            $matchMessage = new Message('', $user, $channel);
            /* @var $driver DriverInterface */
            $driver->reply($message, $matchMessage, $additionalParameters);
        }

        return $this;
    }
```

**Comment by mpociot** [comment]
Hey,

I think you can just pass the number as an additional parameter:

```php
$botman->say('hello', '123456789', NexmoDriver::class, [
    'from' => 'my-number'
]);
```

**Comment by kre8or69** [comment]
Ohh kool! Ill try it out :)

**Comment by kre8or69** [comment]
Yeah that worked!

While i'm here is there a proper way to access the return payload from nexmo? I have a way at the moment but i need to get at the message-id to match up the delivery receipt after its sent.

**Comment by mpociot** [comment]
Hm no..sorry, that's not possible at the moment.
