### ISSUE TITLE
Slack Commands - "In Channel" vs Ephemeral

### ISSUE THREAD

**Issue by leenooks** [mpociot/botman#251]
Hi,

I couldn't see how to have the bot respond with "in channel" message when using botman to answer slack commands. Did I miss something?

...deon

**Comment by mpociot** [comment]
Hi,

what do you mean by "in channel" messages?

**Comment by leenooks** [comment]
https://api.slack.com/slash-commands#responding_to_a_command

See the section "In Channel" vs "Ephemeral" responses

IE: When the bot replies to a slack slash command, the response is only visible to the person who instigated the command. It is possible for the response to be visible to everybody in the channel, hence "in channel" response type.

**Comment by mpociot** [comment]
You can pass additional parameters to the response.
For example:

```
$botman->hears('your command', function($bot) {
    $bot->reply('respond in channel', [
        'response_type' => 'in_channel'
    ]);
});
```

**Comment by leenooks** [comment]
Sorry, this is not working.

It would appear that slash commands are defaulted to a "text" response SlackDriver::reply().

If I change it to a JSON response (calling SlackDriver::respondJSON()) and forcing content-type to application/json then it works.

It might be desirable to default slash command responses to be json responses so that more advanced responses could be returned (e.g.: with attachments, pretext, etc).
