### ISSUE TITLE
Regex in api.ai hear middleware?

### ISSUE THREAD

**Issue by vdnt** [mpociot/botman#252]
Could someone explain why regexp not working in api.ai middleware hears function?
They work fine in normal hears..

Using like this:

```
        $botman->hears('smalltalk(.*)', function(BotMan $bot) {
            $extras = $bot->getMessage()->getExtras();
            $apiReply = $extras['apiReply'];
            $bot->reply($apiReply);
        })->middleware(ApiAi::create('api_key')->listenForAction());
```

**Comment by mpociot** [comment]
Huh. To be honest , I haven't thought of this. The API ai middleware currently only checks for exact matches. 
But being consistent and also allowing a regex makes a lot of sense!

**Comment by vdnt** [comment]
Yeh! I though i'm doing something wrong.. I enabled "Small Talk" domain on Api.AI to make bot a little chatty, bot different topic has different action! So can only match one :)

**Comment by christophrumpel** [comment]
Yeah especially with the API.ai domains it really makes sense. Anyone of you working on a PR already?

**Comment by mpociot** [comment]
Done :)
