### ISSUE TITLE
Are  Telegram Inline keyboards implemented in conversations?

### ISSUE THREAD

**Issue by LeonAlvarez** [mpociot/botman#256]
I would like to use them in a Conversation, but couldn`t find how to do it.
At the moment im using addButton but its placing each button in a new row.

![image](https://cloud.githubusercontent.com/assets/22636643/23523199/4435996a-ff86-11e6-9fed-ca4011a977d4.png)
 
This is what I have now

**Comment by LeonAlvarez** [comment]
Yes they are :P 

![image](https://cloud.githubusercontent.com/assets/22636643/23559727/40a05404-0038-11e7-858f-ab52b2f83596.png)

Passing buttons manually as extra parameters instead of using ->addButtons
Worked.

**Comment by mpociot** [comment]
Oh cool. Do you mind sharing the code?

**Comment by kenkit** [comment]
https://github.com/mpociot/botman/issues/280

**Comment by syltluwe** [comment]
`$keyboard = [
            ['300 €', '400 €', '450 €'],
            ['500 €', '600 €', '700 €'],
            ['800 €', '900 €', '1000 €'],
            ['1200 €', '1400 €', '2000 €'],
            ['2500 €', '3000 €', 'any'],
        ];
        $this->ask('How much?',
            function (Answer $answer) {
                $this->askAdress();
            }, ['reply_markup' => json_encode([
                'keyboard' => $keyboard,
                'one_time_keyboard' => true,
                'resize_keyboard' => true
            ])]
        );`
