### ISSUE TITLE
Not replying back in conversation

### ISSUE THREAD

**Issue by Yassakesbi** [mpociot/botman#259]
Hello, first of all thank you for the awesome framework.
I have an issue that kept me waking for 2 days.
 I wanted to try out the sample conversation on the documentation website, When i type 'hello', i get the firstname question back but when i enter my name it stops, it doesn't enter the callback function. Here's my code. sorry if i seem like a newbie because i am, thank you in advance.

This is my FirstConversation.php Class in the root directroy.
```
<?php 
use Mpociot\BotMan\Answer;
use Mpociot\BotMan\Conversation;
use Mpociot\BotMan\Botman;
use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotManServiceProvider;
use Mpociot\BotMan\Button;
use Mpociot\BotMan\Command;
use Mpociot\BotMan\DriverManager;
use Mpociot\BotMan\Message;
use Mpociot\BotMan\Question;
use Mpociot\BotMan\User;

require_once 'vendor/autoload.php';

class FirstConversation extends Conversation
{
    protected $firstname;
    
    protected $email;

    public function askFirstname()
    {   
        $this->ask('Hello! What is your firstname?', function(Answer $answer) {
            // Save result
            logMe("Please work !!".$this->firstname);
            $this->firstname = $answer->getText();
            $this->say('Nice to meet you '.$this->firstname);
            $this->askEmail();
        });
    }

    public function askEmail()
    {
        $this->ask('One more thing - what is your email?', function(Answer $answer) {
            // Save result
            $this->email = $answer->getText();

            $this->say('Great - that is all we need, '.$this->firstname);
        });
    }

    public function run()
    {
        // This will be called immediately
        $this->askFirstname();
    }
}
 ?>
```
also im using this in my main entry point botman.php
```
<?php

use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotMan;
use Mpociot\BotMan\Cache\DoctrineCache;

require_once 'vendor/autoload.php';

include 'log.php';
include 'FirstConversation.php';

$config = [
    'facebook_token' => $token,
    'facebook_app_secret' => $appsecret,
];



// doctrine cache driver 
$cacheDriver = new \Doctrine\Common\Cache\ArrayCache();

// Botman instance
$botman = BotManFactory::create($config,new DoctrineCache($cacheDriver));

// verify app secret
$botman->verifyServices($appsecret);

$botman->hears('Hello', function($bot) {
	 $conv = new FirstConversation;
         $bot->startConversation(new FirstConversation);
});

// start listening
$botman->listen();
```

**Comment by LeonAlvarez** [comment]
` public function run()
    {
        // This will be called immediately
        $this->askEmail();
    }`

In the run method  you should be calling askFirstname() insted of askEmail()

**Comment by Yassakesbi** [comment]
It is still the same, either way it doesn't enter the callback methos

**Comment by Yassakesbi** [comment]
@LeonAlvarez  It is still the same, either way it doesn't enter the callback method

**Comment by mpociot** [comment]
You need a persistent cache, as conversations get stored in the cache. So your array cache won't help you

**Comment by Yassakesbi** [comment]
@mpociot I tried many other caches they all return errors not finding certain methods.

- ApcCache :
Fatal error: Call to undefined function Doctrine\Common\Cache\apc_fetch() in C:\wamp64\www\Bot\vendor\doctrine\cache\lib\Doctrine\Common\Cache\ApcCache.php

-MemcacheCache
Fatal error: Call to a member function get() on null in C:\wamp64\www\Bot\vendor\doctrine\cache\lib\Doctrine\Common\Cache\MemcacheCache.php 

This is the code i used : 
$cacheDriver = new \Doctrine\Common\Cache\MemcacheCache();
$botman = BotManFactory::create($config,new DoctrineCache($cacheDriver));

**Comment by mpociot** [comment]
I don't have experience with the different doctrine cache implementations.

Try this:
```
$cacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
$botman = BotManFactory::create($config,new DoctrineCache($cacheDriver));
```

**Comment by Yassakesbi** [comment]
@mpociot Thank you for your time. It doesn't show any errors but i still don't get a reply. Do i need to download any extension or enable anything ?

**Comment by Yassakesbi** [comment]
Finally, i fixed it. It turned out i didn't have the acpu extension installed and enabled on my wamp server. Thank you for your time i appreciate it.

**Comment by mpociot** [comment]
👍

**Comment by Abhishekjaiz** [comment]
> Finally, i fixed it. It turned out i didn't have the acpu extension installed and enabled on my wamp server. Thank you for your time i appreciate it.

hey i am getting the same issue can you help me with it. I am very thankful to you.

**Comment by vdomah** [comment]
> I don't have experience with the different doctrine cache implementations.
> 
> Try this:
> 
> ```
> $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
> $botman = BotManFactory::create($config,new DoctrineCache($cacheDriver));
> ```

What is the namespace of DoctrineCache? Can't find needed package. Installed only Doctrine/Common

**Comment by vdomah** [comment]
> I don't have experience with the different doctrine cache implementations.
> 
> Try this:
> 
> ```
> $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
> $botman = BotManFactory::create($config,new DoctrineCache($cacheDriver));
> ```

Hello!
Why can I get the following error using this cache driver with exact same code? Here the error:

````
'msg' => 'var_export does not handle circular references',
  'line' => 96,
  'file' => '/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php',
````
