### ISSUE TITLE
empty stopConversation methods

### ISSUE THREAD

**Issue by dizews** [mpociot/botman#261]
Hello.
Thank you for the good project.

In the last release you told "Added ability to either temporarily skip conversations or completely stop them using the skipConversation and stopConversation methods on the conversation object.", but the body of this methods is empty. 

Is it normal or you forget to commit some changes?

**Comment by mpociot** [comment]
Hey, I think this lacks documentation.

In these methods, you can detect if you want to stop or skip the current conversation.
So in order to skip/stop the conversation, return `true`:

Example:

```php
public function skipConversation(Message $message)
{
    return $message->getMessage() === 'help';
}
```

So if a user writes "help", it will not trigger a ongoing conversation.

**Comment by dizews** [comment]
thx

**Comment by lakinmohapatra** [comment]
I used 

`$botman->hears('stop', function(BotMan $bot) {
	$bot->reply('stopped');
})->stopsConversation();`

Its not working

**Comment by sasha-ch** [comment]
> public function skipConversation(Message $message)
> {
>     return $message->getMessage() === 'help';
> }

@mpociot ,
Looks like `$message->getText()` works ok.
Be great to add in docs.
