### ISSUE TITLE
The first just positive issue

### ISSUE THREAD

**Issue by christophrumpel** [mpociot/botman#263]
Inspired by little article I just read I deeply felt the need to just say `THANK YOU` @mpociot for maintaining this project. I guess it is really hard to find enough time, patience and energy to read issues, comment, discuss, test and so on.
I will also try to think more about the maintainer of an open-source project before writing an a poor issue or PR. (or before contacting Marcel on Slack, like I do a lot :-))

**Comment by mpociot** [comment]
❤️ thank you, Christoph!

And just to let you know: It's okay to contact me via Slack :)
