### ISSUE TITLE
Too many api calls

### ISSUE THREAD

**Issue by SquareBeard** [mpociot/botman#266]
Hello, I believe there is a problem with the way group middlewares are handled.
Each "hears" call within a group triggers the handle method of the middleware, thus making a post request. Maybe the middleware should cache the request response. But it would be better to only call it once or am I missing something?

E.g. this would cause three api.ai calls :
```php
$botman->group(['middleware' => ApiAi::create(config('services.api_ai_key'))->listenForAction()], function ($bot) {
    $bot->hears('input.unknown', 'App\Bot\Commands\Unknown@handle');
    $bot->hears('smalltalk.(.*)', 'App\Bot\Commands\SmallTalk@handle');
    $bot->hears('weather.(.*)', 'App\Bot\Commands\Weather@handle');
});
```

**Comment by mpociot** [comment]
You're right. Fixed this issue.
