### ISSUE TITLE
how do I get the text of the message sent

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#268]
I mean Like if I want to get the message befor passing it the the hears() function.

**Comment by mpociot** [comment]
What do you mean? You could listen for .* if you want to listen for all messages

**Comment by kenkit** [comment]
I found it. please create a gitter chat on this repo. 
Many are getting lost with help

**Comment by mpociot** [comment]
If you need help that is unrelated to issues, please join us on our BotMan Slack team: https://rauchg-slackin-jtdkltstsj.now.sh/
