### ISSUE TITLE
[TELEGRAM] sendSticker()  AND Sendfile by FILE_ID Urgent request to implent this method [URGENT]

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#271]
Hi, I hope you will include some basict telegram functions like sendSticker and sendfile by file_id.
I can't get my bot to send files by file_id .
This is the only thing my bot, is lacking after moving from the official telegram php sdk.

**Comment by mpociot** [comment]
Wow...seems like this is urgent, huh?
...

You now have access to the low level request methods to call your own API methods:

Example:

```
$botman->hears('BotMan is...', function($bot){
    $bot->sendRequest('sendSticker', [
        'sticker' => 'CAADAQADIgADPdfTAWSju9Jr9M6PAg'
    ]);
});
```

This way, you can call all the APIs you need.

**Comment by kenkit** [comment]
Yes. This is all my bot needs, thanks for your prompt response btw.
My telegram bot is known as @the_eleventh_bot, and it uses this lib, check it out when you have time.

**Comment by kenkit** [comment]
Method [sendRequest] does not exist. in /app/vendor/mpociot/botman/src/Mpociot/BotMan/BotMan.php:487

**Comment by christophrumpel** [comment]
You need to load the lates version of BotMan. It is a new method.

**Comment by kenkit** [comment]
ooh, ok.

**Comment by kenkit** [comment]
I've just switched to dev master branch

```
 Mar 15 11:19:43 pacific-shore-14311 app[web] info [15-Mar-2017 08:19:43 UTC] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /app/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/TelegramDriver.php:235
Mar 15 11:19:43 pacific-shore-14311 app[web] info Stack trace:
Mar 15 11:19:43 pacific-shore-14311 app[web] info #0 /app/vendor/mpociot/botman/src/Mpociot/BotMan/BotMan.php(389): Mpociot\BotMan\Drivers\TelegramDriver->sendRequest('sendSticker', Array, Object(Mpociot\BotMan\Message))
Mar 15 11:19:43 pacific-shore-14311 app[web] info #1 /app/index.php(110): Mpociot\BotMan\BotMan->sendRequest('sendSticker', Array)
Mar 15 11:19:43 pacific-shore-14311 app[web] info #2 [internal function]: {closure}(Object(Mpociot\BotMan\BotMan))
Mar 15 11:19:43 pacific-shore-14311 app[web] info #3 /app/vendor/mpociot/botman/src/Mpociot/BotMan/BotMan.php(279): call_user_func_array(Object(Closure), Array)
Mar 15 11:19:43 pacific-shore-14311 app[web] info #4 /app/index.php(132): Mpociot\BotMan\BotMan->listen()
Mar 15 11:19:43 pacific-shore-14311 app[web] info #5 {main}
Mar 15 11:19:43 pacific-shore-14311 app[web] info   thrown in /app/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/TelegramDriver.php on line 235
Mar 15 11:19:43 pacific-shore-14311 app[web] info 10.183.102.41 - - [15/Mar/2017:08:19:39 +0000] "POST /index.php HTTP/1.1" 500 - "-" "- 
```

**Comment by mpociot** [comment]
Fixed it

**Comment by kenkit** [comment]
Ok, let me try.

**Comment by kenkit** [comment]
It worked!
Thanks.

**Comment by kenkit** [comment]
But I don't know if being on the dev branch is a good idea ?

**Comment by mpociot** [comment]
If you want to use that feature and can not wait until I tag a new release, it's probably a good idea

**Comment by kenkit** [comment]
Ok, i'm working on a telegram bot that listens on two api.ai agents.So far it works fine.
I use the hears function without any input string so it catches all the messages.
After retrieving the message it forwards it to **api.a agent 1**, which checks the message for commands that trigger any of my custom webhooks. It then stores the response in a string and grabs the vars. 
After this execution goes into an if loop which check if some parameters were triggered by the first agent, if they were then it woun't execute the 2 agent which is just a chatting bot, if they were triggered it executes it and modifys the response message.
Unfortunately I could not find a way of using only 1 agent if it's just  chatting, which means I have to ignore the first agents response.

**Comment by kenkit** [comment]
I haven't worked on the chat intent's, i'm considering converting aiml files and importing them into api.ai so the response is much more relative.
