### ISSUE TITLE
TELEGRAM newlines and  other text formating options

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#273]
Whenever I try using \n or <br> they just get displayed int the chat. 
Not event PHP_EOL.
Anyone succeeded in sending newlines or bold output ?

**Comment by mpociot** [comment]
You can use `Markdown` or `HTML` parse modes.

Just set this as additional Parameters to your reply method:

```php
$bot->reply('Hello *you*', [
    'parse_mode' => 'Markdown'
]);
```

See: https://core.telegram.org/bots/api#markdown-style

**Comment by kenkit** [comment]
It does not work, it endsup [blocking the bot] with alot of messages,  the bot retries contacting(response) the telegram server with the  [html] text whitch it can't send then it keeps seeing the new message which it cannot respond to, I had to disable the reply function after reseting the webhook to make sure there are no more messages pending some response.

**Comment by kenkit** [comment]
PHEW! 
I've just cleared the 'pending_update_count'. I'll just have to wait for the official implementation.

**Comment by gczh** [comment]
I can affirm that this doesn't work.

**Comment by johnson-jnr** [comment]
Hi, make sure you test on the app itself, it doesn't work when testing locally but I can confirm that this works on the app
`$bot->reply('Hello <b>you</b>', [
    'parse_mode' => 'HTML'
]);`
