### ISSUE TITLE
Changed issue to:Telegram Edit an already sent message Telegram keyboard

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#274]
Hi, 
Again am back here, am stuck again, how do you send a telegram keyboard in response to a messsage ?
I am finalizing my bot, and also how do you edit an already sent message ?
This is all I need to make my bot more elegant.

**Comment by LeonAlvarez** [comment]
U need to hack a bit, create a low level method in your Driver and use editMessageText or editMessageReplyMarkup . But im stuck finding way to use it on Conversations, when I edited the message Botman didn't answer to the callbacks, guess I need to update the conversation in the cache or something.

**Comment by mpociot** [comment]
The `dev-master` branch now gives you access to the low level API methods.
So you can (for Telegram as an example) perform API requests like this:

```
$apiParameters = [
    'foo' => 'bar'
];
$bot->sendRequest('API_ENDPOINT', $apiParameters);
```

this also works inside of conversations using `$this->bot->sendRequest` so this might help you

**Comment by kenkit** [comment]
Actually I need the bot to participate in the telegram bot competition, i've been informed it's a requirement. I'll see what I can do about it tomorrow.
Thanks for your advice btw.
CHAT LOG
```
28. USER:Telegram DATE:2017-03-16 22:41:16 :MESSAGE: /start BOT REPLY:I am not a normal Telegram bot. You just chat normally as a person. Ask me about :[Chat] [ip address scan], [reddit news] , [ebook search], [botprize].
29. USER:Telegram DATE:2017-03-16 22:41:20 :MESSAGE: /start BOT REPLY:I am not a normal Telegram bot. You just chat normally as a person. Ask me about :[Chat] [ip address scan], [reddit news] , [ebook search], [botprize].
30. USER:Telegram DATE:2017-03-16 22:41:20 :MESSAGE: /start BOT REPLY:I am not a normal Telegram bot. You just chat normally as a person. Ask me about :[Chat] [ip address scan], [reddit news] , [ebook search], [botprize].
```

**Comment by kenkit** [comment]
@LeonAlvarez  The same thing happend to me, it endended up flooding my chat with messages.
But tommorow I'll give it my full attention.

**Comment by LeonAlvarez** [comment]
I been testing, but when editing telegram mesage inside the conversation, the conversation stop works

**Comment by mpociot** [comment]
As discussed in Slack, the problem happened because you executed the callback function while storing it as a conversation response. Can this be closed now?

**Comment by kenkit** [comment]
Let's say the bot sends a message, and afterwards instead of replying with a new message. How do you edit that message.
