### ISSUE TITLE
Facebook Template in Conversations

### ISSUE THREAD

**Issue by ribb3r** [mpociot/botman#277]
Hi all,

I'm using conversations with `DoctrineCache` inside a symfony 3 application (Botman `dev-master`). I observe the following behavior inside my conversation class:

1. Using the `ask()` method with a `question object`
2. Using `isInteractiveMessageReply` to detect, if the user interacted with the message
3. Inside `isInteractiveMessageReply` reply with a facebook template

Once the facebook template is sent, I receive again the webhook call from facebook with the answer of 1. If I change my message from facebook template to "normal" text, I won't receive the answer of 1. again (as expected)

Any ideas?

Thank you.

**Comment by christophrumpel** [comment]
I built the FB templates. Could you show me your code so I can try to reproduce the issue?

**Comment by ribb3r** [comment]
I just rewrote the complete conversation class and the issue is solved. Seems that I didn't build the facebook template correctly. However, it was visible in the messenger.

**Comment by christophrumpel** [comment]
ok strange, but great it works now.
