### ISSUE TITLE
URGENT:Telegram accessing message->file_id

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#278]
How do I retrieve the file_id from a telegram message ?

**Comment by LeonAlvarez** [comment]
When u send a photo with Telegram Api u get a Message Response with a photo array of Photosize each one having file_id . Docs https://core.telegram.org/bots/api#photosize

**Comment by kenkit** [comment]
I mean receiving the photo from another user, also how do you retrieve the id from the response.

**Comment by kenkit** [comment]
Switch to the other branch it has almost all the media types
