### ISSUE TITLE
Retrieve sender

### ISSUE THREAD

**Issue by vladimir-yuldashev** [mpociot/botman#28]
Can't find how to retrieve sender User.

**Comment by mpociot** [comment]
Inside the closure, you can now use `$bot->getMessage()->getUser()` to retrieve the sender

**Comment by vladimir-yuldashev** [comment]
@mpociot But it does provide only user's id. No first_name, last_name, username which, for instance, Telegram provides. Facebook also provides something.

**Comment by mpociot** [comment]
You can get the message payload using `$bot->getMessage()->getPayload()` and extract the needed information from there :)
