### ISSUE TITLE
[HELP]Telegram Sendrequest() not sending keyboard

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#280]
The following code is not sending the keyboard, just a hello appears.
```
$keyboard = [
    ['7', '8', '9'],
    ['4', '5', '6'],
    ['1', '2', '3'],
         ['0']
];


		 
$bot->sendRequest("sendMessage", array("text" => 'Hello', 'reply_markup' => array(
  'keyboard' => array($keyboard),
  'one_time_keyboard' => true,
  'resize_keyboard' => true)));	
```

**Comment by kenkit** [comment]
This behaves the same

```
$keyboard = [
    ['7', '8', '9'],
    ['4', '5', '6'],
    ['1', '2', '3'],
         ['0']
];


		 
$bot->sendRequest("sendMessage", ["text" => 'Hello', 'reply_markup' => [
	  'keyboard' => $keyboard,
	  'one_time_keyboard' => true,
	  'resize_keyboard' => true
	  ]
  ]);		 
		 
```

**Comment by LeonAlvarez** [comment]
You need to pass json_encode it

`$keyboard = [
        ['7', '8', '9'],
        ['4', '5', '6'],
        ['1', '2', '3'],
        ['0']
    ];
    $bot->sendRequest("sendMessage", ["text" => 'Hello', 'reply_markup' => json_encode([
        'keyboard' => $keyboard,
        'one_time_keyboard' => true,
        'resize_keyboard' => true
        ])
    ]);`

  And you can use $bot->reply() for that also

**Comment by kenkit** [comment]
Can you give an example of how to use bot reply ?
You assistance is very much appreciated.

**Comment by kenkit** [comment]
Let's say a keyboard string contains a json tring of this format
`{"keyboard":[["7","8","9"],["4","5","6"],["1","2","3"],["0"]],"one_time_keyboard":true,"resize_keyboard":true} `
which is what I retrieved on json encode.
but when I try
```
	if(strlen($keyboard)>1)
		$bot->sendRequest("sendMessage", ["text" => $message_output, 'reply_markup' =>$keyboard ]);
	else
		$bot->reply($message_output);
```
It doesn't work
You implementation using the reply would be a great solution though it would eliminate that loop

**Comment by kenkit** [comment]
It works, I only had to add {} becoz api.ai was removing them from the params, though am waiting from your implementation using the reply.
All I did was
```
if(strlen($keyboard)>1)
		$bot->sendRequest("sendMessage", ["text" => $message_output, 'reply_markup' => "{".$keyboard."}" ]);
	else
		$bot->reply($message_output);
```

**Comment by LeonAlvarez** [comment]
Its nearly the same $bot->reply('TEXT', $extraParameters);

```
$keyboard = [
        ['7', '8', '9'],
        ['4', '5', '6'],
        ['1', '2', '3'],
        ['0']
    ];
$bot->reply($message_output,['reply_markup' => json_encode([
        'keyboard' => $keyboard,
        'one_time_keyboard' => true,
        'resize_keyboard' => true
        ])
    ]);
```

**Comment by kenkit** [comment]
Ok, thanks let me try it.
I made u mistake and put everything in in the $message_output string.

**Comment by LeonAlvarez** [comment]
@kenkit , close Issue if u fixed it.

**Comment by kenkit** [comment]
ooh, my bad.
Thanks for reminding me.
