### ISSUE TITLE
My $loop->run() don't work, why?

### ISSUE THREAD

**Issue by butteff** [mpociot/botman#281]
I have the code:

```
<?php
require 'vendor/autoload.php';

use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotMan;
use React\EventLoop\Factory;

$loop = Factory::create();
$botman = BotManFactory::createForRTM([
    'slack_token' => 'tokenhere',
], $loop);


$botman->hears('hello', function(BotMan $botman) {
	$msg ='hey'.PHP_EOL;
	$botman->reply($msg);
});

$loop->run();
```

But when I execute the script in terminal, $loop->run() don't start to work like an infinity loop. Script just stops very quickly and started to be fully completed. I have nothing in logs. Looks, like I need to switch on something in server's config or php.ini

Any ideas about what can influence on it all?

**Comment by mpociot** [comment]
Have you verified that your Slack token is valid? Maybe the bot can not connect using he token.
