### ISSUE TITLE
Foreach in conversation results in infinite loop

### ISSUE THREAD

**Issue by jozwikp** [mpociot/botman#284]
When I use foreach inside a conversation I end with infinite loop of the method in which I use foreach. Code example:

`
public function askFirstname() {
        $this->ask('Podaj adres strony www', function(Answer $answer) {
            // Save result
            $this->url = $answer->getText();
            
            $this->audyt = new WebsiteAudit('http://' . $this->url);
            $this->auditData = $this->audyt->auditResults;

            $this->say('No to zaczynamy.. ');
            if ($this->audyt->error) {
                $this->say($this->audyt->error);
            } else {
                $this->say('1. Zaczniemy od analizy znaczników META');
                $this->say('Tytuł strony www <title> (' . $this->auditData['metaData']['titleLen'] . ' znaków): ');// . $this->auditData['metaData']['title']);
                $this->say('Opis strony <meta ..> (' . $this->auditData['metaData']['descriptionLen'] . ' znaków): ');// . $this->auditData['metaData']['name-description']);
                
                    $this->say('--');
                    $this->say('Do poprawy:');
                    foreach ($this->auditData['metaData']['errorsMeta'] as $error1) {
                        $this->say($error1);
                    }
                
                $this->askMore1();
            }
        });
    }
`

**Comment by jozwikp** [comment]
I tried with implode function and it also gives me the loop. I think that implode also use foreach.
So no way to foreach on array.

**Comment by mpociot** [comment]
What do you mean by infinite loop? 
I don't really see how this is related to BotMan.

**Comment by jozwikp** [comment]
Thank you for reply.
I mean that my bot is sending over and over the same messages. 
```
 $this->say('No to zaczynamy.. ');
$this->say('1. Zaczniemy od analizy znaczników META');
$this->say('Tytuł strony www <title> (' . $this->auditData['metaData']['titleLen'] . ' znaków): ');
$this->say('Opis strony <meta ..> (' . $this->auditData['metaData']['descriptionLen'] . ' znaków): ');
$this->say('--');
$this->say('Do poprawy:');
```

and never send anything from foreach.

To stop it I have to clear the cache of laravel.
I spend few ours on that and don't know what to do next.

**Comment by jozwikp** [comment]
The same effect you can see when try to do:

```
for($i=0;$i<=10;$i++)
                    {
                        $this->say('test'.$i);
                    }
```

**Comment by mpociot** [comment]
Which driver do you use?

**Comment by jozwikp** [comment]
If you ask about cache driver I use database with mysql configured.

**Comment by christophrumpel** [comment]
Normally a loop with repeating messages sent indicates an error inside your code. Have you checked your logs?

**Comment by jozwikp** [comment]
Sorry but I don't know how to debug code inside conversation. I know that there is something wrong but can't see error message. I use laravel. 
The same code run outside conversation class works fine.

**Comment by christophrumpel** [comment]
Are you using ngrok or valet for your local tunnel? With ngrok there is a web interface where you see all requests. there you could check if there are 500 responses. But the errors should be in your Laravel logs too. If there is an error inside your conversation and your bot starts sending the same reply again and again, then you can clear the cache `php artisan cache:clear` and the responses should stop. If it doesn't it must be something else though.

**Comment by jozwikp** [comment]
ok. I found my mistake. Sorry for this.
