### ISSUE TITLE
Telegram BUG?

### ISSUE THREAD

**Issue by kenkit** [mpociot/botman#288]
Some users username is inaccessible, I noticed this happens especially when user is using a windows phone.
Don't know about others.

Since I couldn't retrieve the actual conversation id from telegram which my chat bot require, I just hex encoded the username.
EDIT:AFTER googling `$bot->getUser()->getId()` Please take some time and document some methods.
The best bot library ever btw thanks for making it.

Here is a sample log.

```
166. USER:Cosm0 CONV_ID:636f736d30 DATE:2017-03-26 09:26:15 :MESSAGE: back BOT REPLY:Main menu
167. USER:Cosm0 CONV_ID:636f736d30 DATE:2017-03-26 09:26:21 :MESSAGE: Fixit BOT REPLY:Please enter the name of the gadget you want to dissassemble/teardown:
Only most common gadget can be found from here, like the ps4, s7
NB:You may have to click on the links of some images to view them.
168. USER: CONV_ID: DATE:2017-03-26 09:26:43 :MESSAGE: back BOT REPLY:Main menu
169. USER: CONV_ID: DATE:2017-03-26 09:27:25 :MESSAGE: Hi BOT REPLY:Howdy
```

My hears is like this 

`$botman->hears("", function (BotMan $bot) `

It catches all the messages received from the client.

**Comment by kenkit** [comment]
Sometimes the bot hangs and is unable to respond to any messages, I am not sure if that is the issue, but it happened especially when I added the bot to a group. Maybe the other datatypes may have caused this ?

**Comment by kenkit** [comment]
I've just sent a photo, but it has not hanged.

**Comment by mpociot** [comment]
Do you know how to reproduce this issue? And how do you access the username?

**Comment by kenkit** [comment]
$bot->getUser()->getUsername();

**Comment by kenkit** [comment]
I can't reproduce them, but am certain with a windows phone you can see what I mean.
Check the logs over here: Sorry I couldn't filter them out
[Link](https://pacific-shore-14311.herokuapp.com/shrouded.php )

**Comment by kenkit** [comment]
Sorry man turns out it's my logging client not accepting certain strings, hence it logs blanks.
Thanks for the help, I noticed that all the users still got their replies.
Please look into the other issues
`insert_chatt_messages($firstName.' CONV_ID:'.$conv_id.' ',$message,$message_output);`

**Comment by kenkit** [comment]
but the bot will still hang at times, maybe am using hears() wrongfully
