### ISSUE TITLE
Fallback always reply when conversing

### ISSUE THREAD

**Issue by CaporalDead** [mpociot/botman#30]
I'm getting some trouble with your lib and slack. 

Using this code :

```
    if (BotMan::isBot()) {
        return null;
    }

    BotMan::hears('hello', function ($bot) {
        $bot->reply('Hello answer ?');
    });

    BotMan::hears('deploy', function ($bot) {
        $bot->startConversation(new \App\DeployConversation());
    });

    BotMan::hears('totem', function ($bot) {
        $bot->startConversation(new \App\TotemConversation());
    });

    BotMan::fallback(function ($bot) {
        return $bot->reply('Fallback answer');
    });

    BotMan::listen();
```

When trying "hello", the only answer I get is "Hello answer" and nothing else : OK.
When trying "deploy", I got the first question (OK) AND the fallback message.
I followed the example you provide in the doc.

I you have any idea.

Thx for your answer and your lib.

**Comment by mpociot** [comment]
Hello,

yes - this was a bug. It's fixed in the latest release.

**Comment by CaporalDead** [comment]
Thx @mpociot
