### ISSUE TITLE
How I can Implement "Account Linking"

### ISSUE THREAD

**Issue by salahy2** [mpociot/botman#303]
Is this possible ?
https://developers.facebook.com/docs/messenger-platform/messenger-profile/account-linking-url

**Comment by mpociot** [comment]
You can just use the curl commands from the official documentation to use account linking. 

To send the login button, use the `GenericTemplate`:

```php
$bot->reply(GenericTemplate::create()
	->addElements([
		Element::create('Account linking')
			->subtitle('All about BotMan')
			->addButton(
                            ElementButton::create('Login')
				->url('https://www.example.com/authorize')
                                ->type('login')
			)
	])
);
```

**Comment by salahy2** [comment]
I am not getting any response when trying type('login')

**Comment by salahy2** [comment]
I tried setting the type of the button to account_link same thing, nothing appears

**Comment by mpociot** [comment]
There was an issue that we were sending the button title to Facebook, when the type was set to `account_link`. It is not allowed for this type.
It's already fixed in dev-master and will be in the next stable release.

```php
$bot->reply(GenericTemplate::create()
    ->addElements([
        Element::create('Account linking')
            ->subtitle('All about BotMan')
            ->addButton(
                ElementButton::create()
                    ->url('https://www.example.com/authorize')
                    ->type('account_link')
            )
    ])
);
```

**Comment by salahy2** [comment]
Please notice theres account_unlink that doesn't take URL
[https://developers.facebook.com/docs/messenger-platform/account-linking/unlink-account](url)
