### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by 0x38** [mpociot/botman#306]
after compiling a project with laravel 
**composer create-project mpociot/botman-laravel-starter botman**

and startup laravel at port 8000
**php artisan serve --port=8000**

this is the message I found all the time
**Sorry, the page you are looking for could not be found.
NotFoundHttpException in RouteCollection.php line 161**

Please can you let me know how to fix it?

**Comment by mpociot** [comment]
Which route are you trying to access?

**Comment by 0x38** [comment]
127.0.0.1:8000

**Comment by mpociot** [comment]
The only route accessible is /botman , as stated in the documentation.
