### ISSUE TITLE
Slack Event API

### ISSUE THREAD

**Issue by TheLegendaryMarcWork** [mpociot/botman#307]
Hello

The Tutorial on your Blog uses the Slack Event API but its outdated:
[http://marcelpociot.de/blog/2016-10-19-write-your-own-slack-bot-using-laravel](http://marcelpociot.de/blog/2016-10-19-write-your-own-slack-bot-using-laravel)
can you tell me how this works in Botman ?

Greetings from Germany
~Marc

**Comment by mpociot** [comment]
Hi,

I'm working on adding this to the documentation and also simplify the steps in the laravel starter project. Sadly Slack makes the whole process quite cumbersome.

**Comment by mpociot** [comment]
@TheLegendaryMarcWork it's now in the documentation: https://botman.io/1.5/configuration#slack

Thankfully Slack dramatically simplified the installation process!

**Comment by TheLegendaryMarcWork** [comment]
wow, thank you very much! you are awesome!

**Comment by mpociot** [comment]
If you read through the documentation and think that something could be improved, like explained in a better way, feel free to submit a PR to the documentation. :)
