### ISSUE TITLE
Sending location using quick replies

### ISSUE THREAD

**Issue by salahy2** [mpociot/botman#311]
I need to ask the user to send me their location, I saw the new update but thats not what I want,I want to use the quick replies.
Any idea how to achieve this ?
https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies - Location

**Comment by salahy2** [comment]
just quick note, I changed this line https://github.com/mpociot/botman/blob/67c7452c1662a532a55e685d26f009ecdab6093e/src/Mpociot/BotMan/Drivers/FacebookDriver.php#L150
to have location instead of text and it worked

**Comment by mpociot** [comment]
You can use one of the many available Facebook templates for this: https://botman.io/1.5/sending#sending-facebook-templates

**Comment by salahy2** [comment]
I think it should be quick replies not just regular button, please check it

**Comment by mpociot** [comment]
I just published a bugfix release 1.5.1 that addresses this issue.
You can use the `additionalParameters` property on the `say`, `reply` and `ask` methods for this:

```php
$this->askForLocation('Please share your location:', function (Location $location) {
    $this->say('Received: '.print_r($location, true));
}, null, [
    'message' => [
        'quick_replies' => json_encode([
            [
                'content_type' => 'location'
            ]
        ])
    ]
]);
```

As you can see, you can pass the additional parameters to the askLocation method, just as you would do in a standard Facebook API request.

**Comment by salahy2** [comment]
Thank you it worked, but I am not receiving anything

**Comment by mpociot** [comment]
Have you imported the `Location` class?
Do you receive an error? I just tested it and pasted this from my example call, so I'm sure it works.

Also, since this is a conversation, which cache driver are you using?

**Comment by salahy2** [comment]
Yes its imported and I am not getting any errors, I cant get anything to be printed inside the callback I tried askForImages also.
Its like the say method is not working inside the callback.

**Comment by salahy2** [comment]
I am using the laravel cache, its files
$botman = app('botman');
$botman->verifyServices(env('TOKEN_VERIFY'));
is it the problem ?

**Comment by salahy2** [comment]
my bad, it was cacheing issue :)

**Comment by mpociot** [comment]
Okay great :)

**Comment by haikajymada** [comment]
Unfortunately in 2021

```
use BotMan\Drivers\Facebook\Extensions\QuickReplyButton;

$question = Question::create('Great. Can you give me your location?')
            ->addAction(QuickReplyButton::create('test')->type('location'));
```

The error caught in **laravel.log**

local.ERROR: Error sending payload: (#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info. {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info. at E:\\laragon\\www\\botman-facebook\\vendor\\botman\\driver-facebook\\src\\FacebookDriver.php:517)
