### ISSUE TITLE
Botman for Twitter

### ISSUE THREAD

**Issue by ahmedash95** [mpociot/botman#315]
@mpociot why there is no driver for twitter ? I could work on it if you want.

**Comment by mpociot** [comment]
Hm..so the bot would listen to what? 
Incoming DMs / mentions?

**Comment by mpociot** [comment]
So there actually is a webhook that allows you to listen for incoming direct messages. But to be honest I do not want to support this in the core of BotMan. 

If you want to build it though, you certainly can publish it as your own package, since BotMan is easily extendable.
