### ISSUE TITLE
Broken Telegram Audio Driver

### ISSUE THREAD

**Issue by SergiX44** [mpociot/botman#319]
The telegram audio driver is not working, actually, an audio is not recognized and the bot go in fallback closure.
```php
// not working
$this->botman->receivesAudio(function ($bot, $audio) {
	$this->beforeCommand($bot);
	if (is_null($this->partner)) return;

	foreach ($audio as $lAudio) {
		/* do something */
	}
});

$this->botman->fallback(function (BotMan $bot) {
	// enter here
});
```

**Comment by mpociot** [comment]
Which file type have you selected? I'm not sure if telegram detects all audio files correctly. 
Im pretty sure that it works with MP3 files

**Comment by SergiX44** [comment]
Oh, vocal audio registered from application, should be .ogg files

**Comment by mpociot** [comment]
Hm not sure about them. Could you try it again with other audio files?

**Comment by SergiX44** [comment]
Ok, mp3 receiving  is working, but is not possible to send them:
![img](https://puu.sh/viXZf/9cc4271418.png)
(download the mp3 and resend back, this code is working for images and videos)

**Comment by mpociot** [comment]
Yeah right, that's currently not possible. I think about either adding a setAudio method or just a generic setFile method. Not sure if every driver supports sending audio.

**Comment by mpociot** [comment]
So first thing I'll do is: extend telegram audio to also accept voice messages. 
After that, a setAudio / setFile method would be great

**Comment by SergiX44** [comment]
Reading about [here](https://developers.facebook.com/docs/messenger-platform/webhook-reference/message#attachment) and [here](https://developers.facebook.com/docs/messenger-platform/send-api-reference#attachment) also facebook api supports the audio messages, I don't know other platforms because i've only developed on telegram and facebook.

**Comment by mpociot** [comment]
Telegram voice messages will now be received by the audio methods too.
I'll see what I can do about sending Audio too
