### ISSUE TITLE
Does not send reply

### ISSUE THREAD

**Issue by jokamjohn** [mpociot/botman#320]
Helo, I have set up the botman project and configured facebook messenger, i can receive messages, but the reply() method does not send a message back to the user.

I have also tried using botman:tinker but  no reply also.

I am using a windows 10 PC

**Comment by mpociot** [comment]
How do you know that you can receive messages?
Is the Facebook page token correct? This is used to reply to messages. Also, you need to be the owner/admin of the Facebook page.

**Comment by jokamjohn** [comment]
I am using ngrok, so i can see the post requests from facebook having the
sent message. I am the owner of the page, also the page token is correct

**Comment by mpociot** [comment]
Can you dump/log something inside your hears method? 
I have BotMan up and running with Facebook myself. 

Please share some code of your BotMan controller

**Comment by jokamjohn** [comment]
I see the log statement in the laravel.log  file.
This is the code

/**
 * Place your BotMan logic here.
 */
   public function handle()
   {
       $botman = app('botman');
       $botman->verifyServices(env('TOKEN_VERIFY'));

       // Simple respond method
       $botman->hears('Hello', function (BotMan $bot) {
           logger("Facebook");
           $bot->reply('Hi there :)');
       });

       $botman->listen();
   }

**Comment by mpociot** [comment]
Can you try and paste the token into the config file directly?
Had this issue once. The only issue remaining could be that the token is either invalid or belongs to a different page than the messenger app?

**Comment by jokamjohn** [comment]
I have tried copying and pasting it, but there is no change and also tried
generating a new token but still failed.
So now I do not know what I am doing wrong

**Comment by jokamjohn** [comment]
Some help. reply not working, Facebook messenger

**Comment by mpociot** [comment]
This must be a config issue. I'll see if I can register my Facebook app again. I just can verify that it works in general

**Comment by mpociot** [comment]
Do you use the facebook_app_secret configuration key? If not, try to remove it from the config and see if it works then.

**Comment by jokamjohn** [comment]
I have removed the facebook_app_secret, but still its not replying

**Comment by mpociot** [comment]
Okay - I just retried this using the Laravel starter project and a new Facebook app.

The webhooks I configured are:
**messages, messaging_account_linking, messaging_optins, messaging_postbacks**

The webhook verification works, and I am also able to send and reply to the bot. I did not modify any code, just configured the webhooks and placed my page token in the `.env` file.

**Comment by jokamjohn** [comment]
I have been on this for a while, have failed to make it reply, even after trying everything mentioned above

**Comment by radium-labs** [comment]
I have the same Issue , i am using ngrok too , i can receive the post but nothing is returned from my server.

**Comment by mario-deluna** [comment]
Same here.

**Comment by mpociot** [comment]
Okay...we just had discussed the issue on our Slack for the last couple of days and it seems that this is in some way related to Facebook.

> I finally fixed my problem with facebook: i've unlinked the app from the page, recreated a test app, link and unlinked the app from the page, removed the test app and relinked to the main app, and now is working, without changing a line of code :triumph:

Can you please try this too? I do not think this issue is related to BotMan.
@mario-deluna @radium-labs @jokamjohn

**Comment by mpociot** [comment]
Closing this for now...reopen if issues still exist and you know how to properly reproduce it.

**Comment by mario-deluna** [comment]
Can confirm:

> I finally fixed my problem with facebook: i've unlinked the app from the page, recreated a test app, link and unlinked the app from the page, removed the test app and relinked to the main app, and now is working, without changing a line of code 😤

Somehow fixed the issue. THX 😊

**Comment by deplop** [comment]
I have the same issue. The ask function seems not fire callback. I just use the example as in the documentation. Here is my code. 
 $config = [
            'facebook' => [
                'token' => Yii::$app->params['page_token'],
                'verification' => Yii::$app->params['verify_token'],
            ],
            'botman' => [
                'conversation_cache_time' => 30
            ],

        ];

        // // Load the driver(s) you want to use
        DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

        // Create an instance
        $botman = BotManFactory::create($config);

        $botman->hears('Hi', function($bot) {
            $bot->reply('Hello!');
            $bot->ask('Whats your name?', function(Answer $answer, BotMan $bot) {
                $bot->reply('Welcome '.$answer->getText());
            });
        });
        $botman->listen();

**Comment by gawielgo** [comment]
Hi everyone,
I also stumbled into this pleasant case and following what you suggests I still can't get the conversation started again.

Would you have any news about it?
