### ISSUE TITLE
Call to a member function all() on null in Mpociot/BotMan/Drivers/BotFrameworkDriver.php:172

### ISSUE THREAD

**Issue by AndreyBobrov** [mpociot/botman#324]
I'm using say() function to send notifications via skype. After 1.5 update I get this error. 
Judging by code, when using say() getPayload() always is null, so getPayload()->all() will no work at all that way. Temporary fixed that by removing ->all() from BotFrameworkDriver.php.

**Comment by mpociot** [comment]
Oh right. This happens only when originating messages. Would you like to create a pull request for this?
So we check if getPayload is a collection/parameter bag?
