### ISSUE TITLE
Accessing the Facebook Page ID in message responses

### ISSUE THREAD

**Issue by ctaylor** [mpociot/botman#329]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

Is there already a function for capturing the Facebook Page ID from incoming responses  ("entry->id") so that it can be stored in the DB? 

{
    "object": "page",
    "entry": [
        {
            "id": "7333947276323",  <strong><----- THIS</strong>
            "time": 1492347891506,
            "messaging": [
                {
                    "sender": {
                        "id": "1344941962246589"
                    },
                    "recipient": {
                        "id": "7333947276323"
                    },
                    "timestamp": 1492347891313,
                    "message": {
                        "mid": "mid.$cAAEpRRKx84VhqCL2cVbdt2uCsoNk",
                        "seq": 77681,
                        "text": "Get Started"
                    }
                }
            ]
        }
    ]
}

### Steps To Reproduce:

**Comment by mpociot** [comment]
Once BotMan has matched an incoming message using hears, you can access the complete incoming request payload using $bot->getMessage()->getPayload()

**Comment by ctaylor** [comment]
Not so fast on closing this! :) I've tried the solution you're proposing. It only returns the "messaging" node of the array. It does not include the id that I pointed out in the sample array above. The ID that belongs to the Facebook page after "Entry".

**Comment by mpociot** [comment]
Oh you're right. That's not possible using a built in method, because this payload is not dependent upon the single matched Facebook message. 
So you would need to access the request payload yourself in that case using a (Symfony) Request object.

**Comment by mpociot** [comment]
So something like:

```php
$request = Request::createFromGlobals();
json_decode($request->getContent());
```

**Comment by ctaylor** [comment]
Yep. That did the trick. Thanks, @mpociot ! 

Now you can close it. ;)

**Comment by mpociot** [comment]
Great!
