### ISSUE TITLE
BotFrameworkDriver say() throws error

### ISSUE THREAD

**Issue by sasureshkumar** [mpociot/botman#332]
- BotMan Version: 1.5.3
- PHP Version:7.1
- Messaging Service(s):BotFramework
- Cache Driver:

<img width="814" alt="screen shot 2017-04-19 at 3 11 40 pm" src="https://cloud.githubusercontent.com/assets/493515/25174277/73ac1c42-2514-11e7-99ed-da6df4c18016.png">
<img width="983" alt="screen shot 2017-04-19 at 3 12 06 pm" src="https://cloud.githubusercontent.com/assets/493515/25174278/73ac3c2c-2514-11e7-9b31-739b41b4f356.png">
<img width="719" alt="screen shot 2017-04-19 at 3 20 31 pm" src="https://cloud.githubusercontent.com/assets/493515/25174276/73aaac68-2514-11e7-9c7d-092a8f515eb7.png">

**Comment by mpociot** [comment]
I just published a new release - 1.5.4 - which fixes this issue.

**Comment by sasureshkumar** [comment]
@mpociot Yes it works perfectly now. Thank you.
