### ISSUE TITLE
Reply only once for the user's message

### ISSUE THREAD

**Issue by yassineaddi** [mpociot/botman#333]
Hello,

I'm wondering if I'm hearing 2 messages (listening for 2 commands) the 1st one is plain text and the 2nd is a regex. Is there any way I can only reply once which means only execute the 1st hears method without executing the 2nd one even if the command matches the regex?

Thanks in advance.

**Comment by mpociot** [comment]
No, right now botman replies to _all_ messages that match - not only the first one.
You could store the information, if the bot replied to the first message somehow globally and check for it in the second hears method.

**Comment by yassineaddi** [comment]
Ok, thank you!
