### ISSUE TITLE
[Proposal] Change how BotMan middleware works

### ISSUE THREAD

**Issue by mpociot** [mpociot/botman#338]
## Proposal

The current middleware implementation of BotMan only gives developers limited to access to how BotMan handles both incoming and outgoing messages.
I think we can improve upon the middleware idea and extend it so that BotMan provides multiple entry-points for middleware.

Instead of having only one `handle` method on the middleware classes, I suggest that BotMan should give access to the various steps in the lifecycle of a bot message.

![botman](https://cloud.githubusercontent.com/assets/804684/25202022/106e685c-2554-11e7-8c76-593769023bb1.png)

### captured
The `captured` middleware method can be used to alter the incoming message before it gets passed to any other logic or conversation.
This could be especially useful inside conversations - right now, middleware do not have access to the conversation flow. So if your user clicks on a message button in your conversation, you could capture this click and add more information to the message.

### received
This is basically what we have right now with the `handle` method.
The message was received by BotMan and regardless if the message matches or not, it can be altered in here.

### matching
This is the current `isMessageMatching` method, where you can define custom matching rules to check for additional message information, like NLP service data.

### heard
Unlike the `received` method, the `heard` method will only be called on messages that actually matched the regular expression / custom matching method.

### sending
This method can be used like a regular HTTP middleware. It receives the outgoing payload that would be sent to the messaging service (Slack, Facebook, etc.) so that it could modify the values.

It would also have a `$next` parameter, which will then send the data to the webservice and return a Symfony Response object. 

Any code after the `$next($payload)` call can be executed. This would be very useful for a logging middleware or various analytics services.

## Feedback
Am I missing something? Is there something we could improve upon? 
Please give me feedback about these changes.

**Comment by andrijdavid** [comment]
Í

**Comment by andrijdavid** [comment]
U

**Comment by andrijdavid** [comment]
Uiuuuuuuuuùuu

**Comment by andrijdavid** [comment]
Uuùuuyu

**Comment by christophrumpel** [comment]
Hey @mpociot , this looks very nice. Let me try to walk through the cases where middleware from BotMan did not work for me yet.

**1. Conversation**

It seems clear that with this new middleware logic it will then be possible to use a middlewhere for every message inside a conversation. Like you mentioned this would be very useful when using NLP platforms.

**2. fuzzy search**

I am using the callback patterns for matching the users message inside the conversation. I want to use fuzzy comparison with every message, before it gets to the matching login. So I need to have the message and the matching patterns to compare them. From what I read I could use the `received` method from here right? But do I also have the patterns there to compare them with the message? I am not sure about that.
