### ISSUE TITLE
Slack complains on interactive conversation - Only Slack Apps can add interactive elements to messages

### ISSUE THREAD

**Issue by serkin** [mpociot/botman#340]
- BotMan Version: 1.4
- PHP Version: 7.0
- Messaging Service(s): Slack

### Description:

Slack complains that I should recreate bot as app

![182ef6c4d6e5b48caa1824dc188b2acd](https://cloud.githubusercontent.com/assets/1589686/25225961/e8a1e27c-25cb-11e7-82cc-33fdc81dc7fc.png)
### Steps To Reproduce:

- Create bot
-  Create simple conversation with questions(I just took it from official documentation)

**Comment by mpociot** [comment]
Yes, that's correct. In order to use interactive buttons with Slack, you need to setup and configure a Slack App.
The necessary steps can be found in the documentation: https://botman.io/1.5/configuration#slack

**Comment by serkin** [comment]
thank you
