### ISSUE TITLE
Integrate Facebook Workplace Driver

### ISSUE THREAD

**Issue by davaxi** [mpociot/botman#341]
## Description:
Add configuration for Worplace Integration: https://developers.facebook.com/docs/workplace/integrations/custom-integrations/bots

**Comment by mpociot** [comment]
That would be great! I'll try to open up a workplace account to integrate it, but I guess it just works with the normal Facebook drivers out of the box.

**Comment by davaxi** [comment]
I just tested using the Facebook driver and replacing `YOUR-FACEBOOK-PAGE-TOKEN-HERE` with `YOUR-FACEBOOK-APP-TOKEN-HERE` and everything works. I do not know if it is better to create a specific driver but all functionality works.

I leave you to choose :) Nevertheless you can now update the documentation to put Facebook Workplace.

I am available if you want more information, because maybe you do not have the possibility to have a Workplace instance to do the tests.

**Comment by mpociot** [comment]
That's great news! Thanks for testing it.
