### ISSUE TITLE
Get response of $bot->reply call

### ISSUE THREAD

**Issue by ribb3r** [mpociot/botman#342]
Hi,

I'm wondering if it's possible to have access to the response object of the `$bot->reply` call. Internally, it will make a `$this->http->post` that returns a `Symfony\Component\HttpFoundation\Response`.

Is this possible?

Thank you.

**Comment by mpociot** [comment]
Not right now. It will be possible in the next version though.

**Comment by amitailanciano** [comment]
came here to post this, is there anything we can do in the meantime to determine if the reply failed for whatever reason?

**Comment by mpociot** [comment]
@amitailanciano Sorry, it's currently not possible to access the value. It will be possible in the next version.
