### ISSUE TITLE
(feature request) Include the message id on the Message object by default (maybe in extras property?)

### ISSUE THREAD

**Issue by amitailanciano** [mpociot/botman#348]
- BotMan Version: 1.5
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: File

### Description:

Would be great to have access to the message ID (`mid`) on the Message object by default -- it seems if a bot doesn't reply quickly enough to a message, Facebook will post another request with the same message ID a few times before "giving up", which could potentially build up a back stack of replies. Having access to the message ID would provide the means necessary to handle the issue.

**Comment by mpociot** [comment]
Can't you access it using `$bot->getMessage()->getPayload()` ?

**Comment by christophrumpel** [comment]
I had this "issue" too with a chabot project. We ended up checking the mid if it is the same like before, if it is we do not send it through. (Was a project without BotMan) Also think you should get it like @mpociot mentioned.

**Comment by amitailanciano** [comment]
@mpociot sorry I forgot to follow up on this one, I was able to get it off the payload, thanks for the tip; it seems it wasn't much use anyway though, because postbacks don't have an `mid`
