### ISSUE TITLE
Is ->listen() a blocking call ?

### ISSUE THREAD

**Issue by jayesbe** [mpociot/botman#357]
Im trying to understand how to best integrate botman into my app.

Is ->listen() a blocking call ?  Should I make a CLI initiated script?

Or should I ->listen() inside of a Request Controller ?

**Comment by SergiX44** [comment]
Yes it's blocking, and should be used inside a controller from a webhook and not from cli (polling is not supported).

**Comment by mpociot** [comment]
Polling is only supported where messaging services also support it. 
The Slack RTM API can *only* be used through CLI.
See: https://botman.io/1.5/configuration#slack At "Usage with the Realtime API"

All other services work with webhooks and can only be used from within a controller.
