### ISSUE TITLE
How can I capture unaccounted intents and reply 

### ISSUE THREAD

**Issue by gunify** [mpociot/botman#364]
BotMan Version: 1.5
PHP Version: 5.6.30
Messaging Service(s): Facebook
Cache Driver: default

### Description:
How can I still capture and respond to something I'm not listening for? I would like to reply with something like "Sorry, I didn't understand that. Say things like: balance, last payment"

### Steps To Reproduce:

**Comment by mpociot** [comment]
There is a fallback method for this exact use case: https://botman.io/1.5/receiving#fallbacks

**Comment by gunify** [comment]
Great. Thanks again for the immediate help.
