### ISSUE TITLE
Question answer not being captured. Goes directly to fallback

### ISSUE THREAD

**Issue by gunify** [mpociot/botman#370]
BotMan Version: 1.5
PHP Version: 5.6.30
Messaging Service(s): Facebook
Cache Driver: default

### Description:
My answer is not being captured.  I extended the conversation class and my question is asked but the answer is hitting my fallBack. 

### Steps To Reproduce:
`<?php
namespace Mpociot\BotMan;
use Mpociot\BotMan\Conversation;

class RequestCallback extends Conversation
{
    protected $phonenumber;
    
    public function askPhoneNumber()
    {
        $this->ask('What is your callback phone number?', function(Answer $answer) {
            // Save result
        	$this->phonenumber = $answer->getText();

           	$this->say('Your phone number is '.$this->phonenumber);
        });
    }

    public function run()
    {
        // This will be called immediately
        $this->askPhoneNumber();
    }
}
`
Any tips?

**Comment by mpociot** [comment]
You need to use a persistent cache, because conversations get stored in the cache.

**Comment by vdomah** [comment]
> You need to use a persistent cache, because conversations get stored in the cache.

Can you please tell how to use that persistent cache? I got same problem and googling about persistent cache didn't help me
