### ISSUE TITLE
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by bilalvdemir** [mpociot/botman#375]
- BotMan Version: 1.5.0
- PHP Version: 7.0.6
- Messaging Service(s): Facebook Messenger Bot 
- Cache Driver: 

### Description:

I'm done all step with this video: https://www.youtube.com/watch?v=ll-QC9h9KxE
But when setup webhooks I get some error. At Uniform Server Zero, I set my apache http port 8080, when visit my bot page getting this error;

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in C:\Users\Bilal\Desktop\UniServerZ\www\dearbot\vendor\mpociot\botman\src\Mpociot\BotMan\DriverManager.php on line 40

My PHP version 7.0.6,
Thanks.
### Steps To Reproduce:

**Comment by mpociot** [comment]
Are you sure that you're running PHP 7? 
This sounds like it's using an old PHP version instead.

**Comment by bilalvdemir** [comment]
yes you ara true. My php older version. Php 5.4 already installed in uniform server zerı XI 11_0_10. But when I try new version my localhost give me Error Conection Refused!
Can I use for local host Xampp?

**Comment by bilalvdemir** [comment]
Hi I'm solve this problem with 11_8_2_ZeroXI.exe and ZeroXI_php_5_6_16_p.exe this package use for me wonderful.

Thanks.
