### ISSUE TITLE
Facebook reply not working

### ISSUE THREAD

**Issue by u-michiel** [mpociot/botman#378]
- BotMan Version: commit f835317

### Culprit:
Commit 0ae8155a66af41590455c8f7d0786a3e1d3d5291

### Description:
We are working on the master branch because we need the fb referral events for a project.
Commit 0ae8155a66af41590455c8f7d0786a3e1d3d5291 breaks reply functionality.

### Steps To Reproduce:
Simple reply statement on any "hears" listener.

Reverted back to previous commit 05b3ca2a2479e3e3667cea29065c7ebe2b4142f8 and reply is immediately working again.

**Comment by mpociot** [comment]
I reverted the commit, it's working again :)
