### ISSUE TITLE
ApiAi middleware broken

### ISSUE THREAD

**Issue by u-michiel** [mpociot/botman#379]
- BotMan Version: commit f835317

### Description:

Getting error: undefined index 'apiAction' on line 138 in ApiAi.php

```
            return (bool) preg_match($pattern, $message->getExtras()['apiAction']);
```

### Steps To Reproduce:

```
$botman->hears('ai_action', function (BotMan $bot) {
    ...
})->middleware(ApiAi::create(env('API_AI_TOKEN'))->listenForAction());
```

**Comment by mpociot** [comment]
This issue is related to the new middleware system proposed here: https://github.com/mpociot/botman/issues/338

You need to enable the ApiAI middleware on "receiving" messages too:

```php
$apiAi = ApiAi::create(env('API_AI_TOKEN'))->listenForAction();

// Apply global "received" middleware
$botman->middleware->received($apiAi);

// Apply matching middleware per hears command
$botman->hears('ai_action', function (BotMan $bot) {
    ...
})->middleware($apiAi);
```

**Comment by u-michiel** [comment]
Ok thanks, I used the docs on the master branch. I'll edit them and do a pull request!

**Comment by mpociot** [comment]
Thank you! I haven't found the time to properly document all upcoming changes for the next version, which will be 2.0!
