### ISSUE TITLE
Question object vs. String in ask-Function (Telegram Custom Keyboard)

### ISSUE THREAD

**Issue by blankster** [mpociot/botman#381]
- BotMan Version: 1.5.5
- PHP Version: 7.0.9
- Messaging Service(s): Telegram
- Cache Driver: Doctrine

### Description:
First of all, thanks a lot for this great library. In general it works very well. 

At the moment I'm struggling a little bit with custom keyboards of Telegram (are others also supporting them?). They work nice if I send it via reply() or sendRequest(). If I use ask() then they only work if I don't use a question object (what passes it then later to reply).  Am I overlooking something or aren't custom keyboards working when a question object is used? What exact advantages have question object over not using them? Documentation in this area would be very nice and useful...

### Steps To Reproduce:

#Not working

...
```
$keyboard = [['7', '8', '9'], ['4', '5', '6'], ['1', '2', '3'], ['10']];
$question = Question::create('How are you feeling today?');
$this->ask($question,
function (Answer $answer)
	{

	// next

	someFunction();
	}

, ['reply_markup' => json_encode(['keyboard' => $keyboard, 'one_time_keyboard' => true, 'resize_keyboard' => true]) ]);
```
...

#Working

```
$keyboard = [['7', '8', '9'], ['4', '5', '6'], ['1', '2', '3'], ['10']];
$this->ask('How are you feeling today?',
function (Answer $answer)
	{

	// next

	someFunction();
	}

, ['reply_markup' => json_encode(['keyboard' => $keyboard, 'one_time_keyboard' => true, 'resize_keyboard' => true]) ]);
```

**Comment by mpociot** [comment]
The `Question` object is useful if you want to use built-in buttons.
So you can do something like this:

```php
$question = Question::create('How are you feeling today?');
$question->addButtons([
            Button::create(Great')->value('1'),
            Button::create('Super')->value('2'),
        ]);
```

But since you are already using a custom keyboard through the custom `reply_markup` you can not mix these two.
