### ISSUE TITLE
how can I develop and test my chatbot if my webhook is already in live production?

### ISSUE THREAD

**Issue by vesper8** [mpociot/botman#385]
I hope I'm making sense with this question.

I have set up botman and it's on my production server.. the webhook is set up and everything is working. I am able to communicate with it via my own messenger and so are my app's users.

Now I am used to testing everything in a safe sandboxed environment.. and I am confused what is the best workflow for achieving this since I can only set up one webhook, and I assume that this webhook only works with a real https url too.

I do use Valet and I know it can use ngrok (which honestly I have never used before). But even if I do get this to work.

Is the best workflow then to create a new facebook page, set up a new webhook and match it with my dev using ngrok? I guess this won't be testing THE actual chatbot that my production app uses.. but it will be just the same. Am I missing something? Is this the way or is there another easier way?

Would be nice if there was a short guide of how to set this up somewhere to work with Laravel Valet.

Many thanks!!

**Comment by vesper8** [comment]
ah man I feel bad now it seems you do go over most of my questions here https://github.com/mpociot/botman-docs/blob/master/configuration.md

And I found this nice post too http://christoph-rumpel.com/2017/01/Setup-a-messenger-chatbot-in-laravel/

I guess the only thing that's not super clear is whether I have to create a 2nd "test" page in order to setup the webhook that talks to my dev. I imagine that I do since there seems to be no way to add multiple urls when setting up the webhook.

If you think I missed anything let me know otherwise can close this.

Thanks and didn't mean to waste your time. Really looking forward to 2.0!

**Comment by mpociot** [comment]
Yes you're right. For Facebook it is not possible to configure multiple webhooks for one page/bot. 
So you would need to setup a second page and connect it with your dev system. 
I don't think there's any other possible solution for this.

**Comment by robertdziu** [comment]
my bot starts on special word that start converstation class, in this case you can use one webhook changing conversation class name for testing and hard-to-quess testing starting word ;)
