### ISSUE TITLE
[Feature Proposal]Emoji Support

### ISSUE THREAD

**Issue by blankster** [mpociot/botman#391]
It would be really nice if short-codes (or even auto-transforming of text based emoticons) to Unicode would be supported. Personally I made good experiences with https://github.com/emojione/emojione. IMHO emoticons are in the bot context quite important. Is there a chance you will integrate something like this?

**Comment by mpociot** [comment]
What exactly do you want to do? You want to transform outgoing short-codes into the emojis?
So you can do:

```
$botman->hears('foo', function($bot) {
    $bot->reply(':hear_no_evil:');
});
```

**Comment by blankster** [comment]
I want to display emojis in the chat conversation. I'm using Telegram desktop client for my development. When I use the following code, then I get the following result:

code:
```
$this->botman->hears('(hello|hi|ciao|hoi|salut)', function (BotMan $bot) {
    $user = $bot->getUser();
    $message = 'Hi '. $user->getFirstName() . ' :slight_smile:' ;
    $bot->reply($message);
});
```

Telegram:
![screenshot_botman](https://cloud.githubusercontent.com/assets/1443109/26313058/fac47454-3f09-11e7-893b-36c82623fd21.png)

What am I doing wrong? Is this also a 1.5.x problem only and fixed in the next release?

**Comment by mpociot** [comment]
Oh okay. Well can't you just use an emoji in your code? Should work just fine :)
My guess would be, that it depends on the driver API (Telegram in your case) if they auto convert the emojis or not.

**Comment by blankster** [comment]
It works when I use Unicode chars directly. That's also the reason why I was asking for short codes support. What I'm doing atm is:

1.  Using short names in my texts
2. "Tunneling" converting these texts with a helper function and the Emojione library to HTML
3. Convert the HTML to the Unicode strings with the same helper function
4. Using this return value for BotMan and for example then the reply/ask/say-functions.

**Comment by mpociot** [comment]
I suppose that you save / load those short name texts from the database?
So I thought about this quite long yesterday and I do not think that this should be a part of BotMan.

I had the idea of adding a new middleware that can alter the outgoing message/question - but what's the real usage of this? 
You could just store the emojis as Unicode characters in your database and reply them.
Adding a new middleware would only complicate things plus you could already do this with the upcoming middleware system by directly replacing strings in the outgoing message payloads.

So I would say that you would either need to "tunnel" the texts before giving them to the reply method, as you do right now. Or save them as Unicode characters to the database in the first place.
