### ISSUE TITLE
Add Glip support 

### ISSUE THREAD

**Issue by anilkumarbp** [mpociot/botman#397]
Do you plan on implementing a driver for [Glip](https://glip.com/)
- I have put in a PR for the same ( #398 ) . Kindly let me know your thoughts on it.   

Thanks for your time.

**Comment by mpociot** [comment]
First of all, thank you for the PR and the work you put in it.

I don't plan to add new drivers to the core. The next 2.0 release will add Kik support, as it's a pretty huge bot-platform, but other than that I do not really want to have more drivers in the core, as it slows down feature development.

Feel free to distribute the driver as a standalone-package as it will be great for Glip developers!

**Comment by anilkumarbp** [comment]
Thanks @mpociot ! 

Per your suggestion, I have my `driver` as a standalone package but when I try to load the driver using:
`DriverManager::loadDriver(CustomDriver::GlipDriver);`

It prepends my custom driver class into the available driver's list ( in the instance of `DriverManager` but I am thrown off by the error:

```
Class 'Mpociot\BotMan\GlipDriver' not found in /Users/anil.kumar/GitHub/Botman-Glip/vendor/mpociot/botman/src/DriverManager.php:183
Stack trace:
#0 /Users/xxxxx/GitHub/Botman-Glip/vendor/mpociot/botman/src/BotManFactory.php(44): Mpociot\BotMan\DriverManager->getMatchingDriver(Object(Symfony\Component\HttpFoundation\Request))
#1 /Users/xxxxx/GitHub/Botman-Glip/index.php(40): Mpociot\BotMan\BotManFactory::create(Array)
#2 {main}
  thrown in /Users/xxxxx/GitHub/Botman-Glip/vendor/mpociot/botman/src/DriverManager.php on line 183
```
Would appreciate any thoughts on how I could pass in the stand alone driver into the instance of `DriverManager`: 

 Below is the code to implement my driver:

```
DriverManager::loadDriver(GlipTest::class);
$botman = BotManFactory::create($config);
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself dude.');
});
$botman->listen();
```
Thank you again for your time !

**Comment by mpociot** [comment]
@anilkumarbp maybe you need to change the namespace of the driver? As it is looking for `Mpociot\BotMan\GlipDriver` but this might not be what you have in your autoloader.

**Comment by anilkumarbp** [comment]
I agree. But then I would need to use the Driver inside `DriverManager.php` as 
`use Mpociot\Botman\GlipDriver` 

All I am trying to do is use `Botman` library and my standalone library ( custom driver ) and integrate the two without having to include a dependency of my custom driver inside the `botman` library. 

You think this is feasible?
