### ISSUE TITLE
[Question] Did anybody implemented livechat using Botman?

### ISSUE THREAD

**Issue by softnayr** [mpociot/botman#399]
I'm wondering if anybody ever tried/implemented live chat using this awesome project? If so, please tell us what tools/packages you used. I'm looking at using Botman as endpoint for my Facebook Messenger bot such that when a Facebook user initiates a chat through the bot on my FB page, I will be able to receive the message in Botman and have a live chat thereafter.

Any thoughts?

**Comment by mpociot** [comment]
So you want to intercept the incoming messages and stop the bot from receiving and manually continue the chat? Or what do you want to do exactly?

**Comment by softnayr** [comment]
Yes something like that. So the bot will act as the endpoint and then there is the operator who will manually reply to messages.

**Comment by SergiX44** [comment]
I'm doing something similar, mine it's like a message gateway between different platforms. All messages sent by users should be captured (maybe using the method `fallback(function(){...})`, so you can get all messages thats not match commands) and stored in a database, so you can show that in your custom operator interface, when operator reply (store the response in the database, so you can track the original conversation) and sent back to the user using the `say(...)` method, to "originate" a message from the bot to the user.

**Comment by softnayr** [comment]
Similar to that indeed. I'm just wondering how to extract the data that botman hears. The next thing would be how to process the data to and from the database in real-time. 

@SergiX44 do you store the chats to the database also? If so how do you get the database data in real-time? Im thinking about using websockets and angularjs to get around with it.

**Comment by mpociot** [comment]
@softnayr you can extract it using a simple wildcard hears method:

```
$botman->hears('(.*)', function($bot, $message) {
   // user said $message
});
```

Regarding the realtime feature, you should take a look at pusher.com or implement the socket yourself.

**Comment by softnayr** [comment]
Thanks @mpociot . That's what I'm looking for. I will look at both options for the real-time feature. 
I'm looking at starting this as an opensource project with Laravel backend. Or, how about as an added feature to the Botman Laravel Boilerplate? I could start it. It could be useful for social media managers.

**Comment by mpociot** [comment]
@softnayr let's talk about this on Slack? I do have a few ideas that I want to implement in the boilerplate project myself.

**Comment by dextervip** [comment]
@softnayr did you succeed implementing live manual chat? If so, may I know what approach did you take?

**Comment by kvarnagit** [comment]
I'm looking for a way to have a live operator to jump into the bots flow and help the user if needed. My first ide was to have it hooked into intercome but feels very mutch like cake on cake, thoee.. intercom has a way of handleing customer tickets....

Any conclusions here? @softnayr @dextervip 

Cheers!

**Comment by christophrumpel** [comment]
The most simple way to handle this (with a messenger like FB, Telegram etc.) is to be able to `deactivate` the bot when needed. I built something where the user can decide to `talk to a home`, it is a button or message that triggers deactivating the bot for this users. in the back, I store the users ID and now store a flag for deactivating. With a middle I check every outgoing message and only send for `not deactivated users`. 

The deactivation process is also triggered with a notification to the team, so that they know the user wants to talk to a human. After that, the team member activates the user again. In my case through switching the flag in the DB table. Hope this helps.

**Comment by Roman7799** [comment]
Hi @christophrumpel Do you have your implementation of this triggers open source????
can you add me to Telegram @geolance I have couple questions how you did it?  Thanks

Thanks

> The most simple way to handle this (with a messenger like FB, Telegram etc.) is to be able to `deactivate` the bot when needed. I built something where the user can decide to `talk to a home`, it is a button or message that triggers deactivating the bot for this users. in the back, I store the users ID and now store a flag for deactivating. With a middle I check every outgoing message and only send for `not deactivated users`.

The deactivation process is also triggered with a notification to the team, so that they know the user wants to talk to a human. After that, the team member activates the user again. In my case through switching the flag in the DB table. Hope this helps.

**Comment by christophrumpel** [comment]
Hey, sry no this is not available. It belongs to my old company =/

But basically, it is just a BotMan middleware that checks a field of the user in DB. It's a `active flag`. If the user is  `inactive` I don't return from the middleware.

**Comment by AvneetSingh27** [comment]
> @softnayr you can extract it using a simple wildcard hears method:
> 
> ```
> $botman->hears('(.*)', function($bot, $message) {
>    // user said $message
> });
> ```
> 
> Regarding the realtime feature, you should take a look at pusher.com or implement the socket yourself.

how to implement socket in botman. what will be the flow of conversation??

**Comment by AvneetSingh27** [comment]
> I'm looking for a way to have a live operator to jump into the bots flow and help the user if needed. My first ide was to have it hooked into intercome but feels very mutch like cake on cake, thoee.. intercom has a way of handleing customer tickets....
> 
> Any conclusions here? @softnayr @dextervip
> 
> Cheers!

did you implemented the live chat feature? if yes can you help me out doing that 
I am wondering how to do that?
