### ISSUE TITLE
capture message in fallback

### ISSUE THREAD

**Issue by renlight10** [mpociot/botman#402]
hi, is possible to capture message in fallback ?
I'm looking for similar to
```
$botman->fallback(function($bot,$msg){
$bot->reply("I don't understand what you talking about ".$msg);
});
```
while code above won't work, thanks

**Comment by mpociot** [comment]
You were close:

https://botman.io/1.5/receiving#fallbacks

You can get the message in the fallback using `$bot->getMessage()`.
