### ISSUE TITLE
Integration with Silex 2

### ISSUE THREAD

**Issue by meradoou** [mpociot/botman#404]
- BotMan Version: 1.5
- PHP Version: 7.0
- Messaging Service(s): Messenger

### Description:
I use Silex on my project and I would like to integrate botman but It doesn't work. Verification step works but hears & listen.

### Steps To Reproduce:
```
<?php
$app = new \Silex\Application();

$app['botman'] = function () {
    return  BotManFactory::create([
        'facebook_token' => FACEBOOK_TOKEN,
        'facebook_app_secret' => FACEBOOK_HUB_CHALLENGE
    ]);
};

$app->get('/', function ($app, $request) {
      return $app['botman']->verifyServices(FACEBOOK_HUB_CHALLENGE);
});

$app->post('/', function ($app, $request) {
            $app['botman']->hears('bonjour {name}', function ($me, $name) {
                $me->reply(sprintf('Bienvenu %s', $name));
            });
            $app['botman']->listen();

            return 'hello world';
});

$app->run();
```

**Comment by mpociot** [comment]
I haven't used Silex yet, but why is `$app['botman']` a closure and not the actual instance?

**Comment by meradoou** [comment]
Service https://silex.sensiolabs.org/doc/2.0/services.html

**Comment by mpociot** [comment]
I just tried it locally using Slack and it works for me.

I used the Silex Skeleton, so my code looks a bit different:

```php
$app->post('/', function () use ($app) {
    $app['botman']->hears('bonjour {name}', function ($me, $name) {
        $me->reply(sprintf('Bienvenu %s', $name));
    });
    $app['botman']->listen();

    return 'hello world';
});
```

Could you try and log this inside the post closure:
`$app['botman']->getDriver()`

This should be an instance of the FacebookDriver.

Maybe your facebook token is wrong? Are you the admin of the facebook page?

**Comment by meradoou** [comment]
NullDriver. Yep, I'am the admin of the facebook page. It works outside Silex

**Comment by mpociot** [comment]
Okay - `NullDriver` means that BotMan did not detect the incoming request data to be from Facebook.
Are you sure your Facebook app secret is the same as your verification key?

**Comment by meradoou** [comment]
I regenerate token and it works
