### ISSUE TITLE
Docs need upgrade

### ISSUE THREAD

**Issue by IgorDePaula** [mpociot/botman#42]
In laravel, what route|middleware|controller I use?

**Comment by mpociot** [comment]
It's best if you create a POST and GET route that doesn't use the CSRF token middleware. 
You can place the BotMan logic in any controller you want.

**Comment by mpociot** [comment]
Take a look at the Laravel boilerplate project: https://github.com/mpociot/botman-laravel-starter

**Comment by IgorDePaula** [comment]
Thank you

Em 08/12/2016 19:32, "Marcel Pociot" <notifications@github.com> escreveu:
