### ISSUE TITLE
(Optionally) Wrap Messages in a Message Object for additional payloads

### ISSUE THREAD

**Issue by sschlein** [mpociot/botman#48]
I'd like to have the possibility to send images.

Keeping the current API, we could check if the message is a Message Object or the current string and handle them separately.

```
$message = Message::create([
    'text' => 'Have a look at this wonderful image',
    'image' => 'http://placepenguin.com/500/250'
]);

$message = Message::text('Have a look at this wonderful image')->image('http://placepenguin.com/500/250');

$botman->say($message);
```

I think it's also worth the idea to have an image parameter which holds the data of the image or just an URL where the image is located.

**Comment by mpociot** [comment]
We already have a `Message` object, which is used for the incoming messages.

So we either rename the existing class or create a new `OutgoingMessage` class (or with a different name).

The different drivers then would need to parse the messages into the driver-specific API requests (if available).
