### ISSUE TITLE
No answer for a Conversation

### ISSUE THREAD

**Issue by khaledelmahdi** [mpociot/botman#51]
Hi,

First, thank you for this great package.

I have this conversation class:
```
<?php
namespace App\Conversations;

use Mpociot\BotMan\Answer;
use Mpociot\BotMan\Conversation;
use Mpociot\BotMan\Question;

class IntroductionConversation extends Conversation
{
    protected $name;

    protected $email;

    protected $phone;

    public function askName()
    {
        $question = Question::create('Can I get your name please?')
            ->fallback('Unable to ask question')
            ->callbackId('ask_name');

        return $this->ask($question, function (Answer $answer) {
            $this->name = $answer->getText();
            $this->say('Nice to talk to you ' . $answer->getText());
        });
    }

    public function askEmail()
    {
        $question = Question::create('Can I get your email address please? You can say No if you wish to get phone calls notifications.')
            ->fallback('Unable to ask question')
            ->callbackId('ask_email');

        return $this->ask($question, function (Answer $answer) {
            if (str_contains($answer->getText(), ['nah', 'no', 'nope'])) {
                $this->say('That\'s fine, I\'ll ask you later if I need it');
            }
            $this->email = $answer->getText();
            $this->say('Don\'t worry. I\'ll never spam you!');
        });
    }

    public function askPhone()
    {
        $question = Question::create('Can I get your phone number please? You can say No if you don\'t wish to receive emails from me.')
            ->fallback('Unable to ask question')
            ->callbackId('ask_phone');

        return $this->ask($question, function (Answer $answer) {
            if (str_contains($answer->getText(), ['nah', 'no', 'nope'])) {
                $this->say('That\'s fine, I\'ll ask you later if I need it.');
            }
            $this->phone = $answer->getText();
            $this->say('Don\'t worry. I\'ll not wake you up on the middle of the night ;)');
        });
    }

    /**
     * Start the conversation
     */
    public function run()
    {
        $this->askName();
        $this->askEmail();
        $this->askPhone();
    }
}
```

When I initiate this conversation with `$bot->startConversation(new IntroductionConversation);` (in my case I am using Facebook messenger) all I get is the 3 questions directly. 
![screen shot 2016-12-13 at 16 43 02](https://cloud.githubusercontent.com/assets/9323496/21149423/5a6048be-c153-11e6-9639-1f7edaf4d8e7.png)

On the run method, if I only keep the `askName` and remove the other two, I get the question, but when I answer it on messenger nothing happen.

Can any one help please...

**Comment by mpociot** [comment]
Hi!

First of all, can you tell me how you use BotMan? Is it inside a Laravel application or is it a different framework?

**Comment by khaledelmahdi** [comment]
Hi,

I am using it inside Laravel 5.3

**Comment by mpociot** [comment]
Ah i see what the problem is. 
If you use BotManFactory::create it will not use a persistent cache driver. 
If you need multiple BotMan instances, please pass the LaravelCache to the BotManFactory. 

You can find an example code inside the service provider.
https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotManServiceProvider.php

This will then use the default cache you configured to store conversations. 

To trigger multiple questions one after another, place the "ask..." methods inside the answer closures of each function, so that you start with only asking one question.

Let me know if this works for you :)

**Comment by khaledelmahdi** [comment]
Hi,

Thank you very much. I changed the code in the BotController to be like this:
```
$botman = BotManFactory::create($config, new LaravelCache());
```

All working fine now. Seeing my code, do you think there is a better way to initial the bot instance?

Thank you again for your help.

**Comment by mpociot** [comment]
Great!

Not much, you could simplify it and load the config using your model.
Something like this:

```php
$botman = BotManFactory::create($this->dbbot->toArray(), new LaravelCache());
```

Let me know, once you've built a bot with this package :)
