### ISSUE TITLE
Support the realtime bot API

### ISSUE THREAD

**Issue by ssx** [mpociot/botman#54]
Great library, I'm looking at using the Slack realtime bot API, whereas botman seems to be geared to the webhook type of integration in/out.

Is it possible to use this library in the same way as jclg/php-slack-bot for example?

It looks so, by running with slack_token in the config, but when running the Slack example, the $botman->listen() just exists and doesn't connect/listen - it's highly likely I may have missed something.

**Comment by mpociot** [comment]
Hi,

no - currently BotMan only works by using Webhooks to connect with the various services. I'm not sure if it's possible to use the real-time bot API with this library, as it would require the PHP process to keep running.

When using webhooks, BotMan only gets called whenever a webhook calls the BotMan controller.

So you haven't missed anything, I'm just not sure that this is possible with BotMan (and if even PHP might be the right tool for this, when you need long-running processes).

**Comment by ssx** [comment]
Exactly what I'd thought, not a problem, thank you again! :)

**Comment by marcusmoore** [comment]
Hello,

If I'm understanding correctly, we can set up Botman to work with the [Events API](https://api.slack.com/events-api) but not the [Real Time Messaging API](https://api.slack.com/rtm)? If that is the case, it might be a good idea to clarify that in this package's [Slack Readme](https://github.com/mpociot/botman/blob/master/readme-slack.md#use-a-bot).

I would submit a PR but I'm not positive I'm correct.

**Comment by mpociot** [comment]
Yes this is correct! It can only use the events API.

**Comment by mpociot** [comment]
Reopening this as a new feature. 

I already have a local branch with an existing RTM API Slack driver, but still need to implement conversation buttons. 🎉 

So this will be possible soon

**Comment by ssx** [comment]
Brilliant news, thanks @mpociot

**Comment by mpociot** [comment]
The Slack Realtime API is now supported with release 1.2.0!
See the changelog, Slack readme and laravel starter project for additional details (https://github.com/mpociot/botman-laravel-starter)
