### ISSUE TITLE
[Laravel] Set configuration programmatically

### ISSUE THREAD

**Issue by SergiX44** [mpociot/botman#56]
Great library!
But, maybe I missed something. I see that the config for the botfactory is passed as a simply array with plain PHP, but with Laravel, it's hardcoded in the services.php.
I need to manage different tokens with different webhooks (simply, different bots that appears differently but work the same way with the same backend). it's possible to implement something like this with this library?

**Comment by mpociot** [comment]
Sure! All you need to do is create the BotMan instance yourself, not using the service provider. 

So it would be :

```php
$botman = BotManFactory::create($yourConfig, new LaravelCache());
```
