### ISSUE TITLE
Bot does not listen very well :D

### ISSUE THREAD

**Issue by jeroengerits** [mpociot/botman#60]
I think this only happens with replies. I did not had this issue with conversations. I use Telegram as a provider.

![screenshot from 2016-12-16 00-32-06](https://cloud.githubusercontent.com/assets/808734/21246143/20c71d5a-c327-11e6-91f9-65b2e60e2121.png)
![screenshot from 2016-12-16 00-30-57](https://cloud.githubusercontent.com/assets/808734/21246144/20c72aac-c327-11e6-9bfd-4b1010f2489b.png)

**With two methods in the controller...** 

![screenshot from 2016-12-16 00-35-50](https://cloud.githubusercontent.com/assets/808734/21246238/b51858b6-c327-11e6-8a25-5e64bb2c5ecf.png)
![screenshot from 2016-12-16 00-37-39](https://cloud.githubusercontent.com/assets/808734/21246260/e0080bc0-c327-11e6-97b3-c910fa511f32.png)

Nothing wrong in logs

**Comment by mpociot** [comment]
Ah...this is related to a custom middleware. 
The "isMessageMatching" method completely replaces the regular expression match method. If the middleware returns true, all messages are matching and will be processed. 

Hm...but it might also be necessary to use a completely customized matching logic. 
In the meantime, you can place this inside your middleware to retain that logic. 

https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L217-L218

This is causing the problems.

**Comment by mpociot** [comment]
Hi Jeroen,

I fixed this on `dev-master` - see this commit: https://github.com/mpociot/botman/commit/707789c1e8626f4ec5d8cfc8218ccaec15d96d0d


### Changed
- Middleware classes now receive a third parameter `$regexMatched` inside the `isMessageMatching` method. You can use
this method to determine if the regular expression was also matched, in case you do not want to replace the complete
`hears` logic, but only add custom logic to it. **Note:** This will require you to modify your custom middleware classes.


---
So in your specific example, you might check for your custom authorization logic and in addition to that, check that `$regexMatched` is true as well. Pretty much like this: https://github.com/mpociot/botman/blob/master/tests/Fixtures/TestMatchMiddleware.php#L31

This should give us the flexibility of using a completely custom hears logic as well as simply adding additional checks to it.

**Comment by mpociot** [comment]
Let me know if you still encounter this issue. Closing this as fixed for now :)

**Comment by jeroengerits** [comment]
Thanks so far Marcel, did not have any time this week to pick this up. I will soon :D
