### ISSUE TITLE
Slack's interactive messages without conversation

### ISSUE THREAD

**Issue by mcretien** [mpociot/botman#65]
Hi,

I would like to use buttons-based actions but without having to build conversations e.g:

- user says something
- bot hears it and using `reply`function, returns some data + buttons
- user clicks one of the buttons which will then do something

I might have missed something but I can't see how to do the above by just using the `reply`function as it doesn't have any callback to execute `isInteractiveMessageReply` like `Answer` object has.

Thanks
M

**Comment by shadowair105** [comment]
Hi, I came into the same trouble.
How did you solve this?
