### ISSUE TITLE
Telegram conversation answer stalls if the answer is a url

### ISSUE THREAD

**Issue by davetosh** [mpociot/botman#66]
If you ask a question via a conversation and the answer is a url, the conversation will stall on Telegram. (Works fine on Slack).

**Comment by davetosh** [comment]
Messenger and MS (via Skype) both accept the input of a url but each one handles saving it differently resulting in a value that isn't consistent.

**Comment by mpociot** [comment]
Can you post the answer values here?
Maybe there is a way to normalize it. 

Don't know what Telegram does in this case though. Will need to look it up

**Comment by davetosh** [comment]
Sure, here is Slack: http://bbc.co.uk
Here is MS (skype): a href="http://bbc.co.uk">http://bbc.co.uk </a
Here is messenger: ttp://bbc.co.uk

BTW - this is a great package, thanks for building it!

**Comment by davetosh** [comment]
Digging into this a bit more; turns out I had a bug in my code causing the issue from Skpye / Messenger. Botman handles urls just fine from those platforms, as it does from Slack. The only issue is Telegram, however, that is not a Botman problem but something on Telegram's side.
