### ISSUE TITLE
[Telegram] Inline bot

### ISSUE THREAD

**Issue by sirWill** [mpociot/botman#74]
I read all tests and manuals, but not found any info about it. Is there any opportunity to read inline queries to bot (in Telegram) and anwer on them?

**Comment by mpociot** [comment]
Can you show me a link about online queries? I'm not sure hat I know what you mean. 

You can send messages with buttons and get the selected answer.

**Comment by sirWill** [comment]
I mean when you mention bot in chat and it propose some commands. Like when you type @gif Some query to find in any chat.
There is documentation about this mode: https://core.telegram.org/bots/inline

**Comment by mpociot** [comment]
I like the idea of being able to `hear` for inline queries - but the response is very driver / Telegram specific because you need to return an array instead of a simple "message".

Do you have an idea on how an implementation with BotMan could look like?

I'm thinking of something like this:

```php
// Triggered in Telegram with "@myBotUser foo"
$bot->hears('foo', function($bot) {
    $results = [
        'Simplest result without image',
        Message::create('Result without image'),
        Message::create('Result with image')->image('http://foo.com/bar.png'),
    ];
    $bot->reply($results);
});
```

This would allow us to use:

- [InlineQueryResultArticle](https://core.telegram.org/bots/api#inlinequeryresultarticle)
- [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto)

**Comment by mpociot** [comment]
@sirWill I don't think the Telegram Inline Query driver should be inside the core of BotMan, as this driver is very specific.

Instead, I added the ability to load and use custom drivers. You can find a Telegram Inline Query driver here: https://gist.github.com/mpociot/926dbecec28d00fc21a31b0b378ac20e

To use it:

```php
// Load the driver
DriverManager::loadDriver(TelegramInlineQueryDriver::class);

// Listen for inline queries
$botman->hears('{movie}', function (BotMan $bot, $movie) {
    $bot->reply([
        [
            'type' => 'article',
            'id' => uniqid(),
            'title' => 'My result title',
            'input_message_content' => [
            	'message_text' => 'My message text'
            ]
        ]
    ]);
})->driver(TelegramInlineQueryDriver::DRIVER_NAME);
```

With the ability to load own custom drivers, things like this can easily be created :)

**Comment by Hexor** [comment]
how can I use inline mode when I use botman studio?

**Comment by nullcookies** [comment]
> how can I use inline mode when I use botman studio?

Found a solution?

**Comment by bamalt** [comment]
```
$bot->reply([
        [
            'type' => 'article',
            'id' => uniqid(),
            'title' => 'My result title',
            'input_message_content' => [
            	'message_text' => 'My message text'
            ]
        ]
]);
```

Isn't the replay method taken from the TelegramDriver in this case? Is not it?
We need the array to get into the replay method of the TelegramInlineQueryDriver class
I am not very experienced, so do not judge strictly if the question seems stupid to you.
