### ISSUE TITLE
Use complex regular expression

### ISSUE THREAD

**Issue by hosmelq** [mpociot/botman#76]
It would be great to use complex regular expressions.

I have this code.

```php
$botman->hears('deploy\s+([a-zA-Z]*)(?:\s*to\s*)?([a-zA-Z]*)?', function(BotMan $bot, $project, $env) {
});
```

I got the following error.

`array_combine(): Both parameters should have an equal number of elements`

i changed this line https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/BotMan.php#L193 to

```php
$parameters = array_slice($matches, 1);
```

works well, the variables are passed as expected.

Thank you.

**Comment by mpociot** [comment]
Thanks! Fixed in dev-master :)
