### ISSUE TITLE
$botman->hears: Listen for facebook payload

### ISSUE THREAD

**Issue by ribb3r** [mpociot/botman#77]
Hi,

maybe it's already possible, nevertheless it would be great if `$botman->hears` can listen for facebook payloads (e. g. used "Get started" button [Docs](https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button))

Thank you!

**Comment by mpociot** [comment]
If you use a question with buttons, the `$answer->getValue();` method will give you the payload.

**Comment by ribb3r** [comment]
Thanks for the answer.

If I have understood correctly, I have to create a `Question` object first to get access to the facebook message payload. But there cases where you can receive a facebook payload without creating a question (E. g. mentioned "Get started" button).

**Comment by mpociot** [comment]
Ahh okay - now I understood what you mean!
I just added support for this on `dev-master` 👍
