### ISSUE TITLE
fallback reply

### ISSUE THREAD

**Issue by ribb3r** [mpociot/botman#78]
Hi,

if I'm defining a `Question` object and set a fallback like `->fallback('Unable to create a new database')` do I have to call something during `$this->ask(...` to "fire" the fallback? I'm using the example `askForDatabase()` from the docs and the fallback reply is not visible (facebook driver)

Thank you.

**Comment by mpociot** [comment]
The fallback is currently only available for Slack messages. See https://api.slack.com/docs/message-attachments

I'm not sure if Facebook supports fallback messages.

**Comment by ribb3r** [comment]
ok, I see, thank you. Maybe you could update the documentation (if this has not occurred already).
