### ISSUE TITLE
[Facebook] Add support for X-HUB-SIGNATURE header

### ISSUE THREAD

**Issue by ribb3r** [mpociot/botman#79]
Hi,

Facebook provides a X-HUB-SIGNATURE header to verify if the request to the bot endpoint is performed from facebook. This check is straightforward.

1. Add config parameter to `$config` with the facebook app secret.
2. Check every incoming request if `$headers['X_HUB_SIGNATURE'] == 'sha1=' . hash_hmac('sha1', [REQUEST BODY], [APP SECRET])`

Thanks.

**Comment by mpociot** [comment]
That's nice! This can replace the current `matchesRequest` logic - https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Drivers/FacebookDriver.php#L49
