### ISSUE TITLE
Second  ask() answer in conversation can't be detected

### ISSUE THREAD

**Issue by butteff** [mpociot/botman#99]
Hello, I have some trouble with conversation. If I do one method only with one question - it works well, but if I want to ask one more question in another method from first - I have issue like on the picture.

[Issue picture](http://rgho.st/8Cqbz2K9P/image.png)

The problems are:
1. Another username and icon for ask() method
2. Answer on ask() in askAnswer() don't catch, instead of it I see reply of $botman->fallback

The code is here:

```php
public function run()
    {
        $this->askQuestion();
    }
    
    public function askQuestion() {
        $this->ask('Ok! I am ready to learn new phrases. On what message or pattern I should to have reaction?', function (Answer $answer) {    
            $this->question = strtolower($answer->getText());
            if ($this->question != null) {
                $this->say('Got it.', $this->parameters);
                $this->askAnswer();
            } else {
                $this->say('Sorry, something is wrong with your question, try to teach me again!', $this->parameters);
            } 
        });
    }

    public function askAnswer() {
        $this->ask('And what answer should to be on this?', function (Answer $answer) {
            $this->answer = strtolower($answer->getText());
            if ($this->answer != null) {
                $this->say('Understood!', $this->parameters);
                $this->remember($this->question, $this->answer);
            } else {
                $this->say('Sorry, something is wrong with the answer, try to teach me again!', $this->parameters);
            }
        });
    }
```
I've tried to do second ask in first method, but anyway I have the same problem.
It is slackRTM driver.
May be I do something wrong? Can you give any advice to me?

**Comment by mpociot** [comment]
Fixed in dev-master :)
If you need it working right now, please use the master branch as I will probably not tag a new release today.

**Comment by butteff** [comment]
thank you
